// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package socialclient

import (
	"context"

	"social/social"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddBlacklistReq          = social.AddBlacklistReq
	AddBlacklistResp         = social.AddBlacklistResp
	AnnouncementItem         = social.AnnouncementItem
	CreateAnnouncementReq    = social.CreateAnnouncementReq
	CreateAnnouncementResp   = social.CreateAnnouncementResp
	CreateGroupReq           = social.CreateGroupReq
	CreateGroupResp          = social.CreateGroupResp
	DeleteFriendReq          = social.DeleteFriendReq
	DeleteFriendResp         = social.DeleteFriendResp
	FriendItem               = social.FriendItem
	FriendRequestItem        = social.FriendRequestItem
	GetAnnouncementsReq      = social.GetAnnouncementsReq
	GetAnnouncementsResp     = social.GetAnnouncementsResp
	GetBlacklistReq          = social.GetBlacklistReq
	GetBlacklistResp         = social.GetBlacklistResp
	GetFriendRequestsReq     = social.GetFriendRequestsReq
	GetFriendRequestsResp    = social.GetFriendRequestsResp
	GetFriendsReq            = social.GetFriendsReq
	GetFriendsResp           = social.GetFriendsResp
	GetGroupInfoReq          = social.GetGroupInfoReq
	GetGroupInfoResp         = social.GetGroupInfoResp
	GetGroupInvitesReq       = social.GetGroupInvitesReq
	GetGroupInvitesResp      = social.GetGroupInvitesResp
	GetGroupJoinRequestsReq  = social.GetGroupJoinRequestsReq
	GetGroupJoinRequestsResp = social.GetGroupJoinRequestsResp
	GetGroupMembersReq       = social.GetGroupMembersReq
	GetGroupMembersResp      = social.GetGroupMembersResp
	GroupInfo                = social.GroupInfo
	GroupInviteItem          = social.GroupInviteItem
	GroupJoinRequestItem     = social.GroupJoinRequestItem
	GroupMemberItem          = social.GroupMemberItem
	HandleFriendReq          = social.HandleFriendReq
	HandleFriendResp         = social.HandleFriendResp
	HandleGroupInviteReq     = social.HandleGroupInviteReq
	HandleGroupInviteResp    = social.HandleGroupInviteResp
	HandleGroupJoinReq       = social.HandleGroupJoinReq
	HandleGroupJoinResp      = social.HandleGroupJoinResp
	InviteToGroupReq         = social.InviteToGroupReq
	InviteToGroupResp        = social.InviteToGroupResp
	IsBlacklistedReq         = social.IsBlacklistedReq
	IsBlacklistedResp        = social.IsBlacklistedResp
	IsFriendReq              = social.IsFriendReq
	IsFriendResp             = social.IsFriendResp
	IsGroupMemberReq         = social.IsGroupMemberReq
	IsGroupMemberResp        = social.IsGroupMemberResp
	IsGroupMutedReq          = social.IsGroupMutedReq
	IsGroupMutedResp         = social.IsGroupMutedResp
	JoinGroupReq             = social.JoinGroupReq
	JoinGroupResp            = social.JoinGroupResp
	KickMemberReq            = social.KickMemberReq
	KickMemberResp           = social.KickMemberResp
	LeaveGroupReq            = social.LeaveGroupReq
	LeaveGroupResp           = social.LeaveGroupResp
	MuteMemberReq            = social.MuteMemberReq
	MuteMemberResp           = social.MuteMemberResp
	RemoveBlacklistReq       = social.RemoveBlacklistReq
	RemoveBlacklistResp      = social.RemoveBlacklistResp
	SendFriendReq            = social.SendFriendReq
	SendFriendResp           = social.SendFriendResp
	TransferOwnerReq         = social.TransferOwnerReq
	TransferOwnerResp        = social.TransferOwnerResp
	UpdateFriendRemarkReq    = social.UpdateFriendRemarkReq
	UpdateFriendRemarkResp   = social.UpdateFriendRemarkResp
	UpdateGroupReq           = social.UpdateGroupReq
	UpdateGroupResp          = social.UpdateGroupResp

	Social interface {
		// 好友
		SendFriendRequest(ctx context.Context, in *SendFriendReq, opts ...grpc.CallOption) (*SendFriendResp, error)
		HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*HandleFriendResp, error)
		GetFriendRequests(ctx context.Context, in *GetFriendRequestsReq, opts ...grpc.CallOption) (*GetFriendRequestsResp, error)
		GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error)
		DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*DeleteFriendResp, error)
		UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkResp, error)
		IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendResp, error)
		// 黑名单
		AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*AddBlacklistResp, error)
		RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*RemoveBlacklistResp, error)
		IsBlacklisted(ctx context.Context, in *IsBlacklistedReq, opts ...grpc.CallOption) (*IsBlacklistedResp, error)
		GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error)
		// 群组
		CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
		GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
		UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error)
		JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error)
		LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*LeaveGroupResp, error)
		KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error)
		MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error)
		TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error)
		GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error)
		HandleGroupJoinRequest(ctx context.Context, in *HandleGroupJoinReq, opts ...grpc.CallOption) (*HandleGroupJoinResp, error)
		GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error)
		IsGroupMember(ctx context.Context, in *IsGroupMemberReq, opts ...grpc.CallOption) (*IsGroupMemberResp, error)
		IsGroupMuted(ctx context.Context, in *IsGroupMutedReq, opts ...grpc.CallOption) (*IsGroupMutedResp, error)
		// 群公告
		CreateAnnouncement(ctx context.Context, in *CreateAnnouncementReq, opts ...grpc.CallOption) (*CreateAnnouncementResp, error)
		GetAnnouncements(ctx context.Context, in *GetAnnouncementsReq, opts ...grpc.CallOption) (*GetAnnouncementsResp, error)
		// 邀请进群
		InviteToGroup(ctx context.Context, in *InviteToGroupReq, opts ...grpc.CallOption) (*InviteToGroupResp, error)
		HandleGroupInvite(ctx context.Context, in *HandleGroupInviteReq, opts ...grpc.CallOption) (*HandleGroupInviteResp, error)
		GetGroupInvites(ctx context.Context, in *GetGroupInvitesReq, opts ...grpc.CallOption) (*GetGroupInvitesResp, error)
	}

	defaultSocial struct {
		cli zrpc.Client
	}
)

func NewSocial(cli zrpc.Client) Social {
	return &defaultSocial{
		cli: cli,
	}
}

// 好友
func (m *defaultSocial) SendFriendRequest(ctx context.Context, in *SendFriendReq, opts ...grpc.CallOption) (*SendFriendResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.SendFriendRequest(ctx, in, opts...)
}

func (m *defaultSocial) HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*HandleFriendResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.HandleFriendRequest(ctx, in, opts...)
}

func (m *defaultSocial) GetFriendRequests(ctx context.Context, in *GetFriendRequestsReq, opts ...grpc.CallOption) (*GetFriendRequestsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetFriendRequests(ctx, in, opts...)
}

func (m *defaultSocial) GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetFriends(ctx, in, opts...)
}

func (m *defaultSocial) DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*DeleteFriendResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.DeleteFriend(ctx, in, opts...)
}

func (m *defaultSocial) UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.UpdateFriendRemark(ctx, in, opts...)
}

func (m *defaultSocial) IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.IsFriend(ctx, in, opts...)
}

// 黑名单
func (m *defaultSocial) AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*AddBlacklistResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.AddBlacklist(ctx, in, opts...)
}

func (m *defaultSocial) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*RemoveBlacklistResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.RemoveBlacklist(ctx, in, opts...)
}

func (m *defaultSocial) IsBlacklisted(ctx context.Context, in *IsBlacklistedReq, opts ...grpc.CallOption) (*IsBlacklistedResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.IsBlacklisted(ctx, in, opts...)
}

func (m *defaultSocial) GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetBlacklist(ctx, in, opts...)
}

// 群组
func (m *defaultSocial) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.CreateGroup(ctx, in, opts...)
}

func (m *defaultSocial) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetGroupInfo(ctx, in, opts...)
}

func (m *defaultSocial) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.UpdateGroup(ctx, in, opts...)
}

func (m *defaultSocial) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.JoinGroup(ctx, in, opts...)
}

func (m *defaultSocial) LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*LeaveGroupResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.LeaveGroup(ctx, in, opts...)
}

func (m *defaultSocial) KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.KickMember(ctx, in, opts...)
}

func (m *defaultSocial) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.MuteMember(ctx, in, opts...)
}

func (m *defaultSocial) TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.TransferOwner(ctx, in, opts...)
}

func (m *defaultSocial) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetGroupMembers(ctx, in, opts...)
}

func (m *defaultSocial) HandleGroupJoinRequest(ctx context.Context, in *HandleGroupJoinReq, opts ...grpc.CallOption) (*HandleGroupJoinResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.HandleGroupJoinRequest(ctx, in, opts...)
}

func (m *defaultSocial) GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetGroupJoinRequests(ctx, in, opts...)
}

func (m *defaultSocial) IsGroupMember(ctx context.Context, in *IsGroupMemberReq, opts ...grpc.CallOption) (*IsGroupMemberResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.IsGroupMember(ctx, in, opts...)
}

func (m *defaultSocial) IsGroupMuted(ctx context.Context, in *IsGroupMutedReq, opts ...grpc.CallOption) (*IsGroupMutedResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.IsGroupMuted(ctx, in, opts...)
}

// 群公告
func (m *defaultSocial) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementReq, opts ...grpc.CallOption) (*CreateAnnouncementResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.CreateAnnouncement(ctx, in, opts...)
}

func (m *defaultSocial) GetAnnouncements(ctx context.Context, in *GetAnnouncementsReq, opts ...grpc.CallOption) (*GetAnnouncementsResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetAnnouncements(ctx, in, opts...)
}

// 邀请进群
func (m *defaultSocial) InviteToGroup(ctx context.Context, in *InviteToGroupReq, opts ...grpc.CallOption) (*InviteToGroupResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.InviteToGroup(ctx, in, opts...)
}

func (m *defaultSocial) HandleGroupInvite(ctx context.Context, in *HandleGroupInviteReq, opts ...grpc.CallOption) (*HandleGroupInviteResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.HandleGroupInvite(ctx, in, opts...)
}

func (m *defaultSocial) GetGroupInvites(ctx context.Context, in *GetGroupInvitesReq, opts ...grpc.CallOption) (*GetGroupInvitesResp, error) {
	client := social.NewSocialClient(m.cli.Conn())
	return client.GetGroupInvites(ctx, in, opts...)
}
