// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: oss.proto

package server

import (
	"context"

	"oss/internal/logic"
	"oss/internal/svc"
	"oss/oss"
)

type OSSServer struct {
	svcCtx *svc.ServiceContext
	oss.UnimplementedOSSServer
}

func NewOSSServer(svcCtx *svc.ServiceContext) *OSSServer {
	return &OSSServer{
		svcCtx: svcCtx,
	}
}

// 简单上传（流式，适用于中小文件如图片、音频等）
func (s *OSSServer) SimpleUpload(stream oss.OSS_SimpleUploadServer) error {
	l := logic.NewSimpleUploadLogic(stream.Context(), s.svcCtx)
	return l.SimpleUpload(stream)
}

// 初始化分片上传，返回 UploadId
func (s *OSSServer) InitiateMultipartUpload(ctx context.Context, in *oss.InitiateUploadReq) (*oss.InitiateUploadResp, error) {
	l := logic.NewInitiateMultipartUploadLogic(ctx, s.svcCtx)
	return l.InitiateMultipartUpload(in)
}

// 上传分片（流式）
func (s *OSSServer) UploadPart(stream oss.OSS_UploadPartServer) error {
	l := logic.NewUploadPartLogic(stream.Context(), s.svcCtx)
	return l.UploadPart(stream)
}

// 完成分片上传（合并）
func (s *OSSServer) CompleteMultipartUpload(ctx context.Context, in *oss.CompleteUploadReq) (*oss.UploadResp, error) {
	l := logic.NewCompleteMultipartUploadLogic(ctx, s.svcCtx)
	return l.CompleteMultipartUpload(in)
}

// 取消上传
func (s *OSSServer) AbortMultipartUpload(ctx context.Context, in *oss.AbortUploadReq) (*oss.AbortUploadResp, error) {
	l := logic.NewAbortMultipartUploadLogic(ctx, s.svcCtx)
	return l.AbortMultipartUpload(in)
}

// 获取文件下载 URL
func (s *OSSServer) GetDownloadURL(ctx context.Context, in *oss.GetDownloadURLReq) (*oss.GetDownloadURLResp, error) {
	l := logic.NewGetDownloadURLLogic(ctx, s.svcCtx)
	return l.GetDownloadURL(in)
}

// 删除文件
func (s *OSSServer) DeleteFile(ctx context.Context, in *oss.DeleteFileReq) (*oss.DeleteFileResp, error) {
	l := logic.NewDeleteFileLogic(ctx, s.svcCtx)
	return l.DeleteFile(in)
}

// 获取文件信息
func (s *OSSServer) GetFileInfo(ctx context.Context, in *oss.GetFileInfoReq) (*oss.GetFileInfoResp, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}
