// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ========== 数据结构 ==========
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastLogin     int64                  `protobuf:"varint,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UserInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserInfo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserInfo) GetLastLogin() int64 {
	if x != nil {
		return x.LastLogin
	}
	return 0
}

// ========== 请求/响应 ==========
type GetUserByUIDReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUIDReq) Reset() {
	*x = GetUserByUIDReq{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUIDReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUIDReq) ProtoMessage() {}

func (x *GetUserByUIDReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUIDReq.ProtoReflect.Descriptor instead.
func (*GetUserByUIDReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByUIDReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserByUIDReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type BatchGetUserInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []int64                `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"` // 最多建议 100 个
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserInfoReq) Reset() {
	*x = BatchGetUserInfoReq{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserInfoReq) ProtoMessage() {}

func (x *BatchGetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserInfoReq.ProtoReflect.Descriptor instead.
func (*BatchGetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *BatchGetUserInfoReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type BatchGetUserInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         map[int64]*UserInfo    `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // uid -> UserInfo，不存在的 uid 不返回
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetUserInfoResp) Reset() {
	*x = BatchGetUserInfoResp{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetUserInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetUserInfoResp) ProtoMessage() {}

func (x *BatchGetUserInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetUserInfoResp.ProtoReflect.Descriptor instead.
func (*BatchGetUserInfoResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetUserInfoResp) GetUsers() map[int64]*UserInfo {
	if x != nil {
		return x.Users
	}
	return nil
}

type CreateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	OpaqueRecord  []byte                 `protobuf:"bytes,3,opt,name=opaque_record,json=opaqueRecord,proto3" json:"opaque_record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReq) Reset() {
	*x = CreateUserReq{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReq) ProtoMessage() {}

func (x *CreateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReq.ProtoReflect.Descriptor instead.
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateUserReq) GetOpaqueRecord() []byte {
	if x != nil {
		return x.OpaqueRecord
	}
	return nil
}

type CreateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResp) Reset() {
	*x = CreateUserResp{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResp) ProtoMessage() {}

func (x *CreateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResp.ProtoReflect.Descriptor instead.
func (*CreateUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserResp) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserReq) Reset() {
	*x = UpdateUserReq{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserReq) ProtoMessage() {}

func (x *UpdateUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserReq.ProtoReflect.Descriptor instead.
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateUserReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateUserReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

type UpdateUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResp) Reset() {
	*x = UpdateUserResp{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResp) ProtoMessage() {}

func (x *UpdateUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResp.ProtoReflect.Descriptor instead.
func (*UpdateUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

type UpdateUserStatusReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusReq) Reset() {
	*x = UpdateUserStatusReq{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusReq) ProtoMessage() {}

func (x *UpdateUserStatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusReq.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserStatusReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateUserStatusReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateUserStatusResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserStatusResp) Reset() {
	*x = UpdateUserStatusResp{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserStatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserStatusResp) ProtoMessage() {}

func (x *UpdateUserStatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserStatusResp.ProtoReflect.Descriptor instead.
func (*UpdateUserStatusResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

type UpdateLastLoginReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastLoginReq) Reset() {
	*x = UpdateLastLoginReq{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastLoginReq) ProtoMessage() {}

func (x *UpdateLastLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastLoginReq.ProtoReflect.Descriptor instead.
func (*UpdateLastLoginReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLastLoginReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UpdateLastLoginResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastLoginResp) Reset() {
	*x = UpdateLastLoginResp{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastLoginResp) ProtoMessage() {}

func (x *UpdateLastLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastLoginResp.ProtoReflect.Descriptor instead.
func (*UpdateLastLoginResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

type GetUserSettingsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsReq) Reset() {
	*x = GetUserSettingsReq{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsReq) ProtoMessage() {}

func (x *GetUserSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsReq.ProtoReflect.Descriptor instead.
func (*GetUserSettingsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserSettingsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type UserSettings struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Language        string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	MsgNotification bool                   `protobuf:"varint,2,opt,name=msg_notification,json=msgNotification,proto3" json:"msg_notification,omitempty"`
	SoundEnabled    bool                   `protobuf:"varint,3,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	AutoTranslate   bool                   `protobuf:"varint,4,opt,name=auto_translate,json=autoTranslate,proto3" json:"auto_translate,omitempty"`
	TranslateTarget string                 `protobuf:"bytes,5,opt,name=translate_target,json=translateTarget,proto3" json:"translate_target,omitempty"`
	ContentFilter   bool                   `protobuf:"varint,6,opt,name=content_filter,json=contentFilter,proto3" json:"content_filter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UserSettings) Reset() {
	*x = UserSettings{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSettings) ProtoMessage() {}

func (x *UserSettings) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSettings.ProtoReflect.Descriptor instead.
func (*UserSettings) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *UserSettings) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UserSettings) GetMsgNotification() bool {
	if x != nil {
		return x.MsgNotification
	}
	return false
}

func (x *UserSettings) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UserSettings) GetAutoTranslate() bool {
	if x != nil {
		return x.AutoTranslate
	}
	return false
}

func (x *UserSettings) GetTranslateTarget() string {
	if x != nil {
		return x.TranslateTarget
	}
	return ""
}

func (x *UserSettings) GetContentFilter() bool {
	if x != nil {
		return x.ContentFilter
	}
	return false
}

type GetUserSettingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *UserSettings          `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserSettingsResp) Reset() {
	*x = GetUserSettingsResp{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserSettingsResp) ProtoMessage() {}

func (x *GetUserSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserSettingsResp.ProtoReflect.Descriptor instead.
func (*GetUserSettingsResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserSettingsResp) GetSettings() *UserSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdateUserSettingsReq struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Uid             int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Language        string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	MsgNotification bool                   `protobuf:"varint,3,opt,name=msg_notification,json=msgNotification,proto3" json:"msg_notification,omitempty"`
	SoundEnabled    bool                   `protobuf:"varint,4,opt,name=sound_enabled,json=soundEnabled,proto3" json:"sound_enabled,omitempty"`
	AutoTranslate   bool                   `protobuf:"varint,5,opt,name=auto_translate,json=autoTranslate,proto3" json:"auto_translate,omitempty"`
	TranslateTarget string                 `protobuf:"bytes,6,opt,name=translate_target,json=translateTarget,proto3" json:"translate_target,omitempty"`
	ContentFilter   bool                   `protobuf:"varint,7,opt,name=content_filter,json=contentFilter,proto3" json:"content_filter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateUserSettingsReq) Reset() {
	*x = UpdateUserSettingsReq{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingsReq) ProtoMessage() {}

func (x *UpdateUserSettingsReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingsReq.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingsReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateUserSettingsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UpdateUserSettingsReq) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *UpdateUserSettingsReq) GetMsgNotification() bool {
	if x != nil {
		return x.MsgNotification
	}
	return false
}

func (x *UpdateUserSettingsReq) GetSoundEnabled() bool {
	if x != nil {
		return x.SoundEnabled
	}
	return false
}

func (x *UpdateUserSettingsReq) GetAutoTranslate() bool {
	if x != nil {
		return x.AutoTranslate
	}
	return false
}

func (x *UpdateUserSettingsReq) GetTranslateTarget() string {
	if x != nil {
		return x.TranslateTarget
	}
	return ""
}

func (x *UpdateUserSettingsReq) GetContentFilter() bool {
	if x != nil {
		return x.ContentFilter
	}
	return false
}

type UpdateUserSettingsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserSettingsResp) Reset() {
	*x = UpdateUserSettingsResp{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserSettingsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserSettingsResp) ProtoMessage() {}

func (x *UpdateUserSettingsResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserSettingsResp.ProtoReflect.Descriptor instead.
func (*UpdateUserSettingsResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

type IsUserBannedReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserBannedReq) Reset() {
	*x = IsUserBannedReq{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserBannedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserBannedReq) ProtoMessage() {}

func (x *IsUserBannedReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserBannedReq.ProtoReflect.Descriptor instead.
func (*IsUserBannedReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *IsUserBannedReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type IsUserBannedResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Banned        bool                   `protobuf:"varint,1,opt,name=banned,proto3" json:"banned,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserBannedResp) Reset() {
	*x = IsUserBannedResp{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserBannedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserBannedResp) ProtoMessage() {}

func (x *IsUserBannedResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserBannedResp.ProtoReflect.Descriptor instead.
func (*IsUserBannedResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *IsUserBannedResp) GetBanned() bool {
	if x != nil {
		return x.Banned
	}
	return false
}

func (x *IsUserBannedResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type AddPushTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Platform      string                 `protobuf:"bytes,3,opt,name=platform,proto3" json:"platform,omitempty"`
	Token         string                 `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPushTokenReq) Reset() {
	*x = AddPushTokenReq{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPushTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPushTokenReq) ProtoMessage() {}

func (x *AddPushTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPushTokenReq.ProtoReflect.Descriptor instead.
func (*AddPushTokenReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *AddPushTokenReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *AddPushTokenReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AddPushTokenReq) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *AddPushTokenReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AddPushTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPushTokenResp) Reset() {
	*x = AddPushTokenResp{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPushTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPushTokenResp) ProtoMessage() {}

func (x *AddPushTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPushTokenResp.ProtoReflect.Descriptor instead.
func (*AddPushTokenResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

type RemovePushTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId      string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePushTokenReq) Reset() {
	*x = RemovePushTokenReq{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePushTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePushTokenReq) ProtoMessage() {}

func (x *RemovePushTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePushTokenReq.ProtoReflect.Descriptor instead.
func (*RemovePushTokenReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

func (x *RemovePushTokenReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *RemovePushTokenReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type RemovePushTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePushTokenResp) Reset() {
	*x = RemovePushTokenResp{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePushTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePushTokenResp) ProtoMessage() {}

func (x *RemovePushTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePushTokenResp.ProtoReflect.Descriptor instead.
func (*RemovePushTokenResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"\xd3\x01\n" +
	"\bUserInfo\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\x03R\tupdatedAt\x12\x1d\n" +
	"\n" +
	"last_login\x18\b \x01(\x03R\tlastLogin\"9\n" +
	"\x0fGetUserByUIDReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"1\n" +
	"\vGetUserResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\")\n" +
	"\x13BatchGetUserInfoReq\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x03R\x04uids\"\x9d\x01\n" +
	"\x14BatchGetUserInfoResp\x12;\n" +
	"\x05users\x18\x01 \x03(\v2%.user.BatchGetUserInfoResp.UsersEntryR\x05users\x1aH\n" +
	"\n" +
	"UsersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12$\n" +
	"\x05value\x18\x02 \x01(\v2\x0e.user.UserInfoR\x05value:\x028\x01\"^\n" +
	"\rCreateUserReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12#\n" +
	"\ropaque_record\x18\x03 \x01(\fR\fopaqueRecord\"4\n" +
	"\x0eCreateUserResp\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"M\n" +
	"\rUpdateUserReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"\x10\n" +
	"\x0eUpdateUserResp\"?\n" +
	"\x13UpdateUserStatusReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x16\n" +
	"\x14UpdateUserStatusResp\"&\n" +
	"\x12UpdateLastLoginReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\x15\n" +
	"\x13UpdateLastLoginResp\"&\n" +
	"\x12GetUserSettingsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"\xf3\x01\n" +
	"\fUserSettings\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12)\n" +
	"\x10msg_notification\x18\x02 \x01(\bR\x0fmsgNotification\x12#\n" +
	"\rsound_enabled\x18\x03 \x01(\bR\fsoundEnabled\x12%\n" +
	"\x0eauto_translate\x18\x04 \x01(\bR\rautoTranslate\x12)\n" +
	"\x10translate_target\x18\x05 \x01(\tR\x0ftranslateTarget\x12%\n" +
	"\x0econtent_filter\x18\x06 \x01(\bR\rcontentFilter\"E\n" +
	"\x13GetUserSettingsResp\x12.\n" +
	"\bsettings\x18\x01 \x01(\v2\x12.user.UserSettingsR\bsettings\"\x8e\x02\n" +
	"\x15UpdateUserSettingsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12)\n" +
	"\x10msg_notification\x18\x03 \x01(\bR\x0fmsgNotification\x12#\n" +
	"\rsound_enabled\x18\x04 \x01(\bR\fsoundEnabled\x12%\n" +
	"\x0eauto_translate\x18\x05 \x01(\bR\rautoTranslate\x12)\n" +
	"\x10translate_target\x18\x06 \x01(\tR\x0ftranslateTarget\x12%\n" +
	"\x0econtent_filter\x18\a \x01(\bR\rcontentFilter\"\x18\n" +
	"\x16UpdateUserSettingsResp\"#\n" +
	"\x0fIsUserBannedReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"B\n" +
	"\x10IsUserBannedResp\x12\x16\n" +
	"\x06banned\x18\x01 \x01(\bR\x06banned\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"r\n" +
	"\x0fAddPushTokenReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1a\n" +
	"\bplatform\x18\x03 \x01(\tR\bplatform\x12\x14\n" +
	"\x05token\x18\x04 \x01(\tR\x05token\"\x12\n" +
	"\x10AddPushTokenResp\"C\n" +
	"\x12RemovePushTokenReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\"\x15\n" +
	"\x13RemovePushTokenResp2\xef\x05\n" +
	"\x04user\x128\n" +
	"\fGetUserByUID\x12\x15.user.GetUserByUIDReq\x1a\x11.user.GetUserResp\x12I\n" +
	"\x10BatchGetUserInfo\x12\x19.user.BatchGetUserInfoReq\x1a\x1a.user.BatchGetUserInfoResp\x127\n" +
	"\n" +
	"CreateUser\x12\x13.user.CreateUserReq\x1a\x14.user.CreateUserResp\x127\n" +
	"\n" +
	"UpdateUser\x12\x13.user.UpdateUserReq\x1a\x14.user.UpdateUserResp\x12I\n" +
	"\x10UpdateUserStatus\x12\x19.user.UpdateUserStatusReq\x1a\x1a.user.UpdateUserStatusResp\x12F\n" +
	"\x0fUpdateLastLogin\x12\x18.user.UpdateLastLoginReq\x1a\x19.user.UpdateLastLoginResp\x12F\n" +
	"\x0fGetUserSettings\x12\x18.user.GetUserSettingsReq\x1a\x19.user.GetUserSettingsResp\x12O\n" +
	"\x12UpdateUserSettings\x12\x1b.user.UpdateUserSettingsReq\x1a\x1c.user.UpdateUserSettingsResp\x12=\n" +
	"\fIsUserBanned\x12\x15.user.IsUserBannedReq\x1a\x16.user.IsUserBannedResp\x12=\n" +
	"\fAddPushToken\x12\x15.user.AddPushTokenReq\x1a\x16.user.AddPushTokenResp\x12F\n" +
	"\x0fRemovePushToken\x12\x18.user.RemovePushTokenReq\x1a\x19.user.RemovePushTokenRespB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_user_proto_goTypes = []any{
	(*UserInfo)(nil),               // 0: user.UserInfo
	(*GetUserByUIDReq)(nil),        // 1: user.GetUserByUIDReq
	(*GetUserResp)(nil),            // 2: user.GetUserResp
	(*BatchGetUserInfoReq)(nil),    // 3: user.BatchGetUserInfoReq
	(*BatchGetUserInfoResp)(nil),   // 4: user.BatchGetUserInfoResp
	(*CreateUserReq)(nil),          // 5: user.CreateUserReq
	(*CreateUserResp)(nil),         // 6: user.CreateUserResp
	(*UpdateUserReq)(nil),          // 7: user.UpdateUserReq
	(*UpdateUserResp)(nil),         // 8: user.UpdateUserResp
	(*UpdateUserStatusReq)(nil),    // 9: user.UpdateUserStatusReq
	(*UpdateUserStatusResp)(nil),   // 10: user.UpdateUserStatusResp
	(*UpdateLastLoginReq)(nil),     // 11: user.UpdateLastLoginReq
	(*UpdateLastLoginResp)(nil),    // 12: user.UpdateLastLoginResp
	(*GetUserSettingsReq)(nil),     // 13: user.GetUserSettingsReq
	(*UserSettings)(nil),           // 14: user.UserSettings
	(*GetUserSettingsResp)(nil),    // 15: user.GetUserSettingsResp
	(*UpdateUserSettingsReq)(nil),  // 16: user.UpdateUserSettingsReq
	(*UpdateUserSettingsResp)(nil), // 17: user.UpdateUserSettingsResp
	(*IsUserBannedReq)(nil),        // 18: user.IsUserBannedReq
	(*IsUserBannedResp)(nil),       // 19: user.IsUserBannedResp
	(*AddPushTokenReq)(nil),        // 20: user.AddPushTokenReq
	(*AddPushTokenResp)(nil),       // 21: user.AddPushTokenResp
	(*RemovePushTokenReq)(nil),     // 22: user.RemovePushTokenReq
	(*RemovePushTokenResp)(nil),    // 23: user.RemovePushTokenResp
	nil,                            // 24: user.BatchGetUserInfoResp.UsersEntry
}
var file_user_proto_depIdxs = []int32{
	0,  // 0: user.GetUserResp.user:type_name -> user.UserInfo
	24, // 1: user.BatchGetUserInfoResp.users:type_name -> user.BatchGetUserInfoResp.UsersEntry
	0,  // 2: user.CreateUserResp.user:type_name -> user.UserInfo
	14, // 3: user.GetUserSettingsResp.settings:type_name -> user.UserSettings
	0,  // 4: user.BatchGetUserInfoResp.UsersEntry.value:type_name -> user.UserInfo
	1,  // 5: user.user.GetUserByUID:input_type -> user.GetUserByUIDReq
	3,  // 6: user.user.BatchGetUserInfo:input_type -> user.BatchGetUserInfoReq
	5,  // 7: user.user.CreateUser:input_type -> user.CreateUserReq
	7,  // 8: user.user.UpdateUser:input_type -> user.UpdateUserReq
	9,  // 9: user.user.UpdateUserStatus:input_type -> user.UpdateUserStatusReq
	11, // 10: user.user.UpdateLastLogin:input_type -> user.UpdateLastLoginReq
	13, // 11: user.user.GetUserSettings:input_type -> user.GetUserSettingsReq
	16, // 12: user.user.UpdateUserSettings:input_type -> user.UpdateUserSettingsReq
	18, // 13: user.user.IsUserBanned:input_type -> user.IsUserBannedReq
	20, // 14: user.user.AddPushToken:input_type -> user.AddPushTokenReq
	22, // 15: user.user.RemovePushToken:input_type -> user.RemovePushTokenReq
	2,  // 16: user.user.GetUserByUID:output_type -> user.GetUserResp
	4,  // 17: user.user.BatchGetUserInfo:output_type -> user.BatchGetUserInfoResp
	6,  // 18: user.user.CreateUser:output_type -> user.CreateUserResp
	8,  // 19: user.user.UpdateUser:output_type -> user.UpdateUserResp
	10, // 20: user.user.UpdateUserStatus:output_type -> user.UpdateUserStatusResp
	12, // 21: user.user.UpdateLastLogin:output_type -> user.UpdateLastLoginResp
	15, // 22: user.user.GetUserSettings:output_type -> user.GetUserSettingsResp
	17, // 23: user.user.UpdateUserSettings:output_type -> user.UpdateUserSettingsResp
	19, // 24: user.user.IsUserBanned:output_type -> user.IsUserBannedResp
	21, // 25: user.user.AddPushToken:output_type -> user.AddPushTokenResp
	23, // 26: user.user.RemovePushToken:output_type -> user.RemovePushTokenResp
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
