// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: rag.proto

package ragclient

import (
	"context"

	"rag/rag/rag"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AnalyzeKBHealthReq  = rag.AnalyzeKBHealthReq
	AnalyzeKBHealthResp = rag.AnalyzeKBHealthResp
	AssessRetrievalReq  = rag.AssessRetrievalReq
	AssessRetrievalResp = rag.AssessRetrievalResp
	AuthorizeKBReq      = rag.AuthorizeKBReq
	AuthorizeKBResp     = rag.AuthorizeKBResp
	ChunkInfo           = rag.ChunkInfo
	Citation            = rag.Citation
	ConflictItem        = rag.ConflictItem
	CoverageGap         = rag.CoverageGap
	CreateKBReq         = rag.CreateKBReq
	CreateKBResp        = rag.CreateKBResp
	CrossKBSearchReq    = rag.CrossKBSearchReq
	CrossKBSearchResp   = rag.CrossKBSearchResp
	DeleteDocReq        = rag.DeleteDocReq
	DeleteDocResp       = rag.DeleteDocResp
	DeleteKBReq         = rag.DeleteKBReq
	DeleteKBResp        = rag.DeleteKBResp
	DocMeta             = rag.DocMeta
	Document            = rag.Document
	GetDocChunksReq     = rag.GetDocChunksReq
	GetDocChunksResp    = rag.GetDocChunksResp
	GetDocStatusReq     = rag.GetDocStatusReq
	GetDocStatusResp    = rag.GetDocStatusResp
	GetKBReq            = rag.GetKBReq
	GetKBResp           = rag.GetKBResp
	GetSubGraphReq      = rag.GetSubGraphReq
	GetSubGraphResp     = rag.GetSubGraphResp
	// 外部知识库同步
	ExternalSyncInfo        = rag.ExternalSyncInfo
	TriggerExternalSyncReq  = rag.TriggerExternalSyncReq
	TriggerExternalSyncResp = rag.TriggerExternalSyncResp
	GetSyncStatusReq        = rag.GetSyncStatusReq
	GetSyncStatusResp       = rag.GetSyncStatusResp
	ListExternalSyncsReq    = rag.ListExternalSyncsReq
	ListExternalSyncsResp   = rag.ListExternalSyncsResp
	GrantBotKBAccessReq     = rag.GrantBotKBAccessReq
	GrantBotKBAccessResp    = rag.GrantBotKBAccessResp
	GraphEntity             = rag.GraphEntity
	GraphRelation           = rag.GraphRelation
	KBAuthorization         = rag.KBAuthorization
	KBHealthReport          = rag.KBHealthReport
	KnowledgeBase           = rag.KnowledgeBase
	ListBotKBsReq           = rag.ListBotKBsReq
	ListBotKBsResp          = rag.ListBotKBsResp
	ListDocsReq             = rag.ListDocsReq
	ListDocsResp            = rag.ListDocsResp
	ListKBAuthsReq          = rag.ListKBAuthsReq
	ListKBAuthsResp         = rag.ListKBAuthsResp
	ListKBsReq              = rag.ListKBsReq
	ListKBsResp             = rag.ListKBsResp
	MetaCognitionScore      = rag.MetaCognitionScore
	RecallItem              = rag.RecallItem
	RevokeBotKBAccessReq    = rag.RevokeBotKBAccessReq
	RevokeBotKBAccessResp   = rag.RevokeBotKBAccessResp
	RevokeKBAuthReq         = rag.RevokeKBAuthReq
	RevokeKBAuthResp        = rag.RevokeKBAuthResp
	SearchKnowledgeReq      = rag.SearchKnowledgeReq
	SearchKnowledgeResp     = rag.SearchKnowledgeResp
	UpdateKBReq             = rag.UpdateKBReq
	UpdateKBResp            = rag.UpdateKBResp
	UploadDocReq            = rag.UploadDocReq
	UploadDocResp           = rag.UploadDocResp

	Rag interface {
		// 知识库管理
		CreateKnowledgeBase(ctx context.Context, in *CreateKBReq, opts ...grpc.CallOption) (*CreateKBResp, error)
		ListKnowledgeBases(ctx context.Context, in *ListKBsReq, opts ...grpc.CallOption) (*ListKBsResp, error)
		GetKnowledgeBase(ctx context.Context, in *GetKBReq, opts ...grpc.CallOption) (*GetKBResp, error)
		UpdateKnowledgeBase(ctx context.Context, in *UpdateKBReq, opts ...grpc.CallOption) (*UpdateKBResp, error)
		DeleteKnowledgeBase(ctx context.Context, in *DeleteKBReq, opts ...grpc.CallOption) (*DeleteKBResp, error)
		// 文档管理
		UploadDocument(ctx context.Context, opts ...grpc.CallOption) (rag.Rag_UploadDocumentClient, error)
		GetDocumentStatus(ctx context.Context, in *GetDocStatusReq, opts ...grpc.CallOption) (*GetDocStatusResp, error)
		ListDocuments(ctx context.Context, in *ListDocsReq, opts ...grpc.CallOption) (*ListDocsResp, error)
		DeleteDocument(ctx context.Context, in *DeleteDocReq, opts ...grpc.CallOption) (*DeleteDocResp, error)
		GetDocumentChunks(ctx context.Context, in *GetDocChunksReq, opts ...grpc.CallOption) (*GetDocChunksResp, error)
		// 知识库授权
		GrantBotKBAccess(ctx context.Context, in *GrantBotKBAccessReq, opts ...grpc.CallOption) (*GrantBotKBAccessResp, error)
		RevokeBotKBAccess(ctx context.Context, in *RevokeBotKBAccessReq, opts ...grpc.CallOption) (*RevokeBotKBAccessResp, error)
		AuthorizeKB(ctx context.Context, in *AuthorizeKBReq, opts ...grpc.CallOption) (*AuthorizeKBResp, error)
		RevokeKBAuth(ctx context.Context, in *RevokeKBAuthReq, opts ...grpc.CallOption) (*RevokeKBAuthResp, error)
		ListKBAuthorizations(ctx context.Context, in *ListKBAuthsReq, opts ...grpc.CallOption) (*ListKBAuthsResp, error)
		ListBotKnowledgeBases(ctx context.Context, in *ListBotKBsReq, opts ...grpc.CallOption) (*ListBotKBsResp, error)
		// RAG 检索
		SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error)
		CrossKBSearch(ctx context.Context, in *CrossKBSearchReq, opts ...grpc.CallOption) (*CrossKBSearchResp, error)
		// 元认知
		AssessRetrieval(ctx context.Context, in *AssessRetrievalReq, opts ...grpc.CallOption) (*AssessRetrievalResp, error)
		AnalyzeKBHealth(ctx context.Context, in *AnalyzeKBHealthReq, opts ...grpc.CallOption) (*AnalyzeKBHealthResp, error)
		// 图谱
		GetSubGraph(ctx context.Context, in *GetSubGraphReq, opts ...grpc.CallOption) (*GetSubGraphResp, error)
		// 外部知识库同步
		TriggerExternalSync(ctx context.Context, in *TriggerExternalSyncReq, opts ...grpc.CallOption) (*TriggerExternalSyncResp, error)
		GetSyncStatus(ctx context.Context, in *GetSyncStatusReq, opts ...grpc.CallOption) (*GetSyncStatusResp, error)
		ListExternalSyncs(ctx context.Context, in *ListExternalSyncsReq, opts ...grpc.CallOption) (*ListExternalSyncsResp, error)
	}

	defaultRag struct {
		cli zrpc.Client
	}
)

func NewRag(cli zrpc.Client) Rag {
	return &defaultRag{
		cli: cli,
	}
}

// 知识库管理
func (m *defaultRag) CreateKnowledgeBase(ctx context.Context, in *CreateKBReq, opts ...grpc.CallOption) (*CreateKBResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.CreateKnowledgeBase(ctx, in, opts...)
}

func (m *defaultRag) ListKnowledgeBases(ctx context.Context, in *ListKBsReq, opts ...grpc.CallOption) (*ListKBsResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.ListKnowledgeBases(ctx, in, opts...)
}

func (m *defaultRag) GetKnowledgeBase(ctx context.Context, in *GetKBReq, opts ...grpc.CallOption) (*GetKBResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.GetKnowledgeBase(ctx, in, opts...)
}

func (m *defaultRag) UpdateKnowledgeBase(ctx context.Context, in *UpdateKBReq, opts ...grpc.CallOption) (*UpdateKBResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.UpdateKnowledgeBase(ctx, in, opts...)
}

func (m *defaultRag) DeleteKnowledgeBase(ctx context.Context, in *DeleteKBReq, opts ...grpc.CallOption) (*DeleteKBResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.DeleteKnowledgeBase(ctx, in, opts...)
}

// 文档管理
func (m *defaultRag) UploadDocument(ctx context.Context, opts ...grpc.CallOption) (rag.Rag_UploadDocumentClient, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.UploadDocument(ctx, opts...)
}

func (m *defaultRag) GetDocumentStatus(ctx context.Context, in *GetDocStatusReq, opts ...grpc.CallOption) (*GetDocStatusResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.GetDocumentStatus(ctx, in, opts...)
}

func (m *defaultRag) ListDocuments(ctx context.Context, in *ListDocsReq, opts ...grpc.CallOption) (*ListDocsResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.ListDocuments(ctx, in, opts...)
}

func (m *defaultRag) DeleteDocument(ctx context.Context, in *DeleteDocReq, opts ...grpc.CallOption) (*DeleteDocResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.DeleteDocument(ctx, in, opts...)
}

func (m *defaultRag) GetDocumentChunks(ctx context.Context, in *GetDocChunksReq, opts ...grpc.CallOption) (*GetDocChunksResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.GetDocumentChunks(ctx, in, opts...)
}

// 知识库授权
func (m *defaultRag) GrantBotKBAccess(ctx context.Context, in *GrantBotKBAccessReq, opts ...grpc.CallOption) (*GrantBotKBAccessResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.GrantBotKBAccess(ctx, in, opts...)
}

func (m *defaultRag) RevokeBotKBAccess(ctx context.Context, in *RevokeBotKBAccessReq, opts ...grpc.CallOption) (*RevokeBotKBAccessResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.RevokeBotKBAccess(ctx, in, opts...)
}

func (m *defaultRag) AuthorizeKB(ctx context.Context, in *AuthorizeKBReq, opts ...grpc.CallOption) (*AuthorizeKBResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.AuthorizeKB(ctx, in, opts...)
}

func (m *defaultRag) RevokeKBAuth(ctx context.Context, in *RevokeKBAuthReq, opts ...grpc.CallOption) (*RevokeKBAuthResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.RevokeKBAuth(ctx, in, opts...)
}

func (m *defaultRag) ListKBAuthorizations(ctx context.Context, in *ListKBAuthsReq, opts ...grpc.CallOption) (*ListKBAuthsResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.ListKBAuthorizations(ctx, in, opts...)
}

func (m *defaultRag) ListBotKnowledgeBases(ctx context.Context, in *ListBotKBsReq, opts ...grpc.CallOption) (*ListBotKBsResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.ListBotKnowledgeBases(ctx, in, opts...)
}

// RAG 检索
func (m *defaultRag) SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.SearchKnowledge(ctx, in, opts...)
}

func (m *defaultRag) CrossKBSearch(ctx context.Context, in *CrossKBSearchReq, opts ...grpc.CallOption) (*CrossKBSearchResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.CrossKBSearch(ctx, in, opts...)
}

// 元认知
func (m *defaultRag) AssessRetrieval(ctx context.Context, in *AssessRetrievalReq, opts ...grpc.CallOption) (*AssessRetrievalResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.AssessRetrieval(ctx, in, opts...)
}

func (m *defaultRag) AnalyzeKBHealth(ctx context.Context, in *AnalyzeKBHealthReq, opts ...grpc.CallOption) (*AnalyzeKBHealthResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.AnalyzeKBHealth(ctx, in, opts...)
}

// 图谱
func (m *defaultRag) GetSubGraph(ctx context.Context, in *GetSubGraphReq, opts ...grpc.CallOption) (*GetSubGraphResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.GetSubGraph(ctx, in, opts...)
}

// 外部知识库同步
func (m *defaultRag) TriggerExternalSync(ctx context.Context, in *TriggerExternalSyncReq, opts ...grpc.CallOption) (*TriggerExternalSyncResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.TriggerExternalSync(ctx, in, opts...)
}

func (m *defaultRag) GetSyncStatus(ctx context.Context, in *GetSyncStatusReq, opts ...grpc.CallOption) (*GetSyncStatusResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.GetSyncStatus(ctx, in, opts...)
}

func (m *defaultRag) ListExternalSyncs(ctx context.Context, in *ListExternalSyncsReq, opts ...grpc.CallOption) (*ListExternalSyncsResp, error) {
	client := rag.NewRagClient(m.cli.Conn())
	return client.ListExternalSyncs(ctx, in, opts...)
}
