// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: conversation.proto

package conversation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConversationItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConvId         int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Type           string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar         string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GroupId        int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	LastMsgId      int64                  `protobuf:"varint,6,opt,name=last_msg_id,json=lastMsgId,proto3" json:"last_msg_id,omitempty"`
	LastMsgSnippet string                 `protobuf:"bytes,7,opt,name=last_msg_snippet,json=lastMsgSnippet,proto3" json:"last_msg_snippet,omitempty"`
	LastMsgTime    int64                  `protobuf:"varint,8,opt,name=last_msg_time,json=lastMsgTime,proto3" json:"last_msg_time,omitempty"`
	LastMsgSender  int64                  `protobuf:"varint,9,opt,name=last_msg_sender,json=lastMsgSender,proto3" json:"last_msg_sender,omitempty"`
	UnreadCount    int64                  `protobuf:"varint,10,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	Mute           bool                   `protobuf:"varint,11,opt,name=mute,proto3" json:"mute,omitempty"`
	Pinned         bool                   `protobuf:"varint,12,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Uid            int64                  `protobuf:"varint,13,opt,name=uid,proto3" json:"uid,omitempty"`
	PeerUid        int64                  `protobuf:"varint,14,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConversationItem) Reset() {
	*x = ConversationItem{}
	mi := &file_conversation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationItem) ProtoMessage() {}

func (x *ConversationItem) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationItem.ProtoReflect.Descriptor instead.
func (*ConversationItem) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationItem) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ConversationItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ConversationItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConversationItem) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *ConversationItem) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *ConversationItem) GetLastMsgId() int64 {
	if x != nil {
		return x.LastMsgId
	}
	return 0
}

func (x *ConversationItem) GetLastMsgSnippet() string {
	if x != nil {
		return x.LastMsgSnippet
	}
	return ""
}

func (x *ConversationItem) GetLastMsgTime() int64 {
	if x != nil {
		return x.LastMsgTime
	}
	return 0
}

func (x *ConversationItem) GetLastMsgSender() int64 {
	if x != nil {
		return x.LastMsgSender
	}
	return 0
}

func (x *ConversationItem) GetUnreadCount() int64 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

func (x *ConversationItem) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

func (x *ConversationItem) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *ConversationItem) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ConversationItem) GetPeerUid() int64 {
	if x != nil {
		return x.PeerUid
	}
	return 0
}

type GetConversationsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsReq) Reset() {
	*x = GetConversationsReq{}
	mi := &file_conversation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsReq) ProtoMessage() {}

func (x *GetConversationsReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsReq.ProtoReflect.Descriptor instead.
func (*GetConversationsReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{1}
}

func (x *GetConversationsReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetConversationsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ConversationItem    `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationsResp) Reset() {
	*x = GetConversationsResp{}
	mi := &file_conversation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationsResp) ProtoMessage() {}

func (x *GetConversationsResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationsResp.ProtoReflect.Descriptor instead.
func (*GetConversationsResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{2}
}

func (x *GetConversationsResp) GetList() []*ConversationItem {
	if x != nil {
		return x.List
	}
	return nil
}

type GetOrCreateSingleConvReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	PeerUid       int64                  `protobuf:"varint,2,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateSingleConvReq) Reset() {
	*x = GetOrCreateSingleConvReq{}
	mi := &file_conversation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateSingleConvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateSingleConvReq) ProtoMessage() {}

func (x *GetOrCreateSingleConvReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateSingleConvReq.ProtoReflect.Descriptor instead.
func (*GetOrCreateSingleConvReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{3}
}

func (x *GetOrCreateSingleConvReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetOrCreateSingleConvReq) GetPeerUid() int64 {
	if x != nil {
		return x.PeerUid
	}
	return 0
}

type GetOrCreateSingleConvResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateSingleConvResp) Reset() {
	*x = GetOrCreateSingleConvResp{}
	mi := &file_conversation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateSingleConvResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateSingleConvResp) ProtoMessage() {}

func (x *GetOrCreateSingleConvResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateSingleConvResp.ProtoReflect.Descriptor instead.
func (*GetOrCreateSingleConvResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{4}
}

func (x *GetOrCreateSingleConvResp) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *GetOrCreateSingleConvResp) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

type GetConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationReq) Reset() {
	*x = GetConversationReq{}
	mi := &file_conversation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationReq) ProtoMessage() {}

func (x *GetConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationReq.ProtoReflect.Descriptor instead.
func (*GetConversationReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{5}
}

func (x *GetConversationReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *GetConversationReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	GroupId       int64                  `protobuf:"varint,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Mute          bool                   `protobuf:"varint,6,opt,name=mute,proto3" json:"mute,omitempty"`
	Pinned        bool                   `protobuf:"varint,7,opt,name=pinned,proto3" json:"pinned,omitempty"`
	Uid           int64                  `protobuf:"varint,8,opt,name=uid,proto3" json:"uid,omitempty"`
	PeerUid       int64                  `protobuf:"varint,9,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConversationResp) Reset() {
	*x = GetConversationResp{}
	mi := &file_conversation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConversationResp) ProtoMessage() {}

func (x *GetConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConversationResp.ProtoReflect.Descriptor instead.
func (*GetConversationResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{6}
}

func (x *GetConversationResp) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *GetConversationResp) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetConversationResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetConversationResp) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetConversationResp) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *GetConversationResp) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

func (x *GetConversationResp) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *GetConversationResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetConversationResp) GetPeerUid() int64 {
	if x != nil {
		return x.PeerUid
	}
	return 0
}

type DeleteConversationReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationReq) Reset() {
	*x = DeleteConversationReq{}
	mi := &file_conversation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationReq) ProtoMessage() {}

func (x *DeleteConversationReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationReq.ProtoReflect.Descriptor instead.
func (*DeleteConversationReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteConversationReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *DeleteConversationReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type DeleteConversationResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteConversationResp) Reset() {
	*x = DeleteConversationResp{}
	mi := &file_conversation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteConversationResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteConversationResp) ProtoMessage() {}

func (x *DeleteConversationResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteConversationResp.ProtoReflect.Descriptor instead.
func (*DeleteConversationResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{8}
}

type SetConvMuteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Mute          bool                   `protobuf:"varint,3,opt,name=mute,proto3" json:"mute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConvMuteReq) Reset() {
	*x = SetConvMuteReq{}
	mi := &file_conversation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConvMuteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConvMuteReq) ProtoMessage() {}

func (x *SetConvMuteReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConvMuteReq.ProtoReflect.Descriptor instead.
func (*SetConvMuteReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{9}
}

func (x *SetConvMuteReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *SetConvMuteReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetConvMuteReq) GetMute() bool {
	if x != nil {
		return x.Mute
	}
	return false
}

type SetConvMuteResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConvMuteResp) Reset() {
	*x = SetConvMuteResp{}
	mi := &file_conversation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConvMuteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConvMuteResp) ProtoMessage() {}

func (x *SetConvMuteResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConvMuteResp.ProtoReflect.Descriptor instead.
func (*SetConvMuteResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{10}
}

type SetConvPinReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Pinned        bool                   `protobuf:"varint,3,opt,name=pinned,proto3" json:"pinned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConvPinReq) Reset() {
	*x = SetConvPinReq{}
	mi := &file_conversation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConvPinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConvPinReq) ProtoMessage() {}

func (x *SetConvPinReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConvPinReq.ProtoReflect.Descriptor instead.
func (*SetConvPinReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{11}
}

func (x *SetConvPinReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *SetConvPinReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SetConvPinReq) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

type SetConvPinResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConvPinResp) Reset() {
	*x = SetConvPinResp{}
	mi := &file_conversation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConvPinResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConvPinResp) ProtoMessage() {}

func (x *SetConvPinResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConvPinResp.ProtoReflect.Descriptor instead.
func (*SetConvPinResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{12}
}

type CreateGroupConvReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	MemberUids    []int64                `protobuf:"varint,4,rep,packed,name=member_uids,json=memberUids,proto3" json:"member_uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupConvReq) Reset() {
	*x = CreateGroupConvReq{}
	mi := &file_conversation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupConvReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupConvReq) ProtoMessage() {}

func (x *CreateGroupConvReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupConvReq.ProtoReflect.Descriptor instead.
func (*CreateGroupConvReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGroupConvReq) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateGroupConvReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupConvReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateGroupConvReq) GetMemberUids() []int64 {
	if x != nil {
		return x.MemberUids
	}
	return nil
}

type CreateGroupConvResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupConvResp) Reset() {
	*x = CreateGroupConvResp{}
	mi := &file_conversation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupConvResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupConvResp) ProtoMessage() {}

func (x *CreateGroupConvResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupConvResp.ProtoReflect.Descriptor instead.
func (*CreateGroupConvResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{14}
}

func (x *CreateGroupConvResp) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type AddConvMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uids          []int64                `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConvMembersReq) Reset() {
	*x = AddConvMembersReq{}
	mi := &file_conversation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConvMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConvMembersReq) ProtoMessage() {}

func (x *AddConvMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConvMembersReq.ProtoReflect.Descriptor instead.
func (*AddConvMembersReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{15}
}

func (x *AddConvMembersReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *AddConvMembersReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type AddConvMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddConvMembersResp) Reset() {
	*x = AddConvMembersResp{}
	mi := &file_conversation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddConvMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddConvMembersResp) ProtoMessage() {}

func (x *AddConvMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddConvMembersResp.ProtoReflect.Descriptor instead.
func (*AddConvMembersResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{16}
}

type RemoveConvMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uids          []int64                `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConvMembersReq) Reset() {
	*x = RemoveConvMembersReq{}
	mi := &file_conversation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConvMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConvMembersReq) ProtoMessage() {}

func (x *RemoveConvMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConvMembersReq.ProtoReflect.Descriptor instead.
func (*RemoveConvMembersReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveConvMembersReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *RemoveConvMembersReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type RemoveConvMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveConvMembersResp) Reset() {
	*x = RemoveConvMembersResp{}
	mi := &file_conversation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveConvMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveConvMembersResp) ProtoMessage() {}

func (x *RemoveConvMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveConvMembersResp.ProtoReflect.Descriptor instead.
func (*RemoveConvMembersResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{18}
}

type GetConvMembersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConvMembersReq) Reset() {
	*x = GetConvMembersReq{}
	mi := &file_conversation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConvMembersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvMembersReq) ProtoMessage() {}

func (x *GetConvMembersReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvMembersReq.ProtoReflect.Descriptor instead.
func (*GetConvMembersReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{19}
}

func (x *GetConvMembersReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

type GetConvMembersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uids          []int64                `protobuf:"varint,1,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConvMembersResp) Reset() {
	*x = GetConvMembersResp{}
	mi := &file_conversation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConvMembersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConvMembersResp) ProtoMessage() {}

func (x *GetConvMembersResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConvMembersResp.ProtoReflect.Descriptor instead.
func (*GetConvMembersResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{20}
}

func (x *GetConvMembersResp) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type ClearUnreadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUnreadReq) Reset() {
	*x = ClearUnreadReq{}
	mi := &file_conversation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUnreadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUnreadReq) ProtoMessage() {}

func (x *ClearUnreadReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUnreadReq.ProtoReflect.Descriptor instead.
func (*ClearUnreadReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{21}
}

func (x *ClearUnreadReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *ClearUnreadReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ClearUnreadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearUnreadResp) Reset() {
	*x = ClearUnreadResp{}
	mi := &file_conversation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearUnreadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearUnreadResp) ProtoMessage() {}

func (x *ClearUnreadResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearUnreadResp.ProtoReflect.Descriptor instead.
func (*ClearUnreadResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{22}
}

type GetTotalUnreadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalUnreadReq) Reset() {
	*x = GetTotalUnreadReq{}
	mi := &file_conversation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalUnreadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalUnreadReq) ProtoMessage() {}

func (x *GetTotalUnreadReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalUnreadReq.ProtoReflect.Descriptor instead.
func (*GetTotalUnreadReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{23}
}

func (x *GetTotalUnreadReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetTotalUnreadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTotalUnreadResp) Reset() {
	*x = GetTotalUnreadResp{}
	mi := &file_conversation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTotalUnreadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTotalUnreadResp) ProtoMessage() {}

func (x *GetTotalUnreadResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTotalUnreadResp.ProtoReflect.Descriptor instead.
func (*GetTotalUnreadResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{24}
}

func (x *GetTotalUnreadResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type UpdateLastMessageReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	MsgId         int64                  `protobuf:"varint,2,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Snippet       string                 `protobuf:"bytes,3,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Sender        int64                  `protobuf:"varint,4,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastMessageReq) Reset() {
	*x = UpdateLastMessageReq{}
	mi := &file_conversation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastMessageReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastMessageReq) ProtoMessage() {}

func (x *UpdateLastMessageReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastMessageReq.ProtoReflect.Descriptor instead.
func (*UpdateLastMessageReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateLastMessageReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *UpdateLastMessageReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *UpdateLastMessageReq) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *UpdateLastMessageReq) GetSender() int64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

type UpdateLastMessageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLastMessageResp) Reset() {
	*x = UpdateLastMessageResp{}
	mi := &file_conversation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLastMessageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLastMessageResp) ProtoMessage() {}

func (x *UpdateLastMessageResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLastMessageResp.ProtoReflect.Descriptor instead.
func (*UpdateLastMessageResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{26}
}

type IncrementUnreadReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConvId        int64                  `protobuf:"varint,1,opt,name=conv_id,json=convId,proto3" json:"conv_id,omitempty"`
	Uids          []int64                `protobuf:"varint,2,rep,packed,name=uids,proto3" json:"uids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementUnreadReq) Reset() {
	*x = IncrementUnreadReq{}
	mi := &file_conversation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementUnreadReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementUnreadReq) ProtoMessage() {}

func (x *IncrementUnreadReq) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementUnreadReq.ProtoReflect.Descriptor instead.
func (*IncrementUnreadReq) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{27}
}

func (x *IncrementUnreadReq) GetConvId() int64 {
	if x != nil {
		return x.ConvId
	}
	return 0
}

func (x *IncrementUnreadReq) GetUids() []int64 {
	if x != nil {
		return x.Uids
	}
	return nil
}

type IncrementUnreadResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementUnreadResp) Reset() {
	*x = IncrementUnreadResp{}
	mi := &file_conversation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementUnreadResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementUnreadResp) ProtoMessage() {}

func (x *IncrementUnreadResp) ProtoReflect() protoreflect.Message {
	mi := &file_conversation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementUnreadResp.ProtoReflect.Descriptor instead.
func (*IncrementUnreadResp) Descriptor() ([]byte, []int) {
	return file_conversation_proto_rawDescGZIP(), []int{28}
}

var File_conversation_proto protoreflect.FileDescriptor

const file_conversation_proto_rawDesc = "" +
	"\n" +
	"\x12conversation.proto\x12\fconversation\"\x98\x03\n" +
	"\x10ConversationItem\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12\x1e\n" +
	"\vlast_msg_id\x18\x06 \x01(\x03R\tlastMsgId\x12(\n" +
	"\x10last_msg_snippet\x18\a \x01(\tR\x0elastMsgSnippet\x12\"\n" +
	"\rlast_msg_time\x18\b \x01(\x03R\vlastMsgTime\x12&\n" +
	"\x0flast_msg_sender\x18\t \x01(\x03R\rlastMsgSender\x12!\n" +
	"\funread_count\x18\n" +
	" \x01(\x03R\vunreadCount\x12\x12\n" +
	"\x04mute\x18\v \x01(\bR\x04mute\x12\x16\n" +
	"\x06pinned\x18\f \x01(\bR\x06pinned\x12\x10\n" +
	"\x03uid\x18\r \x01(\x03R\x03uid\x12\x19\n" +
	"\bpeer_uid\x18\x0e \x01(\x03R\apeerUid\"'\n" +
	"\x13GetConversationsReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"J\n" +
	"\x14GetConversationsResp\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.conversation.ConversationItemR\x04list\"G\n" +
	"\x18GetOrCreateSingleConvReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\bpeer_uid\x18\x02 \x01(\x03R\apeerUid\"N\n" +
	"\x19GetOrCreateSingleConvResp\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\"?\n" +
	"\x12GetConversationReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"\xe2\x01\n" +
	"\x13GetConversationResp\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04mute\x18\x06 \x01(\bR\x04mute\x12\x16\n" +
	"\x06pinned\x18\a \x01(\bR\x06pinned\x12\x10\n" +
	"\x03uid\x18\b \x01(\x03R\x03uid\x12\x19\n" +
	"\bpeer_uid\x18\t \x01(\x03R\apeerUid\"B\n" +
	"\x15DeleteConversationReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"\x18\n" +
	"\x16DeleteConversationResp\"O\n" +
	"\x0eSetConvMuteReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x12\n" +
	"\x04mute\x18\x03 \x01(\bR\x04mute\"\x11\n" +
	"\x0fSetConvMuteResp\"R\n" +
	"\rSetConvPinReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06pinned\x18\x03 \x01(\bR\x06pinned\"\x10\n" +
	"\x0eSetConvPinResp\"|\n" +
	"\x12CreateGroupConvReq\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x1f\n" +
	"\vmember_uids\x18\x04 \x03(\x03R\n" +
	"memberUids\".\n" +
	"\x13CreateGroupConvResp\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\"@\n" +
	"\x11AddConvMembersReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\x03R\x04uids\"\x14\n" +
	"\x12AddConvMembersResp\"C\n" +
	"\x14RemoveConvMembersReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\x03R\x04uids\"\x17\n" +
	"\x15RemoveConvMembersResp\",\n" +
	"\x11GetConvMembersReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\"(\n" +
	"\x12GetConvMembersResp\x12\x12\n" +
	"\x04uids\x18\x01 \x03(\x03R\x04uids\";\n" +
	"\x0eClearUnreadReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\"\x11\n" +
	"\x0fClearUnreadResp\"%\n" +
	"\x11GetTotalUnreadReq\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\"*\n" +
	"\x12GetTotalUnreadResp\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"x\n" +
	"\x14UpdateLastMessageReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x15\n" +
	"\x06msg_id\x18\x02 \x01(\x03R\x05msgId\x12\x18\n" +
	"\asnippet\x18\x03 \x01(\tR\asnippet\x12\x16\n" +
	"\x06sender\x18\x04 \x01(\x03R\x06sender\"\x17\n" +
	"\x15UpdateLastMessageResp\"A\n" +
	"\x12IncrementUnreadReq\x12\x17\n" +
	"\aconv_id\x18\x01 \x01(\x03R\x06convId\x12\x12\n" +
	"\x04uids\x18\x02 \x03(\x03R\x04uids\"\x15\n" +
	"\x13IncrementUnreadResp2\xd8\t\n" +
	"\fconversation\x12Y\n" +
	"\x10GetConversations\x12!.conversation.GetConversationsReq\x1a\".conversation.GetConversationsResp\x12h\n" +
	"\x15GetOrCreateSingleConv\x12&.conversation.GetOrCreateSingleConvReq\x1a'.conversation.GetOrCreateSingleConvResp\x12V\n" +
	"\x0fGetConversation\x12 .conversation.GetConversationReq\x1a!.conversation.GetConversationResp\x12_\n" +
	"\x12DeleteConversation\x12#.conversation.DeleteConversationReq\x1a$.conversation.DeleteConversationResp\x12J\n" +
	"\vSetConvMute\x12\x1c.conversation.SetConvMuteReq\x1a\x1d.conversation.SetConvMuteResp\x12G\n" +
	"\n" +
	"SetConvPin\x12\x1b.conversation.SetConvPinReq\x1a\x1c.conversation.SetConvPinResp\x12V\n" +
	"\x0fCreateGroupConv\x12 .conversation.CreateGroupConvReq\x1a!.conversation.CreateGroupConvResp\x12S\n" +
	"\x0eAddConvMembers\x12\x1f.conversation.AddConvMembersReq\x1a .conversation.AddConvMembersResp\x12\\\n" +
	"\x11RemoveConvMembers\x12\".conversation.RemoveConvMembersReq\x1a#.conversation.RemoveConvMembersResp\x12S\n" +
	"\x0eGetConvMembers\x12\x1f.conversation.GetConvMembersReq\x1a .conversation.GetConvMembersResp\x12J\n" +
	"\vClearUnread\x12\x1c.conversation.ClearUnreadReq\x1a\x1d.conversation.ClearUnreadResp\x12S\n" +
	"\x0eGetTotalUnread\x12\x1f.conversation.GetTotalUnreadReq\x1a .conversation.GetTotalUnreadResp\x12\\\n" +
	"\x11UpdateLastMessage\x12\".conversation.UpdateLastMessageReq\x1a#.conversation.UpdateLastMessageResp\x12V\n" +
	"\x0fIncrementUnread\x12 .conversation.IncrementUnreadReq\x1a!.conversation.IncrementUnreadRespB\x10Z\x0e./conversationb\x06proto3"

var (
	file_conversation_proto_rawDescOnce sync.Once
	file_conversation_proto_rawDescData []byte
)

func file_conversation_proto_rawDescGZIP() []byte {
	file_conversation_proto_rawDescOnce.Do(func() {
		file_conversation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conversation_proto_rawDesc), len(file_conversation_proto_rawDesc)))
	})
	return file_conversation_proto_rawDescData
}

var file_conversation_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_conversation_proto_goTypes = []any{
	(*ConversationItem)(nil),          // 0: conversation.ConversationItem
	(*GetConversationsReq)(nil),       // 1: conversation.GetConversationsReq
	(*GetConversationsResp)(nil),      // 2: conversation.GetConversationsResp
	(*GetOrCreateSingleConvReq)(nil),  // 3: conversation.GetOrCreateSingleConvReq
	(*GetOrCreateSingleConvResp)(nil), // 4: conversation.GetOrCreateSingleConvResp
	(*GetConversationReq)(nil),        // 5: conversation.GetConversationReq
	(*GetConversationResp)(nil),       // 6: conversation.GetConversationResp
	(*DeleteConversationReq)(nil),     // 7: conversation.DeleteConversationReq
	(*DeleteConversationResp)(nil),    // 8: conversation.DeleteConversationResp
	(*SetConvMuteReq)(nil),            // 9: conversation.SetConvMuteReq
	(*SetConvMuteResp)(nil),           // 10: conversation.SetConvMuteResp
	(*SetConvPinReq)(nil),             // 11: conversation.SetConvPinReq
	(*SetConvPinResp)(nil),            // 12: conversation.SetConvPinResp
	(*CreateGroupConvReq)(nil),        // 13: conversation.CreateGroupConvReq
	(*CreateGroupConvResp)(nil),       // 14: conversation.CreateGroupConvResp
	(*AddConvMembersReq)(nil),         // 15: conversation.AddConvMembersReq
	(*AddConvMembersResp)(nil),        // 16: conversation.AddConvMembersResp
	(*RemoveConvMembersReq)(nil),      // 17: conversation.RemoveConvMembersReq
	(*RemoveConvMembersResp)(nil),     // 18: conversation.RemoveConvMembersResp
	(*GetConvMembersReq)(nil),         // 19: conversation.GetConvMembersReq
	(*GetConvMembersResp)(nil),        // 20: conversation.GetConvMembersResp
	(*ClearUnreadReq)(nil),            // 21: conversation.ClearUnreadReq
	(*ClearUnreadResp)(nil),           // 22: conversation.ClearUnreadResp
	(*GetTotalUnreadReq)(nil),         // 23: conversation.GetTotalUnreadReq
	(*GetTotalUnreadResp)(nil),        // 24: conversation.GetTotalUnreadResp
	(*UpdateLastMessageReq)(nil),      // 25: conversation.UpdateLastMessageReq
	(*UpdateLastMessageResp)(nil),     // 26: conversation.UpdateLastMessageResp
	(*IncrementUnreadReq)(nil),        // 27: conversation.IncrementUnreadReq
	(*IncrementUnreadResp)(nil),       // 28: conversation.IncrementUnreadResp
}
var file_conversation_proto_depIdxs = []int32{
	0,  // 0: conversation.GetConversationsResp.list:type_name -> conversation.ConversationItem
	1,  // 1: conversation.conversation.GetConversations:input_type -> conversation.GetConversationsReq
	3,  // 2: conversation.conversation.GetOrCreateSingleConv:input_type -> conversation.GetOrCreateSingleConvReq
	5,  // 3: conversation.conversation.GetConversation:input_type -> conversation.GetConversationReq
	7,  // 4: conversation.conversation.DeleteConversation:input_type -> conversation.DeleteConversationReq
	9,  // 5: conversation.conversation.SetConvMute:input_type -> conversation.SetConvMuteReq
	11, // 6: conversation.conversation.SetConvPin:input_type -> conversation.SetConvPinReq
	13, // 7: conversation.conversation.CreateGroupConv:input_type -> conversation.CreateGroupConvReq
	15, // 8: conversation.conversation.AddConvMembers:input_type -> conversation.AddConvMembersReq
	17, // 9: conversation.conversation.RemoveConvMembers:input_type -> conversation.RemoveConvMembersReq
	19, // 10: conversation.conversation.GetConvMembers:input_type -> conversation.GetConvMembersReq
	21, // 11: conversation.conversation.ClearUnread:input_type -> conversation.ClearUnreadReq
	23, // 12: conversation.conversation.GetTotalUnread:input_type -> conversation.GetTotalUnreadReq
	25, // 13: conversation.conversation.UpdateLastMessage:input_type -> conversation.UpdateLastMessageReq
	27, // 14: conversation.conversation.IncrementUnread:input_type -> conversation.IncrementUnreadReq
	2,  // 15: conversation.conversation.GetConversations:output_type -> conversation.GetConversationsResp
	4,  // 16: conversation.conversation.GetOrCreateSingleConv:output_type -> conversation.GetOrCreateSingleConvResp
	6,  // 17: conversation.conversation.GetConversation:output_type -> conversation.GetConversationResp
	8,  // 18: conversation.conversation.DeleteConversation:output_type -> conversation.DeleteConversationResp
	10, // 19: conversation.conversation.SetConvMute:output_type -> conversation.SetConvMuteResp
	12, // 20: conversation.conversation.SetConvPin:output_type -> conversation.SetConvPinResp
	14, // 21: conversation.conversation.CreateGroupConv:output_type -> conversation.CreateGroupConvResp
	16, // 22: conversation.conversation.AddConvMembers:output_type -> conversation.AddConvMembersResp
	18, // 23: conversation.conversation.RemoveConvMembers:output_type -> conversation.RemoveConvMembersResp
	20, // 24: conversation.conversation.GetConvMembers:output_type -> conversation.GetConvMembersResp
	22, // 25: conversation.conversation.ClearUnread:output_type -> conversation.ClearUnreadResp
	24, // 26: conversation.conversation.GetTotalUnread:output_type -> conversation.GetTotalUnreadResp
	26, // 27: conversation.conversation.UpdateLastMessage:output_type -> conversation.UpdateLastMessageResp
	28, // 28: conversation.conversation.IncrementUnread:output_type -> conversation.IncrementUnreadResp
	15, // [15:29] is the sub-list for method output_type
	1,  // [1:15] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_conversation_proto_init() }
func file_conversation_proto_init() {
	if File_conversation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conversation_proto_rawDesc), len(file_conversation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_conversation_proto_goTypes,
		DependencyIndexes: file_conversation_proto_depIdxs,
		MessageInfos:      file_conversation_proto_msgTypes,
	}.Build()
	File_conversation_proto = out.File
	file_conversation_proto_goTypes = nil
	file_conversation_proto_depIdxs = nil
}
