// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: conversation.proto

package conversation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Conversation_GetConversations_FullMethodName      = "/conversation.conversation/GetConversations"
	Conversation_GetOrCreateSingleConv_FullMethodName = "/conversation.conversation/GetOrCreateSingleConv"
	Conversation_GetConversation_FullMethodName       = "/conversation.conversation/GetConversation"
	Conversation_DeleteConversation_FullMethodName    = "/conversation.conversation/DeleteConversation"
	Conversation_SetConvMute_FullMethodName           = "/conversation.conversation/SetConvMute"
	Conversation_SetConvPin_FullMethodName            = "/conversation.conversation/SetConvPin"
	Conversation_CreateGroupConv_FullMethodName       = "/conversation.conversation/CreateGroupConv"
	Conversation_AddConvMembers_FullMethodName        = "/conversation.conversation/AddConvMembers"
	Conversation_RemoveConvMembers_FullMethodName     = "/conversation.conversation/RemoveConvMembers"
	Conversation_GetConvMembers_FullMethodName        = "/conversation.conversation/GetConvMembers"
)

// ConversationClient is the client API for Conversation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConversationClient interface {
	GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
	GetOrCreateSingleConv(ctx context.Context, in *GetOrCreateSingleConvReq, opts ...grpc.CallOption) (*GetOrCreateSingleConvResp, error)
	GetConversation(ctx context.Context, in *GetConversationReq, opts ...grpc.CallOption) (*GetConversationResp, error)
	DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error)
	SetConvMute(ctx context.Context, in *SetConvMuteReq, opts ...grpc.CallOption) (*SetConvMuteResp, error)
	SetConvPin(ctx context.Context, in *SetConvPinReq, opts ...grpc.CallOption) (*SetConvPinResp, error)
	CreateGroupConv(ctx context.Context, in *CreateGroupConvReq, opts ...grpc.CallOption) (*CreateGroupConvResp, error)
	AddConvMembers(ctx context.Context, in *AddConvMembersReq, opts ...grpc.CallOption) (*AddConvMembersResp, error)
	RemoveConvMembers(ctx context.Context, in *RemoveConvMembersReq, opts ...grpc.CallOption) (*RemoveConvMembersResp, error)
	GetConvMembers(ctx context.Context, in *GetConvMembersReq, opts ...grpc.CallOption) (*GetConvMembersResp, error)
}

type conversationClient struct {
	cc grpc.ClientConnInterface
}

func NewConversationClient(cc grpc.ClientConnInterface) ConversationClient {
	return &conversationClient{cc}
}

func (c *conversationClient) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationsResp)
	err := c.cc.Invoke(ctx, Conversation_GetConversations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) GetOrCreateSingleConv(ctx context.Context, in *GetOrCreateSingleConvReq, opts ...grpc.CallOption) (*GetOrCreateSingleConvResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrCreateSingleConvResp)
	err := c.cc.Invoke(ctx, Conversation_GetOrCreateSingleConv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) GetConversation(ctx context.Context, in *GetConversationReq, opts ...grpc.CallOption) (*GetConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConversationResp)
	err := c.cc.Invoke(ctx, Conversation_GetConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteConversationResp)
	err := c.cc.Invoke(ctx, Conversation_DeleteConversation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) SetConvMute(ctx context.Context, in *SetConvMuteReq, opts ...grpc.CallOption) (*SetConvMuteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConvMuteResp)
	err := c.cc.Invoke(ctx, Conversation_SetConvMute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) SetConvPin(ctx context.Context, in *SetConvPinReq, opts ...grpc.CallOption) (*SetConvPinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConvPinResp)
	err := c.cc.Invoke(ctx, Conversation_SetConvPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) CreateGroupConv(ctx context.Context, in *CreateGroupConvReq, opts ...grpc.CallOption) (*CreateGroupConvResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupConvResp)
	err := c.cc.Invoke(ctx, Conversation_CreateGroupConv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) AddConvMembers(ctx context.Context, in *AddConvMembersReq, opts ...grpc.CallOption) (*AddConvMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddConvMembersResp)
	err := c.cc.Invoke(ctx, Conversation_AddConvMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) RemoveConvMembers(ctx context.Context, in *RemoveConvMembersReq, opts ...grpc.CallOption) (*RemoveConvMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveConvMembersResp)
	err := c.cc.Invoke(ctx, Conversation_RemoveConvMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *conversationClient) GetConvMembers(ctx context.Context, in *GetConvMembersReq, opts ...grpc.CallOption) (*GetConvMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConvMembersResp)
	err := c.cc.Invoke(ctx, Conversation_GetConvMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConversationServer is the server API for Conversation service.
// All implementations must embed UnimplementedConversationServer
// for forward compatibility.
type ConversationServer interface {
	GetConversations(context.Context, *GetConversationsReq) (*GetConversationsResp, error)
	GetOrCreateSingleConv(context.Context, *GetOrCreateSingleConvReq) (*GetOrCreateSingleConvResp, error)
	GetConversation(context.Context, *GetConversationReq) (*GetConversationResp, error)
	DeleteConversation(context.Context, *DeleteConversationReq) (*DeleteConversationResp, error)
	SetConvMute(context.Context, *SetConvMuteReq) (*SetConvMuteResp, error)
	SetConvPin(context.Context, *SetConvPinReq) (*SetConvPinResp, error)
	CreateGroupConv(context.Context, *CreateGroupConvReq) (*CreateGroupConvResp, error)
	AddConvMembers(context.Context, *AddConvMembersReq) (*AddConvMembersResp, error)
	RemoveConvMembers(context.Context, *RemoveConvMembersReq) (*RemoveConvMembersResp, error)
	GetConvMembers(context.Context, *GetConvMembersReq) (*GetConvMembersResp, error)
	mustEmbedUnimplementedConversationServer()
}

// UnimplementedConversationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConversationServer struct{}

func (UnimplementedConversationServer) GetConversations(context.Context, *GetConversationsReq) (*GetConversationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversations not implemented")
}
func (UnimplementedConversationServer) GetOrCreateSingleConv(context.Context, *GetOrCreateSingleConvReq) (*GetOrCreateSingleConvResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrCreateSingleConv not implemented")
}
func (UnimplementedConversationServer) GetConversation(context.Context, *GetConversationReq) (*GetConversationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConversation not implemented")
}
func (UnimplementedConversationServer) DeleteConversation(context.Context, *DeleteConversationReq) (*DeleteConversationResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteConversation not implemented")
}
func (UnimplementedConversationServer) SetConvMute(context.Context, *SetConvMuteReq) (*SetConvMuteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConvMute not implemented")
}
func (UnimplementedConversationServer) SetConvPin(context.Context, *SetConvPinReq) (*SetConvPinResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConvPin not implemented")
}
func (UnimplementedConversationServer) CreateGroupConv(context.Context, *CreateGroupConvReq) (*CreateGroupConvResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupConv not implemented")
}
func (UnimplementedConversationServer) AddConvMembers(context.Context, *AddConvMembersReq) (*AddConvMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddConvMembers not implemented")
}
func (UnimplementedConversationServer) RemoveConvMembers(context.Context, *RemoveConvMembersReq) (*RemoveConvMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveConvMembers not implemented")
}
func (UnimplementedConversationServer) GetConvMembers(context.Context, *GetConvMembersReq) (*GetConvMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConvMembers not implemented")
}
func (UnimplementedConversationServer) mustEmbedUnimplementedConversationServer() {}
func (UnimplementedConversationServer) testEmbeddedByValue()                      {}

// UnsafeConversationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConversationServer will
// result in compilation errors.
type UnsafeConversationServer interface {
	mustEmbedUnimplementedConversationServer()
}

func RegisterConversationServer(s grpc.ServiceRegistrar, srv ConversationServer) {
	// If the following call panics, it indicates UnimplementedConversationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Conversation_ServiceDesc, srv)
}

func _Conversation_GetConversations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).GetConversations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_GetConversations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).GetConversations(ctx, req.(*GetConversationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_GetOrCreateSingleConv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrCreateSingleConvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).GetOrCreateSingleConv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_GetOrCreateSingleConv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).GetOrCreateSingleConv(ctx, req.(*GetOrCreateSingleConvReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_GetConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).GetConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_GetConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).GetConversation(ctx, req.(*GetConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_DeleteConversation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteConversationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).DeleteConversation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_DeleteConversation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).DeleteConversation(ctx, req.(*DeleteConversationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_SetConvMute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConvMuteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).SetConvMute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_SetConvMute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).SetConvMute(ctx, req.(*SetConvMuteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_SetConvPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConvPinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).SetConvPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_SetConvPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).SetConvPin(ctx, req.(*SetConvPinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_CreateGroupConv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupConvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).CreateGroupConv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_CreateGroupConv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).CreateGroupConv(ctx, req.(*CreateGroupConvReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_AddConvMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddConvMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).AddConvMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_AddConvMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).AddConvMembers(ctx, req.(*AddConvMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_RemoveConvMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveConvMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).RemoveConvMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_RemoveConvMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).RemoveConvMembers(ctx, req.(*RemoveConvMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Conversation_GetConvMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConvMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConversationServer).GetConvMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Conversation_GetConvMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConversationServer).GetConvMembers(ctx, req.(*GetConvMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Conversation_ServiceDesc is the grpc.ServiceDesc for Conversation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Conversation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conversation.conversation",
	HandlerType: (*ConversationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConversations",
			Handler:    _Conversation_GetConversations_Handler,
		},
		{
			MethodName: "GetOrCreateSingleConv",
			Handler:    _Conversation_GetOrCreateSingleConv_Handler,
		},
		{
			MethodName: "GetConversation",
			Handler:    _Conversation_GetConversation_Handler,
		},
		{
			MethodName: "DeleteConversation",
			Handler:    _Conversation_DeleteConversation_Handler,
		},
		{
			MethodName: "SetConvMute",
			Handler:    _Conversation_SetConvMute_Handler,
		},
		{
			MethodName: "SetConvPin",
			Handler:    _Conversation_SetConvPin_Handler,
		},
		{
			MethodName: "CreateGroupConv",
			Handler:    _Conversation_CreateGroupConv_Handler,
		},
		{
			MethodName: "AddConvMembers",
			Handler:    _Conversation_AddConvMembers_Handler,
		},
		{
			MethodName: "RemoveConvMembers",
			Handler:    _Conversation_RemoveConvMembers_Handler,
		},
		{
			MethodName: "GetConvMembers",
			Handler:    _Conversation_GetConvMembers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "conversation.proto",
}
