// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: social.proto

package social

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Social_SendFriendRequest_FullMethodName      = "/social.social/SendFriendRequest"
	Social_HandleFriendRequest_FullMethodName    = "/social.social/HandleFriendRequest"
	Social_GetFriendRequests_FullMethodName      = "/social.social/GetFriendRequests"
	Social_GetFriends_FullMethodName             = "/social.social/GetFriends"
	Social_DeleteFriend_FullMethodName           = "/social.social/DeleteFriend"
	Social_UpdateFriendRemark_FullMethodName     = "/social.social/UpdateFriendRemark"
	Social_IsFriend_FullMethodName               = "/social.social/IsFriend"
	Social_AddBlacklist_FullMethodName           = "/social.social/AddBlacklist"
	Social_RemoveBlacklist_FullMethodName        = "/social.social/RemoveBlacklist"
	Social_IsBlacklisted_FullMethodName          = "/social.social/IsBlacklisted"
	Social_GetBlacklist_FullMethodName           = "/social.social/GetBlacklist"
	Social_CreateGroup_FullMethodName            = "/social.social/CreateGroup"
	Social_GetGroupInfo_FullMethodName           = "/social.social/GetGroupInfo"
	Social_UpdateGroup_FullMethodName            = "/social.social/UpdateGroup"
	Social_JoinGroup_FullMethodName              = "/social.social/JoinGroup"
	Social_LeaveGroup_FullMethodName             = "/social.social/LeaveGroup"
	Social_KickMember_FullMethodName             = "/social.social/KickMember"
	Social_MuteMember_FullMethodName             = "/social.social/MuteMember"
	Social_TransferOwner_FullMethodName          = "/social.social/TransferOwner"
	Social_GetGroupMembers_FullMethodName        = "/social.social/GetGroupMembers"
	Social_HandleGroupJoinRequest_FullMethodName = "/social.social/HandleGroupJoinRequest"
	Social_GetGroupJoinRequests_FullMethodName   = "/social.social/GetGroupJoinRequests"
	Social_IsGroupMember_FullMethodName          = "/social.social/IsGroupMember"
	Social_IsGroupMuted_FullMethodName           = "/social.social/IsGroupMuted"
	Social_CreateAnnouncement_FullMethodName     = "/social.social/CreateAnnouncement"
	Social_GetAnnouncements_FullMethodName       = "/social.social/GetAnnouncements"
	Social_InviteToGroup_FullMethodName          = "/social.social/InviteToGroup"
	Social_HandleGroupInvite_FullMethodName      = "/social.social/HandleGroupInvite"
	Social_GetGroupInvites_FullMethodName        = "/social.social/GetGroupInvites"
)

// SocialClient is the client API for Social service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== 服务 ==========
type SocialClient interface {
	// 好友
	SendFriendRequest(ctx context.Context, in *SendFriendReq, opts ...grpc.CallOption) (*SendFriendResp, error)
	HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*HandleFriendResp, error)
	GetFriendRequests(ctx context.Context, in *GetFriendRequestsReq, opts ...grpc.CallOption) (*GetFriendRequestsResp, error)
	GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error)
	DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*DeleteFriendResp, error)
	UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkResp, error)
	IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendResp, error)
	// 黑名单
	AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*AddBlacklistResp, error)
	RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*RemoveBlacklistResp, error)
	IsBlacklisted(ctx context.Context, in *IsBlacklistedReq, opts ...grpc.CallOption) (*IsBlacklistedResp, error)
	GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error)
	// 群组
	CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error)
	GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error)
	UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error)
	JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error)
	LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*LeaveGroupResp, error)
	KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error)
	MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error)
	TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error)
	GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error)
	HandleGroupJoinRequest(ctx context.Context, in *HandleGroupJoinReq, opts ...grpc.CallOption) (*HandleGroupJoinResp, error)
	GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error)
	IsGroupMember(ctx context.Context, in *IsGroupMemberReq, opts ...grpc.CallOption) (*IsGroupMemberResp, error)
	IsGroupMuted(ctx context.Context, in *IsGroupMutedReq, opts ...grpc.CallOption) (*IsGroupMutedResp, error)
	// 群公告
	CreateAnnouncement(ctx context.Context, in *CreateAnnouncementReq, opts ...grpc.CallOption) (*CreateAnnouncementResp, error)
	GetAnnouncements(ctx context.Context, in *GetAnnouncementsReq, opts ...grpc.CallOption) (*GetAnnouncementsResp, error)
	// 邀请进群
	InviteToGroup(ctx context.Context, in *InviteToGroupReq, opts ...grpc.CallOption) (*InviteToGroupResp, error)
	HandleGroupInvite(ctx context.Context, in *HandleGroupInviteReq, opts ...grpc.CallOption) (*HandleGroupInviteResp, error)
	GetGroupInvites(ctx context.Context, in *GetGroupInvitesReq, opts ...grpc.CallOption) (*GetGroupInvitesResp, error)
}

type socialClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialClient(cc grpc.ClientConnInterface) SocialClient {
	return &socialClient{cc}
}

func (c *socialClient) SendFriendRequest(ctx context.Context, in *SendFriendReq, opts ...grpc.CallOption) (*SendFriendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFriendResp)
	err := c.cc.Invoke(ctx, Social_SendFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) HandleFriendRequest(ctx context.Context, in *HandleFriendReq, opts ...grpc.CallOption) (*HandleFriendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleFriendResp)
	err := c.cc.Invoke(ctx, Social_HandleFriendRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetFriendRequests(ctx context.Context, in *GetFriendRequestsReq, opts ...grpc.CallOption) (*GetFriendRequestsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendRequestsResp)
	err := c.cc.Invoke(ctx, Social_GetFriendRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetFriends(ctx context.Context, in *GetFriendsReq, opts ...grpc.CallOption) (*GetFriendsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFriendsResp)
	err := c.cc.Invoke(ctx, Social_GetFriends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) DeleteFriend(ctx context.Context, in *DeleteFriendReq, opts ...grpc.CallOption) (*DeleteFriendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFriendResp)
	err := c.cc.Invoke(ctx, Social_DeleteFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) UpdateFriendRemark(ctx context.Context, in *UpdateFriendRemarkReq, opts ...grpc.CallOption) (*UpdateFriendRemarkResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFriendRemarkResp)
	err := c.cc.Invoke(ctx, Social_UpdateFriendRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) IsFriend(ctx context.Context, in *IsFriendReq, opts ...grpc.CallOption) (*IsFriendResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsFriendResp)
	err := c.cc.Invoke(ctx, Social_IsFriend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) AddBlacklist(ctx context.Context, in *AddBlacklistReq, opts ...grpc.CallOption) (*AddBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddBlacklistResp)
	err := c.cc.Invoke(ctx, Social_AddBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistReq, opts ...grpc.CallOption) (*RemoveBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveBlacklistResp)
	err := c.cc.Invoke(ctx, Social_RemoveBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) IsBlacklisted(ctx context.Context, in *IsBlacklistedReq, opts ...grpc.CallOption) (*IsBlacklistedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsBlacklistedResp)
	err := c.cc.Invoke(ctx, Social_IsBlacklisted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetBlacklist(ctx context.Context, in *GetBlacklistReq, opts ...grpc.CallOption) (*GetBlacklistResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlacklistResp)
	err := c.cc.Invoke(ctx, Social_GetBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) CreateGroup(ctx context.Context, in *CreateGroupReq, opts ...grpc.CallOption) (*CreateGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResp)
	err := c.cc.Invoke(ctx, Social_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetGroupInfo(ctx context.Context, in *GetGroupInfoReq, opts ...grpc.CallOption) (*GetGroupInfoResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInfoResp)
	err := c.cc.Invoke(ctx, Social_GetGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) UpdateGroup(ctx context.Context, in *UpdateGroupReq, opts ...grpc.CallOption) (*UpdateGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGroupResp)
	err := c.cc.Invoke(ctx, Social_UpdateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) JoinGroup(ctx context.Context, in *JoinGroupReq, opts ...grpc.CallOption) (*JoinGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupResp)
	err := c.cc.Invoke(ctx, Social_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) LeaveGroup(ctx context.Context, in *LeaveGroupReq, opts ...grpc.CallOption) (*LeaveGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaveGroupResp)
	err := c.cc.Invoke(ctx, Social_LeaveGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) KickMember(ctx context.Context, in *KickMemberReq, opts ...grpc.CallOption) (*KickMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KickMemberResp)
	err := c.cc.Invoke(ctx, Social_KickMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) MuteMember(ctx context.Context, in *MuteMemberReq, opts ...grpc.CallOption) (*MuteMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MuteMemberResp)
	err := c.cc.Invoke(ctx, Social_MuteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) TransferOwner(ctx context.Context, in *TransferOwnerReq, opts ...grpc.CallOption) (*TransferOwnerResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwnerResp)
	err := c.cc.Invoke(ctx, Social_TransferOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetGroupMembers(ctx context.Context, in *GetGroupMembersReq, opts ...grpc.CallOption) (*GetGroupMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMembersResp)
	err := c.cc.Invoke(ctx, Social_GetGroupMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) HandleGroupJoinRequest(ctx context.Context, in *HandleGroupJoinReq, opts ...grpc.CallOption) (*HandleGroupJoinResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleGroupJoinResp)
	err := c.cc.Invoke(ctx, Social_HandleGroupJoinRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetGroupJoinRequests(ctx context.Context, in *GetGroupJoinRequestsReq, opts ...grpc.CallOption) (*GetGroupJoinRequestsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupJoinRequestsResp)
	err := c.cc.Invoke(ctx, Social_GetGroupJoinRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) IsGroupMember(ctx context.Context, in *IsGroupMemberReq, opts ...grpc.CallOption) (*IsGroupMemberResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsGroupMemberResp)
	err := c.cc.Invoke(ctx, Social_IsGroupMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) IsGroupMuted(ctx context.Context, in *IsGroupMutedReq, opts ...grpc.CallOption) (*IsGroupMutedResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsGroupMutedResp)
	err := c.cc.Invoke(ctx, Social_IsGroupMuted_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) CreateAnnouncement(ctx context.Context, in *CreateAnnouncementReq, opts ...grpc.CallOption) (*CreateAnnouncementResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAnnouncementResp)
	err := c.cc.Invoke(ctx, Social_CreateAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetAnnouncements(ctx context.Context, in *GetAnnouncementsReq, opts ...grpc.CallOption) (*GetAnnouncementsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnnouncementsResp)
	err := c.cc.Invoke(ctx, Social_GetAnnouncements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) InviteToGroup(ctx context.Context, in *InviteToGroupReq, opts ...grpc.CallOption) (*InviteToGroupResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteToGroupResp)
	err := c.cc.Invoke(ctx, Social_InviteToGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) HandleGroupInvite(ctx context.Context, in *HandleGroupInviteReq, opts ...grpc.CallOption) (*HandleGroupInviteResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleGroupInviteResp)
	err := c.cc.Invoke(ctx, Social_HandleGroupInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialClient) GetGroupInvites(ctx context.Context, in *GetGroupInvitesReq, opts ...grpc.CallOption) (*GetGroupInvitesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupInvitesResp)
	err := c.cc.Invoke(ctx, Social_GetGroupInvites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialServer is the server API for Social service.
// All implementations must embed UnimplementedSocialServer
// for forward compatibility.
//
// ========== 服务 ==========
type SocialServer interface {
	// 好友
	SendFriendRequest(context.Context, *SendFriendReq) (*SendFriendResp, error)
	HandleFriendRequest(context.Context, *HandleFriendReq) (*HandleFriendResp, error)
	GetFriendRequests(context.Context, *GetFriendRequestsReq) (*GetFriendRequestsResp, error)
	GetFriends(context.Context, *GetFriendsReq) (*GetFriendsResp, error)
	DeleteFriend(context.Context, *DeleteFriendReq) (*DeleteFriendResp, error)
	UpdateFriendRemark(context.Context, *UpdateFriendRemarkReq) (*UpdateFriendRemarkResp, error)
	IsFriend(context.Context, *IsFriendReq) (*IsFriendResp, error)
	// 黑名单
	AddBlacklist(context.Context, *AddBlacklistReq) (*AddBlacklistResp, error)
	RemoveBlacklist(context.Context, *RemoveBlacklistReq) (*RemoveBlacklistResp, error)
	IsBlacklisted(context.Context, *IsBlacklistedReq) (*IsBlacklistedResp, error)
	GetBlacklist(context.Context, *GetBlacklistReq) (*GetBlacklistResp, error)
	// 群组
	CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error)
	GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error)
	UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupResp, error)
	JoinGroup(context.Context, *JoinGroupReq) (*JoinGroupResp, error)
	LeaveGroup(context.Context, *LeaveGroupReq) (*LeaveGroupResp, error)
	KickMember(context.Context, *KickMemberReq) (*KickMemberResp, error)
	MuteMember(context.Context, *MuteMemberReq) (*MuteMemberResp, error)
	TransferOwner(context.Context, *TransferOwnerReq) (*TransferOwnerResp, error)
	GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersResp, error)
	HandleGroupJoinRequest(context.Context, *HandleGroupJoinReq) (*HandleGroupJoinResp, error)
	GetGroupJoinRequests(context.Context, *GetGroupJoinRequestsReq) (*GetGroupJoinRequestsResp, error)
	IsGroupMember(context.Context, *IsGroupMemberReq) (*IsGroupMemberResp, error)
	IsGroupMuted(context.Context, *IsGroupMutedReq) (*IsGroupMutedResp, error)
	// 群公告
	CreateAnnouncement(context.Context, *CreateAnnouncementReq) (*CreateAnnouncementResp, error)
	GetAnnouncements(context.Context, *GetAnnouncementsReq) (*GetAnnouncementsResp, error)
	// 邀请进群
	InviteToGroup(context.Context, *InviteToGroupReq) (*InviteToGroupResp, error)
	HandleGroupInvite(context.Context, *HandleGroupInviteReq) (*HandleGroupInviteResp, error)
	GetGroupInvites(context.Context, *GetGroupInvitesReq) (*GetGroupInvitesResp, error)
	mustEmbedUnimplementedSocialServer()
}

// UnimplementedSocialServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSocialServer struct{}

func (UnimplementedSocialServer) SendFriendRequest(context.Context, *SendFriendReq) (*SendFriendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SendFriendRequest not implemented")
}
func (UnimplementedSocialServer) HandleFriendRequest(context.Context, *HandleFriendReq) (*HandleFriendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleFriendRequest not implemented")
}
func (UnimplementedSocialServer) GetFriendRequests(context.Context, *GetFriendRequestsReq) (*GetFriendRequestsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriendRequests not implemented")
}
func (UnimplementedSocialServer) GetFriends(context.Context, *GetFriendsReq) (*GetFriendsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFriends not implemented")
}
func (UnimplementedSocialServer) DeleteFriend(context.Context, *DeleteFriendReq) (*DeleteFriendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFriend not implemented")
}
func (UnimplementedSocialServer) UpdateFriendRemark(context.Context, *UpdateFriendRemarkReq) (*UpdateFriendRemarkResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFriendRemark not implemented")
}
func (UnimplementedSocialServer) IsFriend(context.Context, *IsFriendReq) (*IsFriendResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsFriend not implemented")
}
func (UnimplementedSocialServer) AddBlacklist(context.Context, *AddBlacklistReq) (*AddBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlacklist not implemented")
}
func (UnimplementedSocialServer) RemoveBlacklist(context.Context, *RemoveBlacklistReq) (*RemoveBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBlacklist not implemented")
}
func (UnimplementedSocialServer) IsBlacklisted(context.Context, *IsBlacklistedReq) (*IsBlacklistedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsBlacklisted not implemented")
}
func (UnimplementedSocialServer) GetBlacklist(context.Context, *GetBlacklistReq) (*GetBlacklistResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlacklist not implemented")
}
func (UnimplementedSocialServer) CreateGroup(context.Context, *CreateGroupReq) (*CreateGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedSocialServer) GetGroupInfo(context.Context, *GetGroupInfoReq) (*GetGroupInfoResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInfo not implemented")
}
func (UnimplementedSocialServer) UpdateGroup(context.Context, *UpdateGroupReq) (*UpdateGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGroup not implemented")
}
func (UnimplementedSocialServer) JoinGroup(context.Context, *JoinGroupReq) (*JoinGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedSocialServer) LeaveGroup(context.Context, *LeaveGroupReq) (*LeaveGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (UnimplementedSocialServer) KickMember(context.Context, *KickMemberReq) (*KickMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method KickMember not implemented")
}
func (UnimplementedSocialServer) MuteMember(context.Context, *MuteMemberReq) (*MuteMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MuteMember not implemented")
}
func (UnimplementedSocialServer) TransferOwner(context.Context, *TransferOwnerReq) (*TransferOwnerResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwner not implemented")
}
func (UnimplementedSocialServer) GetGroupMembers(context.Context, *GetGroupMembersReq) (*GetGroupMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMembers not implemented")
}
func (UnimplementedSocialServer) HandleGroupJoinRequest(context.Context, *HandleGroupJoinReq) (*HandleGroupJoinResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGroupJoinRequest not implemented")
}
func (UnimplementedSocialServer) GetGroupJoinRequests(context.Context, *GetGroupJoinRequestsReq) (*GetGroupJoinRequestsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupJoinRequests not implemented")
}
func (UnimplementedSocialServer) IsGroupMember(context.Context, *IsGroupMemberReq) (*IsGroupMemberResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsGroupMember not implemented")
}
func (UnimplementedSocialServer) IsGroupMuted(context.Context, *IsGroupMutedReq) (*IsGroupMutedResp, error) {
	return nil, status.Error(codes.Unimplemented, "method IsGroupMuted not implemented")
}
func (UnimplementedSocialServer) CreateAnnouncement(context.Context, *CreateAnnouncementReq) (*CreateAnnouncementResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAnnouncement not implemented")
}
func (UnimplementedSocialServer) GetAnnouncements(context.Context, *GetAnnouncementsReq) (*GetAnnouncementsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnnouncements not implemented")
}
func (UnimplementedSocialServer) InviteToGroup(context.Context, *InviteToGroupReq) (*InviteToGroupResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteToGroup not implemented")
}
func (UnimplementedSocialServer) HandleGroupInvite(context.Context, *HandleGroupInviteReq) (*HandleGroupInviteResp, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleGroupInvite not implemented")
}
func (UnimplementedSocialServer) GetGroupInvites(context.Context, *GetGroupInvitesReq) (*GetGroupInvitesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupInvites not implemented")
}
func (UnimplementedSocialServer) mustEmbedUnimplementedSocialServer() {}
func (UnimplementedSocialServer) testEmbeddedByValue()                {}

// UnsafeSocialServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialServer will
// result in compilation errors.
type UnsafeSocialServer interface {
	mustEmbedUnimplementedSocialServer()
}

func RegisterSocialServer(s grpc.ServiceRegistrar, srv SocialServer) {
	// If the following call panics, it indicates UnimplementedSocialServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Social_ServiceDesc, srv)
}

func _Social_SendFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).SendFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_SendFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).SendFriendRequest(ctx, req.(*SendFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_HandleFriendRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).HandleFriendRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_HandleFriendRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).HandleFriendRequest(ctx, req.(*HandleFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetFriendRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetFriendRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetFriendRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetFriendRequests(ctx, req.(*GetFriendRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetFriends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFriendsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetFriends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetFriends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetFriends(ctx, req.(*GetFriendsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_DeleteFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).DeleteFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_DeleteFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).DeleteFriend(ctx, req.(*DeleteFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_UpdateFriendRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFriendRemarkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).UpdateFriendRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_UpdateFriendRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).UpdateFriendRemark(ctx, req.(*UpdateFriendRemarkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_IsFriend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsFriendReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).IsFriend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_IsFriend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).IsFriend(ctx, req.(*IsFriendReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_AddBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).AddBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_AddBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).AddBlacklist(ctx, req.(*AddBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_RemoveBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).RemoveBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_RemoveBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).RemoveBlacklist(ctx, req.(*RemoveBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_IsBlacklisted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsBlacklistedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).IsBlacklisted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_IsBlacklisted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).IsBlacklisted(ctx, req.(*IsBlacklistedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlacklistReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetBlacklist(ctx, req.(*GetBlacklistReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).CreateGroup(ctx, req.(*CreateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetGroupInfo(ctx, req.(*GetGroupInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_UpdateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).UpdateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_UpdateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).UpdateGroup(ctx, req.(*UpdateGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).JoinGroup(ctx, req.(*JoinGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_LeaveGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).LeaveGroup(ctx, req.(*LeaveGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_KickMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).KickMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_KickMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).KickMember(ctx, req.(*KickMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_MuteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MuteMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).MuteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_MuteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).MuteMember(ctx, req.(*MuteMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_TransferOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwnerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).TransferOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_TransferOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).TransferOwner(ctx, req.(*TransferOwnerReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetGroupMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetGroupMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetGroupMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetGroupMembers(ctx, req.(*GetGroupMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_HandleGroupJoinRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGroupJoinReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).HandleGroupJoinRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_HandleGroupJoinRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).HandleGroupJoinRequest(ctx, req.(*HandleGroupJoinReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetGroupJoinRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupJoinRequestsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetGroupJoinRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetGroupJoinRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetGroupJoinRequests(ctx, req.(*GetGroupJoinRequestsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_IsGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsGroupMemberReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).IsGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_IsGroupMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).IsGroupMember(ctx, req.(*IsGroupMemberReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_IsGroupMuted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsGroupMutedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).IsGroupMuted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_IsGroupMuted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).IsGroupMuted(ctx, req.(*IsGroupMutedReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_CreateAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAnnouncementReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).CreateAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_CreateAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).CreateAnnouncement(ctx, req.(*CreateAnnouncementReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetAnnouncements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnnouncementsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetAnnouncements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetAnnouncements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetAnnouncements(ctx, req.(*GetAnnouncementsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_InviteToGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteToGroupReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).InviteToGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_InviteToGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).InviteToGroup(ctx, req.(*InviteToGroupReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_HandleGroupInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleGroupInviteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).HandleGroupInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_HandleGroupInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).HandleGroupInvite(ctx, req.(*HandleGroupInviteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Social_GetGroupInvites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupInvitesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialServer).GetGroupInvites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Social_GetGroupInvites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialServer).GetGroupInvites(ctx, req.(*GetGroupInvitesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Social_ServiceDesc is the grpc.ServiceDesc for Social service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Social_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "social.social",
	HandlerType: (*SocialServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendFriendRequest",
			Handler:    _Social_SendFriendRequest_Handler,
		},
		{
			MethodName: "HandleFriendRequest",
			Handler:    _Social_HandleFriendRequest_Handler,
		},
		{
			MethodName: "GetFriendRequests",
			Handler:    _Social_GetFriendRequests_Handler,
		},
		{
			MethodName: "GetFriends",
			Handler:    _Social_GetFriends_Handler,
		},
		{
			MethodName: "DeleteFriend",
			Handler:    _Social_DeleteFriend_Handler,
		},
		{
			MethodName: "UpdateFriendRemark",
			Handler:    _Social_UpdateFriendRemark_Handler,
		},
		{
			MethodName: "IsFriend",
			Handler:    _Social_IsFriend_Handler,
		},
		{
			MethodName: "AddBlacklist",
			Handler:    _Social_AddBlacklist_Handler,
		},
		{
			MethodName: "RemoveBlacklist",
			Handler:    _Social_RemoveBlacklist_Handler,
		},
		{
			MethodName: "IsBlacklisted",
			Handler:    _Social_IsBlacklisted_Handler,
		},
		{
			MethodName: "GetBlacklist",
			Handler:    _Social_GetBlacklist_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Social_CreateGroup_Handler,
		},
		{
			MethodName: "GetGroupInfo",
			Handler:    _Social_GetGroupInfo_Handler,
		},
		{
			MethodName: "UpdateGroup",
			Handler:    _Social_UpdateGroup_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _Social_JoinGroup_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _Social_LeaveGroup_Handler,
		},
		{
			MethodName: "KickMember",
			Handler:    _Social_KickMember_Handler,
		},
		{
			MethodName: "MuteMember",
			Handler:    _Social_MuteMember_Handler,
		},
		{
			MethodName: "TransferOwner",
			Handler:    _Social_TransferOwner_Handler,
		},
		{
			MethodName: "GetGroupMembers",
			Handler:    _Social_GetGroupMembers_Handler,
		},
		{
			MethodName: "HandleGroupJoinRequest",
			Handler:    _Social_HandleGroupJoinRequest_Handler,
		},
		{
			MethodName: "GetGroupJoinRequests",
			Handler:    _Social_GetGroupJoinRequests_Handler,
		},
		{
			MethodName: "IsGroupMember",
			Handler:    _Social_IsGroupMember_Handler,
		},
		{
			MethodName: "IsGroupMuted",
			Handler:    _Social_IsGroupMuted_Handler,
		},
		{
			MethodName: "CreateAnnouncement",
			Handler:    _Social_CreateAnnouncement_Handler,
		},
		{
			MethodName: "GetAnnouncements",
			Handler:    _Social_GetAnnouncements_Handler,
		},
		{
			MethodName: "InviteToGroup",
			Handler:    _Social_InviteToGroup_Handler,
		},
		{
			MethodName: "HandleGroupInvite",
			Handler:    _Social_HandleGroupInvite_Handler,
		},
		{
			MethodName: "GetGroupInvites",
			Handler:    _Social_GetGroupInvites_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "social.proto",
}
