// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type AddBlacklistReq struct {
	UID int64 `json:"uid"`
}

type AddBlacklistResp struct {
	Result bool `json:"result"`
}

type AnnouncementItem struct {
	ID        int64  `json:"id"`
	UID       int64  `json:"uid"`
	Name      string `json:"name"`
	Content   string `json:"content"`
	Pinned    bool   `json:"pinned"`
	CreatedAt int64  `json:"created_at"`
}

type AuthorizeRequest struct {
	ResponseType string `form:"response_type"`
	ClientId     string `form:"client_id"`
	RedirectUri  string `form:"redirect_uri"`
	Scope        string `form:"scope"`
	State        string `form:"state"`
}

type ClearUnreadReq struct {
	ConvID int64 `json:"conv_id"`
}

type ClearUnreadResp struct {
}

type CompleteUploadRequest struct {
	UploadID string     `json:"upload_id"`
	Parts    []PartInfo `json:"parts"`
}

type ConversationItem struct {
	ConvID         int64  `json:"conv_id"`
	Type           string `json:"type"` // SINGLE / GROUP
	Name           string `json:"name"`
	Avatar         string `json:"avatar"`
	GroupID        int64  `json:"group_id,omitempty"`
	LastMsgID      int64  `json:"last_msg_id,omitempty"`
	LastMsgSnippet string `json:"last_msg_snippet,omitempty"`
	LastMsgTime    int64  `json:"last_msg_time,omitempty"`
	LastMsgSender  int64  `json:"last_msg_sender,omitempty"`
	UnreadCount    int64  `json:"unread_count"`
	Mute           bool   `json:"mute"`
	Pinned         bool   `json:"pinned"`
}

type CreateAnnouncementReq struct {
	GroupID int64  `json:"group_id"`
	Content string `json:"content"`
}

type CreateAnnouncementResp struct {
	Result bool `json:"result"`
}

type CreateGroupReq struct {
	Name       string  `json:"name"`
	Avatar     string  `json:"avatar,optional"`
	MemberUIDs []int64 `json:"member_uids,optional"`
	VerifyMode string  `json:"verify_mode,default=NONE"`
}

type CreateGroupResp struct {
	GroupID int64 `json:"group_id"`
	ConvID  int64 `json:"conv_id"`
}

type DeleteConversationReq struct {
	ConvID int64 `json:"conv_id"`
}

type DeleteConversationResp struct {
}

type DeleteFriendReq struct {
	UID int64 `json:"uid"`
}

type DeleteFriendResp struct {
	Result bool `json:"result"`
}

type EditMessageReq struct {
	ConvID  int64  `json:"conv_id"`
	MsgID   int64  `json:"msg_id"`
	Content string `json:"content"`
}

type EditMessageResp struct {
}

type EmptyReponse struct {
}

type FriendItem struct {
	UID       int64  `json:"uid"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Remark    string `json:"remark"`
	Status    string `json:"status"`
	Online    bool   `json:"online"`
	GroupName string `json:"group_name"`
}

type FriendRequestItem struct {
	ID        int64  `json:"id"`
	UID       int64  `json:"uid"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Message   string `json:"message"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
}

type GetAnnouncementsReq struct {
	GroupID int64 `path:"group_id"`
	Page    int   `form:"page,default=1"`
	Size    int   `form:"size,default=20"`
}

type GetAnnouncementsResp struct {
	List  []AnnouncementItem `json:"list"`
	Total int64              `json:"total"`
}

type GetBlacklistResp struct {
	List []FriendItem `json:"list"`
}

type GetConversationReq struct {
	ConvID int64 `path:"conv_id"`
}

type GetConversationResp struct {
	ConvID  int64  `json:"conv_id"`
	Type    string `json:"type"`
	Name    string `json:"name"`
	Avatar  string `json:"avatar"`
	GroupID int64  `json:"group_id,omitempty"`
	Mute    bool   `json:"mute"`
	Pinned  bool   `json:"pinned"`
}

type GetConversationsReq struct {
}

type GetConversationsResp struct {
	List []ConversationItem `json:"list"`
}

type GetFriendRequestsReq struct {
	Type string `form:"type,default=received"` // sent / received
	Page int    `form:"page,default=1"`        // 0表示获取全部
	Size int    `form:"size,default=20"`
}

type GetFriendRequestsResp struct {
	List  []FriendRequestItem `json:"list"`
	Total int64               `json:"total"`
}

type GetFriendsReq struct {
	Group string `form:"group,optional"`
}

type GetFriendsResp struct {
	List []FriendItem `json:"list"`
}

type GetGroupInfoReq struct {
	GroupID int64 `path:"group_id"`
}

type GetGroupInvitesReq struct {
}

type GetGroupInvitesResp struct {
	List []GroupInviteItem `json:"list"`
}

type GetGroupJoinRequestsReq struct {
	GroupID int64  `path:"group_id"`
	Status  string `form:"status,optional"`
}

type GetGroupJoinRequestsResp struct {
	List []GroupJoinRequestItem `json:"list"`
}

type GetGroupMembersReq struct {
	GroupID int64  `path:"group_id"`
	Role    string `form:"role,optional"`
}

type GetGroupMembersResp struct {
	List []GroupMemberItem `json:"list"`
}

type GetMessageReadMembersReq struct {
	ConvID int64 `path:"conv_id"`
	MsgID  int64 `path:"msg_id"`
}

type GetMessageReadMembersResp struct {
	List  []ReadMemberItem `json:"list"`
	Total int64            `json:"total"`
}

type GetMessagesReq struct {
	ConvID    int64  `path:"conv_id"`
	Cursor    int64  `form:"cursor,optional"` // 上一页最后一条消息 ID，空=最新
	Limit     int    `form:"limit,default=30"`
	Direction string `form:"direction,default=before"` // before / after
}

type GetMessagesResp struct {
	List    []MessageItem `json:"list"`
	HasMore bool          `json:"has_more"`
}

type GetOrCreateSingleConvReq struct {
	PeerUID int64 `json:"peer_uid"`
}

type GetOrCreateSingleConvResp struct {
	ConvID  int64 `json:"conv_id"`
	Created bool  `json:"created"`
}

type GetTotalUnreadResp struct {
	Count int64 `json:"count"`
}

type GroupInfoResp struct {
	GroupID     int64  `json:"group_id"`
	Name        string `json:"name"`
	Avatar      string `json:"avatar"`
	Owner       int64  `json:"owner"`
	MemberCount int    `json:"member_count"`
	Status      string `json:"status"`
	VerifyMode  string `json:"verify_mode"`
	CreatedAt   int64  `json:"created_at"`
}

type GroupInviteItem struct {
	ID          int64  `json:"id"`
	GroupID     int64  `json:"group_id"`
	GroupName   string `json:"group_name"`
	GroupAvatar string `json:"group_avatar"`
	InviterUID  int64  `json:"inviter_uid"`
	InviterName string `json:"inviter_name"`
	Message     string `json:"message"`
	CreatedAt   int64  `json:"created_at"`
}

type GroupJoinRequestItem struct {
	ID        int64  `json:"id"`
	UID       int64  `json:"uid"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Message   string `json:"message"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
}

type GroupMemberItem struct {
	UID       int64  `json:"uid"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Role      string `json:"role"`
	Nick      string `json:"nick"`
	JoinTime  int64  `json:"join_time"`
	MuteUntil int64  `json:"mute_until"`
}

type HandleFriendRequest struct {
	ReqID  int64  `path:"id"`
	Action string `json:"action"` // accept / reject
}

type HandleFriendResponse struct {
	Result bool `json:"result"`
}

type HandleGroupInviteReq struct {
	ID     int64  `path:"id"`
	Action string `json:"action"` // accept / reject
}

type HandleGroupInviteResp struct {
	Result bool `json:"result"`
}

type HandleGroupJoinReq struct {
	ReqID  int64  `path:"id"`
	Action string `json:"action"` // accept / reject
}

type HandleGroupJoinResp struct {
	Result bool `json:"result"`
}

type InitiateUploadRequest struct {
	FileName    string `json:"file_name"`
	ContentType string `json:"content_type,optional"`
	TotalSize   int64  `json:"total_size,optional"`
}

type InitiateUploadResponse struct {
	UploadID  string `json:"upload_id"`
	Bucket    string `json:"bucket"`
	ObjectKey string `json:"object_key"`
}

type InviteToGroupReq struct {
	GroupID     int64   `json:"group_id"`
	InviteeUIDs []int64 `json:"invitee_uids"`
	Message     string  `json:"message,optional"`
}

type InviteToGroupResp struct {
	FailedUIDs []int64 `json:"failed_uids"`
}

type JoinGroupReq struct {
	GroupID int64  `json:"group_id"`
	Message string `json:"message,optional"`
}

type JoinGroupResp struct {
	Result bool `json:"result"`
}

type KickMemberReq struct {
	GroupID int64 `json:"group_id"`
	UID     int64 `json:"uid"`
}

type KickMemberResp struct {
	Result bool `json:"result"`
}

type LeaveGroupReq struct {
	GroupID int64 `json:"group_id"`
}

type LeaveGroupResp struct {
	Result bool `json:"result"`
}

type LoginFinalizeRequest struct {
	Ke3       string `json:"k"`
	SessionId string `json:"sid"`
}

type LoginFinalizeResponse struct {
	UID          int64  `json:"uid"`
	Need2FA      bool   `json:"need_2fa"`            // 是否需要进行二次验证
	TFAToken     string `json:"tfa_token,omitempty"` // 二次验证临时令牌
	AccessToken  string `json:"access_token,omitempty"`
	RefreshToken string `json:"refresh_token,omitempty"`
	ExpiresAt    int64  `json:"expires_at,omitempty"`
}

type LoginInitRequest struct {
	Phone string `json:"phone"`
	Ke1   string `json:"k"`
}

type LoginInitResponse struct {
	Ke2       string `json:"k"`
	SessionId string `json:"sid"`
}

type LogoutRequest struct {
	Authorization string `header:"Authorization"`
}

type MessageItem struct {
	ID           int64  `json:"id"`
	ConvID       int64  `json:"conv_id"`
	Sender       int64  `json:"sender"`
	SenderName   string `json:"sender_name"`
	SenderAvatar string `json:"sender_avatar"`
	Type         string `json:"type"`
	Content      string `json:"content"`
	ContentType  string `json:"content_type"`
	QuoteMsgID   int64  `json:"quote_msg_id,omitempty"`
	QuoteContent string `json:"quote_content,omitempty"`
	Recalled     bool   `json:"recalled"`
	Edited       bool   `json:"edited"`
	Extra        string `json:"extra,omitempty"`
	CreatedAt    int64  `json:"created_at"`
}

type MuteMemberReq struct {
	GroupID  int64 `json:"group_id"`
	UID      int64 `json:"uid"`
	Duration int   `json:"duration"` // 秒
}

type MuteMemberResp struct {
	Result bool `json:"result"`
}

type PartInfo struct {
	PartNumber int    `json:"part_number"`
	ETag       string `json:"etag"`
}

type ReadMemberItem struct {
	UID    int64  `json:"uid"`
	Name   string `json:"name"`
	Avatar string `json:"avatar"`
	ReadAt int64  `json:"read_at"`
}

type RecallMessageReq struct {
	ConvID int64 `json:"conv_id"`
	MsgID  int64 `json:"msg_id"`
}

type RecallMessageResp struct {
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type RegisterFinalizeRequest struct {
	Phone              string `json:"phone"`
	Name               string `json:"name"`
	RegistrationRecord string `json:"r"`
}

type RegisterFinalizeResponse struct {
	Result bool   `json:"result"`
	Reason string `json:"reason,omitempty"`
}

type RegisterInitRequest struct {
	Phone               string `json:"phone"`
	RegistrationRequest string `json:"r"`
}

type RegisterInitResponse struct {
	ServerPublicKey      string `json:"spk"`
	RegistrationResponse string `json:"r"`
	CredentialIdentifier string `json:"cid,omitempty"`
}

type RemoveBlacklistReq struct {
	UID int64 `json:"uid"`
}

type RemoveBlacklistResp struct {
	Result bool `json:"result"`
}

type SearchMessagesReq struct {
	Keyword   string `form:"keyword"`
	ConvID    int64  `form:"conv_id,optional"`
	Sender    int64  `form:"sender,optional"`
	StartTime int64  `form:"start_time,optional"`
	EndTime   int64  `form:"end_time,optional"`
	Page      int    `form:"page,default=1"`
	Size      int    `form:"size,default=20"`
}

type SearchMessagesResp struct {
	List  []MessageItem `json:"list"`
	Total int64         `json:"total"`
}

type SendFriendRequest struct {
	UID     int64  `json:"uid"`
	Message string `json:"message,optional"`
}

type SendFriendResponse struct {
	Result bool `json:"result"`
}

type SetConvMuteReq struct {
	ConvID int64 `json:"conv_id"`
	Mute   bool  `json:"mute"`
}

type SetConvMuteResp struct {
}

type SetConvPinReq struct {
	ConvID int64 `json:"conv_id"`
	Pinned bool  `json:"pinned"`
}

type SetConvPinResp struct {
}

type SyncOfflineMessagesReq struct {
	DeviceID      string `form:"device_id"`
	LastSyncMsgID int64  `form:"last_sync_msg_id,optional"`
	Limit         int    `form:"limit,default=100"`
}

type SyncOfflineMessagesResp struct {
	List             []MessageItem `json:"list"`
	HasMore          bool          `json:"has_more"`
	NewLastSyncMsgID int64         `json:"new_last_sync_msg_id"`
}

type TFAVerifyRequest struct {
	TFAToken string `json:"tfa_token"`
	Code     string `json:"code"`
}

type TFAVerifyResponse struct {
	UID          int64  `json:"uid"`
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	ExpiresAt    int64  `json:"expires_at"`
}

type TokenRequest struct {
	GrantType    string `form:"grant_type"`
	ClientId     string `form:"client_id"`
	ClientSecret string `form:"client_secret"`
	Code         string `form:"code,optional"`
	Scope        string `form:"scope,optional"`
	RedirectUri  string `form:"redirect_uri,optional"`
	RefreshToken string `form:"refresh_token,optional"`
}

type TokenResponse struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	TokenType    string `json:"token_type"`
	ExpiresIn    int64  `json:"expires_in"`
	Scope        string `json:"scope"`
}

type TransferOwnerReq struct {
	GroupID  int64 `json:"group_id"`
	NewOwner int64 `json:"new_owner"`
}

type TransferOwnerResp struct {
	Result bool `json:"result"`
}

type UpdateFriendRemarkReq struct {
	UID       int64  `json:"uid"`
	Remark    string `json:"remark"`
	GroupName string `json:"group_name,optional"`
}

type UpdateFriendRemarkResp struct {
	Result bool `json:"result"`
}

type UpdateGroupReq struct {
	GroupID    int64  `json:"group_id"`
	Name       string `json:"name,optional"`
	Avatar     string `json:"avatar,optional"`
	VerifyMode string `json:"verify_mode,optional"`
}

type UpdateGroupResp struct {
	Result bool `json:"result"`
}

type UploadPartRequest struct {
	UploadID   string `form:"upload_id"`
	PartNumber int    `form:"part_number"`
}

type UploadPartResponse struct {
	ETag       string `json:"etag"`
	PartNumber int    `json:"part_number"`
}

type UploadResponse struct {
	FileName  string `json:"filename"`
	Size      int64  `json:"size"`
	Url       string `json:"url"`
	OssIndex  string `json:"oss_index"`
	ExpiresAt int64  `json:"expires_at"`
}

type UserInfoRequest struct {
	Uid           int64  `path:"uid"`
	Authorization string `header:"Authorization"`
}

type UserInfoResponse struct {
	UID       int64  `json:"uid"`
	Name      string `json:"name"`
	Avatar    string `json:"avatar"`
	Status    string `json:"status"`
	CreatedAt int64  `json:"created_at"`
	UpdatedAt int64  `json:"updated_at"`
	LastLogin int64  `json:"last_login"`
}
