global:
  scrape_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: [ 'otel-collector:8888' ]
    scrape_interval: 10s

  - job_name: 'rustfs-app-metrics'
    static_configs:
      - targets: [ 'otel-collector:8889' ]
    scrape_interval: 15s
    metric_relabel_configs:
      - source_labels: [ __name__ ]
        regex: 'go_.*'
        action: drop

  - job_name: 'gateway-api'
    static_configs:
      - targets: [ 'gateway-api:80' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'ws-gateway'
    static_configs:
      - targets: [ 'ws-gateway:8080' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'bot-api'
    static_configs:
      - targets: [ 'bot-api:8888' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'auth-rpc'
    static_configs:
      - targets: [ 'auth-services:6061' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'social-rpc'
    static_configs:
      - targets: [ 'social-services:6062' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'message-rpc'
    static_configs:
      - targets: [ 'message-services:6063' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'conversation-rpc'
    static_configs:
      - targets: [ 'conversation-services:6064' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'user-rpc'
    static_configs:
      - targets: [ 'user-services:6065' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'oss-rpc'
    static_configs:
      - targets: [ 'oss-services:6066' ]
    scrape_interval: 10s
    metrics_path: '/metrics'

  - job_name: 'tempo'
    static_configs:
      - targets: [ 'tempo:3200' ]

  - job_name: 'jaeger'
    static_configs:
      - targets: [ 'jaeger:14269' ]

  - job_name: 'loki'
    static_configs:
      - targets: [ 'loki:3100' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]

otlp:
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment.name
    - k8s.cluster.name
    - k8s.container.name
    - k8s.cronjob.name
    - k8s.daemonset.name
    - k8s.deployment.name
    - k8s.job.name
    - k8s.namespace.name
    - k8s.pod.name
    - k8s.replicaset.name
    - k8s.statefulset.name
  translation_strategy: NoUTF8EscapingWithSuffixes

storage:
  tsdb:
    out_of_order_time_window: 30m