// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: bot.proto

package server

import (
	"context"

	"bot/bot"
	"bot/internal/logic"
	"bot/internal/svc"
)

type BotServer struct {
	svcCtx *svc.ServiceContext
	bot.UnimplementedBotServer
}

func NewBotServer(svcCtx *svc.ServiceContext) *BotServer {
	return &BotServer{
		svcCtx: svcCtx,
	}
}

// Developer APIs (user-facing)
func (s *BotServer) CreateBot(ctx context.Context, in *bot.CreateBotReq) (*bot.CreateBotResp, error) {
	l := logic.NewCreateBotLogic(ctx, s.svcCtx)
	return l.CreateBot(in)
}

func (s *BotServer) ListMyBots(ctx context.Context, in *bot.ListMyBotsReq) (*bot.ListMyBotsResp, error) {
	l := logic.NewListMyBotsLogic(ctx, s.svcCtx)
	return l.ListMyBots(in)
}

func (s *BotServer) ListCommunityBots(ctx context.Context, in *bot.ListCommunityBotsReq) (*bot.ListCommunityBotsResp, error) {
	l := logic.NewListCommunityBotsLogic(ctx, s.svcCtx)
	return l.ListCommunityBots(in)
}

func (s *BotServer) GetBot(ctx context.Context, in *bot.GetBotReq) (*bot.GetBotResp, error) {
	l := logic.NewGetBotLogic(ctx, s.svcCtx)
	return l.GetBot(in)
}

func (s *BotServer) UpdateBot(ctx context.Context, in *bot.UpdateBotReq) (*bot.UpdateBotResp, error) {
	l := logic.NewUpdateBotLogic(ctx, s.svcCtx)
	return l.UpdateBot(in)
}

func (s *BotServer) DeleteBot(ctx context.Context, in *bot.DeleteBotReq) (*bot.DeleteBotResp, error) {
	l := logic.NewDeleteBotLogic(ctx, s.svcCtx)
	return l.DeleteBot(in)
}

func (s *BotServer) GetBotInstallations(ctx context.Context, in *bot.GetBotInstallationsReq) (*bot.GetBotInstallationsResp, error) {
	l := logic.NewGetBotInstallationsLogic(ctx, s.svcCtx)
	return l.GetBotInstallations(in)
}

func (s *BotServer) GetBotRateLimit(ctx context.Context, in *bot.GetBotRateLimitReq) (*bot.GetBotRateLimitResp, error) {
	l := logic.NewGetBotRateLimitLogic(ctx, s.svcCtx)
	return l.GetBotRateLimit(in)
}

func (s *BotServer) UpdateBotRateLimit(ctx context.Context, in *bot.UpdateBotRateLimitReq) (*bot.UpdateBotRateLimitResp, error) {
	l := logic.NewUpdateBotRateLimitLogic(ctx, s.svcCtx)
	return l.UpdateBotRateLimit(in)
}

func (s *BotServer) RegenerateCredential(ctx context.Context, in *bot.RegenerateCredentialReq) (*bot.RegenerateCredentialResp, error) {
	l := logic.NewRegenerateCredentialLogic(ctx, s.svcCtx)
	return l.RegenerateCredential(in)
}

func (s *BotServer) RotateWebhookSecret(ctx context.Context, in *bot.RotateWebhookSecretReq) (*bot.RotateWebhookSecretResp, error) {
	l := logic.NewRotateWebhookSecretLogic(ctx, s.svcCtx)
	return l.RotateWebhookSecret(in)
}

func (s *BotServer) GetEventDeliveries(ctx context.Context, in *bot.GetEventDeliveriesReq) (*bot.GetEventDeliveriesResp, error) {
	l := logic.NewGetEventDeliveriesLogic(ctx, s.svcCtx)
	return l.GetEventDeliveries(in)
}

func (s *BotServer) RetryEventDelivery(ctx context.Context, in *bot.RetryEventDeliveryReq) (*bot.RetryEventDeliveryResp, error) {
	l := logic.NewRetryEventDeliveryLogic(ctx, s.svcCtx)
	return l.RetryEventDelivery(in)
}

// Installation APIs
func (s *BotServer) GetConvBots(ctx context.Context, in *bot.GetConvBotsReq) (*bot.GetConvBotsResp, error) {
	l := logic.NewGetConvBotsLogic(ctx, s.svcCtx)
	return l.GetConvBots(in)
}

func (s *BotServer) InstallBot(ctx context.Context, in *bot.InstallBotReq) (*bot.InstallBotResp, error) {
	l := logic.NewInstallBotLogic(ctx, s.svcCtx)
	return l.InstallBot(in)
}

func (s *BotServer) UninstallBot(ctx context.Context, in *bot.UninstallBotReq) (*bot.UninstallBotResp, error) {
	l := logic.NewUninstallBotLogic(ctx, s.svcCtx)
	return l.UninstallBot(in)
}

// Bot APIs (bot 调用 Katheryne)
func (s *BotServer) BotGetConv(ctx context.Context, in *bot.BotGetConvReq) (*bot.BotGetConvResp, error) {
	l := logic.NewBotGetConvLogic(ctx, s.svcCtx)
	return l.BotGetConv(in)
}

func (s *BotServer) BotGetConvMembers(ctx context.Context, in *bot.BotGetConvMembersReq) (*bot.BotGetConvMembersResp, error) {
	l := logic.NewBotGetConvMembersLogic(ctx, s.svcCtx)
	return l.BotGetConvMembers(in)
}

func (s *BotServer) BotGetMsg(ctx context.Context, in *bot.BotGetMsgReq) (*bot.BotGetMsgResp, error) {
	l := logic.NewBotGetMsgLogic(ctx, s.svcCtx)
	return l.BotGetMsg(in)
}

func (s *BotServer) BotSendMsg(ctx context.Context, in *bot.BotSendMsgReq) (*bot.BotSendMsgResp, error) {
	l := logic.NewBotSendMsgLogic(ctx, s.svcCtx)
	return l.BotSendMsg(in)
}

func (s *BotServer) BotRecallMsg(ctx context.Context, in *bot.BotRecallMsgReq) (*bot.BotRecallMsgResp, error) {
	l := logic.NewBotRecallMsgLogic(ctx, s.svcCtx)
	return l.BotRecallMsg(in)
}

func (s *BotServer) BotReplyMsg(ctx context.Context, in *bot.BotReplyMsgReq) (*bot.BotReplyMsgResp, error) {
	l := logic.NewBotReplyMsgLogic(ctx, s.svcCtx)
	return l.BotReplyMsg(in)
}

func (s *BotServer) BotUploadFile(ctx context.Context, in *bot.BotUploadFileReq) (*bot.BotUploadFileResp, error) {
	l := logic.NewBotUploadFileLogic(ctx, s.svcCtx)
	return l.BotUploadFile(in)
}

func (s *BotServer) BotGetUser(ctx context.Context, in *bot.BotGetUserReq) (*bot.BotGetUserResp, error) {
	l := logic.NewBotGetUserLogic(ctx, s.svcCtx)
	return l.BotGetUser(in)
}

// OAuth2 APIs
func (s *BotServer) Authorize(ctx context.Context, in *bot.AuthorizeReq) (*bot.AuthorizeResp, error) {
	l := logic.NewAuthorizeLogic(ctx, s.svcCtx)
	return l.Authorize(in)
}

func (s *BotServer) ApproveAuthorize(ctx context.Context, in *bot.ApproveAuthorizeReq) (*bot.ApproveAuthorizeResp, error) {
	l := logic.NewApproveAuthorizeLogic(ctx, s.svcCtx)
	return l.ApproveAuthorize(in)
}

func (s *BotServer) BotToken(ctx context.Context, in *bot.BotTokenReq) (*bot.BotTokenResp, error) {
	l := logic.NewBotTokenLogic(ctx, s.svcCtx)
	return l.BotToken(in)
}
