// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: conversation.proto

package server

import (
	"context"

	"conversation/conversation"
	"conversation/internal/logic"
	"conversation/internal/svc"
)

type ConversationServer struct {
	svcCtx *svc.ServiceContext
	conversation.UnimplementedConversationServer
}

func NewConversationServer(svcCtx *svc.ServiceContext) *ConversationServer {
	return &ConversationServer{
		svcCtx: svcCtx,
	}
}

func (s *ConversationServer) GetConversations(ctx context.Context, in *conversation.GetConversationsReq) (*conversation.GetConversationsResp, error) {
	l := logic.NewGetConversationsLogic(ctx, s.svcCtx)
	return l.GetConversations(in)
}

func (s *ConversationServer) GetOrCreateSingleConv(ctx context.Context, in *conversation.GetOrCreateSingleConvReq) (*conversation.GetOrCreateSingleConvResp, error) {
	l := logic.NewGetOrCreateSingleConvLogic(ctx, s.svcCtx)
	return l.GetOrCreateSingleConv(in)
}

func (s *ConversationServer) GetConversation(ctx context.Context, in *conversation.GetConversationReq) (*conversation.GetConversationResp, error) {
	l := logic.NewGetConversationLogic(ctx, s.svcCtx)
	return l.GetConversation(in)
}

func (s *ConversationServer) DeleteConversation(ctx context.Context, in *conversation.DeleteConversationReq) (*conversation.DeleteConversationResp, error) {
	l := logic.NewDeleteConversationLogic(ctx, s.svcCtx)
	return l.DeleteConversation(in)
}

func (s *ConversationServer) SetConvMute(ctx context.Context, in *conversation.SetConvMuteReq) (*conversation.SetConvMuteResp, error) {
	l := logic.NewSetConvMuteLogic(ctx, s.svcCtx)
	return l.SetConvMute(in)
}

func (s *ConversationServer) SetConvPin(ctx context.Context, in *conversation.SetConvPinReq) (*conversation.SetConvPinResp, error) {
	l := logic.NewSetConvPinLogic(ctx, s.svcCtx)
	return l.SetConvPin(in)
}

func (s *ConversationServer) CreateGroupConv(ctx context.Context, in *conversation.CreateGroupConvReq) (*conversation.CreateGroupConvResp, error) {
	l := logic.NewCreateGroupConvLogic(ctx, s.svcCtx)
	return l.CreateGroupConv(in)
}

func (s *ConversationServer) AddConvMembers(ctx context.Context, in *conversation.AddConvMembersReq) (*conversation.AddConvMembersResp, error) {
	l := logic.NewAddConvMembersLogic(ctx, s.svcCtx)
	return l.AddConvMembers(in)
}

func (s *ConversationServer) RemoveConvMembers(ctx context.Context, in *conversation.RemoveConvMembersReq) (*conversation.RemoveConvMembersResp, error) {
	l := logic.NewRemoveConvMembersLogic(ctx, s.svcCtx)
	return l.RemoveConvMembers(in)
}

func (s *ConversationServer) GetConvMembers(ctx context.Context, in *conversation.GetConvMembersReq) (*conversation.GetConvMembersResp, error) {
	l := logic.NewGetConvMembersLogic(ctx, s.svcCtx)
	return l.GetConvMembers(in)
}

func (s *ConversationServer) ClearUnread(ctx context.Context, in *conversation.ClearUnreadReq) (*conversation.ClearUnreadResp, error) {
	l := logic.NewClearUnreadLogic(ctx, s.svcCtx)
	return l.ClearUnread(in)
}

func (s *ConversationServer) GetTotalUnread(ctx context.Context, in *conversation.GetTotalUnreadReq) (*conversation.GetTotalUnreadResp, error) {
	l := logic.NewGetTotalUnreadLogic(ctx, s.svcCtx)
	return l.GetTotalUnread(in)
}

func (s *ConversationServer) UpdateLastMessage(ctx context.Context, in *conversation.UpdateLastMessageReq) (*conversation.UpdateLastMessageResp, error) {
	l := logic.NewUpdateLastMessageLogic(ctx, s.svcCtx)
	return l.UpdateLastMessage(in)
}

func (s *ConversationServer) IncrementUnread(ctx context.Context, in *conversation.IncrementUnreadReq) (*conversation.IncrementUnreadResp, error) {
	l := logic.NewIncrementUnreadLogic(ctx, s.svcCtx)
	return l.IncrementUnread(in)
}
