// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: social.proto

package server

import (
	"context"

	"social/internal/logic/social"
	"social/internal/svc"
	"social/social"
)

type SocialServer struct {
	svcCtx *svc.ServiceContext
	social.UnimplementedSocialServer
}

func NewSocialServer(svcCtx *svc.ServiceContext) *SocialServer {
	return &SocialServer{
		svcCtx: svcCtx,
	}
}

// 好友
func (s *SocialServer) SendFriendRequest(ctx context.Context, in *social.SendFriendReq) (*social.SendFriendResp, error) {
	l := sociallogic.NewSendFriendRequestLogic(ctx, s.svcCtx)
	return l.SendFriendRequest(in)
}

func (s *SocialServer) HandleFriendRequest(ctx context.Context, in *social.HandleFriendReq) (*social.HandleFriendResp, error) {
	l := sociallogic.NewHandleFriendRequestLogic(ctx, s.svcCtx)
	return l.HandleFriendRequest(in)
}

func (s *SocialServer) GetFriendRequests(ctx context.Context, in *social.GetFriendRequestsReq) (*social.GetFriendRequestsResp, error) {
	l := sociallogic.NewGetFriendRequestsLogic(ctx, s.svcCtx)
	return l.GetFriendRequests(in)
}

func (s *SocialServer) GetFriends(ctx context.Context, in *social.GetFriendsReq) (*social.GetFriendsResp, error) {
	l := sociallogic.NewGetFriendsLogic(ctx, s.svcCtx)
	return l.GetFriends(in)
}

func (s *SocialServer) DeleteFriend(ctx context.Context, in *social.DeleteFriendReq) (*social.DeleteFriendResp, error) {
	l := sociallogic.NewDeleteFriendLogic(ctx, s.svcCtx)
	return l.DeleteFriend(in)
}

func (s *SocialServer) UpdateFriendRemark(ctx context.Context, in *social.UpdateFriendRemarkReq) (*social.UpdateFriendRemarkResp, error) {
	l := sociallogic.NewUpdateFriendRemarkLogic(ctx, s.svcCtx)
	return l.UpdateFriendRemark(in)
}

func (s *SocialServer) IsFriend(ctx context.Context, in *social.IsFriendReq) (*social.IsFriendResp, error) {
	l := sociallogic.NewIsFriendLogic(ctx, s.svcCtx)
	return l.IsFriend(in)
}

// 黑名单
func (s *SocialServer) AddBlacklist(ctx context.Context, in *social.AddBlacklistReq) (*social.AddBlacklistResp, error) {
	l := sociallogic.NewAddBlacklistLogic(ctx, s.svcCtx)
	return l.AddBlacklist(in)
}

func (s *SocialServer) RemoveBlacklist(ctx context.Context, in *social.RemoveBlacklistReq) (*social.RemoveBlacklistResp, error) {
	l := sociallogic.NewRemoveBlacklistLogic(ctx, s.svcCtx)
	return l.RemoveBlacklist(in)
}

func (s *SocialServer) IsBlacklisted(ctx context.Context, in *social.IsBlacklistedReq) (*social.IsBlacklistedResp, error) {
	l := sociallogic.NewIsBlacklistedLogic(ctx, s.svcCtx)
	return l.IsBlacklisted(in)
}

func (s *SocialServer) GetBlacklist(ctx context.Context, in *social.GetBlacklistReq) (*social.GetBlacklistResp, error) {
	l := sociallogic.NewGetBlacklistLogic(ctx, s.svcCtx)
	return l.GetBlacklist(in)
}

// 群组
func (s *SocialServer) CreateGroup(ctx context.Context, in *social.CreateGroupReq) (*social.CreateGroupResp, error) {
	l := sociallogic.NewCreateGroupLogic(ctx, s.svcCtx)
	return l.CreateGroup(in)
}

func (s *SocialServer) GetGroupInfo(ctx context.Context, in *social.GetGroupInfoReq) (*social.GetGroupInfoResp, error) {
	l := sociallogic.NewGetGroupInfoLogic(ctx, s.svcCtx)
	return l.GetGroupInfo(in)
}

func (s *SocialServer) UpdateGroup(ctx context.Context, in *social.UpdateGroupReq) (*social.UpdateGroupResp, error) {
	l := sociallogic.NewUpdateGroupLogic(ctx, s.svcCtx)
	return l.UpdateGroup(in)
}

func (s *SocialServer) JoinGroup(ctx context.Context, in *social.JoinGroupReq) (*social.JoinGroupResp, error) {
	l := sociallogic.NewJoinGroupLogic(ctx, s.svcCtx)
	return l.JoinGroup(in)
}

func (s *SocialServer) LeaveGroup(ctx context.Context, in *social.LeaveGroupReq) (*social.LeaveGroupResp, error) {
	l := sociallogic.NewLeaveGroupLogic(ctx, s.svcCtx)
	return l.LeaveGroup(in)
}

func (s *SocialServer) KickMember(ctx context.Context, in *social.KickMemberReq) (*social.KickMemberResp, error) {
	l := sociallogic.NewKickMemberLogic(ctx, s.svcCtx)
	return l.KickMember(in)
}

func (s *SocialServer) MuteMember(ctx context.Context, in *social.MuteMemberReq) (*social.MuteMemberResp, error) {
	l := sociallogic.NewMuteMemberLogic(ctx, s.svcCtx)
	return l.MuteMember(in)
}

func (s *SocialServer) TransferOwner(ctx context.Context, in *social.TransferOwnerReq) (*social.TransferOwnerResp, error) {
	l := sociallogic.NewTransferOwnerLogic(ctx, s.svcCtx)
	return l.TransferOwner(in)
}

func (s *SocialServer) GetGroupMembers(ctx context.Context, in *social.GetGroupMembersReq) (*social.GetGroupMembersResp, error) {
	l := sociallogic.NewGetGroupMembersLogic(ctx, s.svcCtx)
	return l.GetGroupMembers(in)
}

func (s *SocialServer) HandleGroupJoinRequest(ctx context.Context, in *social.HandleGroupJoinReq) (*social.HandleGroupJoinResp, error) {
	l := sociallogic.NewHandleGroupJoinRequestLogic(ctx, s.svcCtx)
	return l.HandleGroupJoinRequest(in)
}

func (s *SocialServer) GetGroupJoinRequests(ctx context.Context, in *social.GetGroupJoinRequestsReq) (*social.GetGroupJoinRequestsResp, error) {
	l := sociallogic.NewGetGroupJoinRequestsLogic(ctx, s.svcCtx)
	return l.GetGroupJoinRequests(in)
}

func (s *SocialServer) IsGroupMember(ctx context.Context, in *social.IsGroupMemberReq) (*social.IsGroupMemberResp, error) {
	l := sociallogic.NewIsGroupMemberLogic(ctx, s.svcCtx)
	return l.IsGroupMember(in)
}

func (s *SocialServer) IsGroupMuted(ctx context.Context, in *social.IsGroupMutedReq) (*social.IsGroupMutedResp, error) {
	l := sociallogic.NewIsGroupMutedLogic(ctx, s.svcCtx)
	return l.IsGroupMuted(in)
}

// 群公告
func (s *SocialServer) CreateAnnouncement(ctx context.Context, in *social.CreateAnnouncementReq) (*social.CreateAnnouncementResp, error) {
	l := sociallogic.NewCreateAnnouncementLogic(ctx, s.svcCtx)
	return l.CreateAnnouncement(in)
}

func (s *SocialServer) GetAnnouncements(ctx context.Context, in *social.GetAnnouncementsReq) (*social.GetAnnouncementsResp, error) {
	l := sociallogic.NewGetAnnouncementsLogic(ctx, s.svcCtx)
	return l.GetAnnouncements(in)
}

func (s *SocialServer) SetGroupAnnouncement(ctx context.Context, in *social.SetGroupAnnouncementReq) (*social.SetGroupAnnouncementResp, error) {
	l := sociallogic.NewSetGroupAnnouncementLogic(ctx, s.svcCtx)
	return l.SetGroupAnnouncement(in)
}

func (s *SocialServer) GetGroupAnnouncement(ctx context.Context, in *social.GetGroupAnnouncementReq) (*social.GetGroupAnnouncementResp, error) {
	l := sociallogic.NewGetGroupAnnouncementLogic(ctx, s.svcCtx)
	return l.GetGroupAnnouncement(in)
}

// 邀请进群
func (s *SocialServer) InviteToGroup(ctx context.Context, in *social.InviteToGroupReq) (*social.InviteToGroupResp, error) {
	l := sociallogic.NewInviteToGroupLogic(ctx, s.svcCtx)
	return l.InviteToGroup(in)
}

func (s *SocialServer) HandleGroupInvite(ctx context.Context, in *social.HandleGroupInviteReq) (*social.HandleGroupInviteResp, error) {
	l := sociallogic.NewHandleGroupInviteLogic(ctx, s.svcCtx)
	return l.HandleGroupInvite(in)
}

func (s *SocialServer) GetGroupInvites(ctx context.Context, in *social.GetGroupInvitesReq) (*social.GetGroupInvitesResp, error) {
	l := sociallogic.NewGetGroupInvitesLogic(ctx, s.svcCtx)
	return l.GetGroupInvites(in)
}

// 用户
func (s *SocialServer) GetUserInfo(ctx context.Context, in *social.GetUserInfoReq) (*social.GetUserInfoResp, error) {
	l := sociallogic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *SocialServer) UpdateUserInfo(ctx context.Context, in *social.UpdateUserInfoReq) (*social.UpdateUserInfoResp, error) {
	l := sociallogic.NewUpdateUserInfoLogic(ctx, s.svcCtx)
	return l.UpdateUserInfo(in)
}

func (s *SocialServer) SearchUser(ctx context.Context, in *social.SearchUserReq) (*social.SearchUserResp, error) {
	l := sociallogic.NewSearchUserLogic(ctx, s.svcCtx)
	return l.SearchUser(in)
}

func (s *SocialServer) GetUserProfile(ctx context.Context, in *social.GetUserProfileReq) (*social.GetUserProfileResp, error) {
	l := sociallogic.NewGetUserProfileLogic(ctx, s.svcCtx)
	return l.GetUserProfile(in)
}

// 用户群组
func (s *SocialServer) GetUserGroups(ctx context.Context, in *social.GetUserGroupsReq) (*social.GetUserGroupsResp, error) {
	l := sociallogic.NewGetUserGroupsLogic(ctx, s.svcCtx)
	return l.GetUserGroups(in)
}

// 在线状态
func (s *SocialServer) GetOnlineStatus(ctx context.Context, in *social.GetOnlineStatusReq) (*social.GetOnlineStatusResp, error) {
	l := sociallogic.NewGetOnlineStatusLogic(ctx, s.svcCtx)
	return l.GetOnlineStatus(in)
}

func (s *SocialServer) UpdateOnlineStatus(ctx context.Context, in *social.UpdateOnlineStatusReq) (*social.UpdateOnlineStatusResp, error) {
	l := sociallogic.NewUpdateOnlineStatusLogic(ctx, s.svcCtx)
	return l.UpdateOnlineStatus(in)
}
