log_level: INFO
service:
  host: 0.0.0.0
  http_port: 6333
  grpc_port: 6334
  enable_telemetry: false
storage:
  storage_path: /qdrant/storage
  performance:
    max_search_threads: 0
cluster:
  enabled: false