// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.35.0--rc1
// source: rag.proto

package rag

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rag_CreateKnowledgeBase_FullMethodName   = "/rag.rag/CreateKnowledgeBase"
	Rag_ListKnowledgeBases_FullMethodName    = "/rag.rag/ListKnowledgeBases"
	Rag_GetKnowledgeBase_FullMethodName      = "/rag.rag/GetKnowledgeBase"
	Rag_UpdateKnowledgeBase_FullMethodName   = "/rag.rag/UpdateKnowledgeBase"
	Rag_DeleteKnowledgeBase_FullMethodName   = "/rag.rag/DeleteKnowledgeBase"
	Rag_UploadDocument_FullMethodName        = "/rag.rag/UploadDocument"
	Rag_GetDocumentStatus_FullMethodName     = "/rag.rag/GetDocumentStatus"
	Rag_ListDocuments_FullMethodName         = "/rag.rag/ListDocuments"
	Rag_DeleteDocument_FullMethodName        = "/rag.rag/DeleteDocument"
	Rag_GetDocumentChunks_FullMethodName     = "/rag.rag/GetDocumentChunks"
	Rag_GrantBotKBAccess_FullMethodName      = "/rag.rag/GrantBotKBAccess"
	Rag_RevokeBotKBAccess_FullMethodName     = "/rag.rag/RevokeBotKBAccess"
	Rag_AuthorizeKB_FullMethodName           = "/rag.rag/AuthorizeKB"
	Rag_RevokeKBAuth_FullMethodName          = "/rag.rag/RevokeKBAuth"
	Rag_ListKBAuthorizations_FullMethodName  = "/rag.rag/ListKBAuthorizations"
	Rag_ListBotKnowledgeBases_FullMethodName = "/rag.rag/ListBotKnowledgeBases"
	Rag_SearchKnowledge_FullMethodName       = "/rag.rag/SearchKnowledge"
	Rag_CrossKBSearch_FullMethodName         = "/rag.rag/CrossKBSearch"
	Rag_AssessRetrieval_FullMethodName       = "/rag.rag/AssessRetrieval"
	Rag_AnalyzeKBHealth_FullMethodName       = "/rag.rag/AnalyzeKBHealth"
	Rag_GetSubGraph_FullMethodName           = "/rag.rag/GetSubGraph"
	Rag_TriggerExternalSync_FullMethodName   = "/rag.rag/TriggerExternalSync"
	Rag_GetSyncStatus_FullMethodName         = "/rag.rag/GetSyncStatus"
	Rag_ListExternalSyncs_FullMethodName     = "/rag.rag/ListExternalSyncs"
)

// RagClient is the client API for Rag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== Service ==========
type RagClient interface {
	// 知识库管理
	CreateKnowledgeBase(ctx context.Context, in *CreateKBReq, opts ...grpc.CallOption) (*CreateKBResp, error)
	ListKnowledgeBases(ctx context.Context, in *ListKBsReq, opts ...grpc.CallOption) (*ListKBsResp, error)
	GetKnowledgeBase(ctx context.Context, in *GetKBReq, opts ...grpc.CallOption) (*GetKBResp, error)
	UpdateKnowledgeBase(ctx context.Context, in *UpdateKBReq, opts ...grpc.CallOption) (*UpdateKBResp, error)
	DeleteKnowledgeBase(ctx context.Context, in *DeleteKBReq, opts ...grpc.CallOption) (*DeleteKBResp, error)
	// 文档管理
	UploadDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadDocReq, UploadDocResp], error)
	GetDocumentStatus(ctx context.Context, in *GetDocStatusReq, opts ...grpc.CallOption) (*GetDocStatusResp, error)
	ListDocuments(ctx context.Context, in *ListDocsReq, opts ...grpc.CallOption) (*ListDocsResp, error)
	DeleteDocument(ctx context.Context, in *DeleteDocReq, opts ...grpc.CallOption) (*DeleteDocResp, error)
	GetDocumentChunks(ctx context.Context, in *GetDocChunksReq, opts ...grpc.CallOption) (*GetDocChunksResp, error)
	// 知识库授权
	GrantBotKBAccess(ctx context.Context, in *GrantBotKBAccessReq, opts ...grpc.CallOption) (*GrantBotKBAccessResp, error)
	RevokeBotKBAccess(ctx context.Context, in *RevokeBotKBAccessReq, opts ...grpc.CallOption) (*RevokeBotKBAccessResp, error)
	AuthorizeKB(ctx context.Context, in *AuthorizeKBReq, opts ...grpc.CallOption) (*AuthorizeKBResp, error)
	RevokeKBAuth(ctx context.Context, in *RevokeKBAuthReq, opts ...grpc.CallOption) (*RevokeKBAuthResp, error)
	ListKBAuthorizations(ctx context.Context, in *ListKBAuthsReq, opts ...grpc.CallOption) (*ListKBAuthsResp, error)
	ListBotKnowledgeBases(ctx context.Context, in *ListBotKBsReq, opts ...grpc.CallOption) (*ListBotKBsResp, error)
	// RAG 检索
	SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error)
	CrossKBSearch(ctx context.Context, in *CrossKBSearchReq, opts ...grpc.CallOption) (*CrossKBSearchResp, error)
	// 元认知
	AssessRetrieval(ctx context.Context, in *AssessRetrievalReq, opts ...grpc.CallOption) (*AssessRetrievalResp, error)
	AnalyzeKBHealth(ctx context.Context, in *AnalyzeKBHealthReq, opts ...grpc.CallOption) (*AnalyzeKBHealthResp, error)
	// 图谱
	GetSubGraph(ctx context.Context, in *GetSubGraphReq, opts ...grpc.CallOption) (*GetSubGraphResp, error)
	// 外部知识库同步
	TriggerExternalSync(ctx context.Context, in *TriggerExternalSyncReq, opts ...grpc.CallOption) (*TriggerExternalSyncResp, error)
	GetSyncStatus(ctx context.Context, in *GetSyncStatusReq, opts ...grpc.CallOption) (*GetSyncStatusResp, error)
	ListExternalSyncs(ctx context.Context, in *ListExternalSyncsReq, opts ...grpc.CallOption) (*ListExternalSyncsResp, error)
}

type ragClient struct {
	cc grpc.ClientConnInterface
}

func NewRagClient(cc grpc.ClientConnInterface) RagClient {
	return &ragClient{cc}
}

func (c *ragClient) CreateKnowledgeBase(ctx context.Context, in *CreateKBReq, opts ...grpc.CallOption) (*CreateKBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKBResp)
	err := c.cc.Invoke(ctx, Rag_CreateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) ListKnowledgeBases(ctx context.Context, in *ListKBsReq, opts ...grpc.CallOption) (*ListKBsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKBsResp)
	err := c.cc.Invoke(ctx, Rag_ListKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) GetKnowledgeBase(ctx context.Context, in *GetKBReq, opts ...grpc.CallOption) (*GetKBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKBResp)
	err := c.cc.Invoke(ctx, Rag_GetKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) UpdateKnowledgeBase(ctx context.Context, in *UpdateKBReq, opts ...grpc.CallOption) (*UpdateKBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateKBResp)
	err := c.cc.Invoke(ctx, Rag_UpdateKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) DeleteKnowledgeBase(ctx context.Context, in *DeleteKBReq, opts ...grpc.CallOption) (*DeleteKBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKBResp)
	err := c.cc.Invoke(ctx, Rag_DeleteKnowledgeBase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) UploadDocument(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadDocReq, UploadDocResp], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rag_ServiceDesc.Streams[0], Rag_UploadDocument_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadDocReq, UploadDocResp]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rag_UploadDocumentClient = grpc.ClientStreamingClient[UploadDocReq, UploadDocResp]

func (c *ragClient) GetDocumentStatus(ctx context.Context, in *GetDocStatusReq, opts ...grpc.CallOption) (*GetDocStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocStatusResp)
	err := c.cc.Invoke(ctx, Rag_GetDocumentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) ListDocuments(ctx context.Context, in *ListDocsReq, opts ...grpc.CallOption) (*ListDocsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDocsResp)
	err := c.cc.Invoke(ctx, Rag_ListDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) DeleteDocument(ctx context.Context, in *DeleteDocReq, opts ...grpc.CallOption) (*DeleteDocResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDocResp)
	err := c.cc.Invoke(ctx, Rag_DeleteDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) GetDocumentChunks(ctx context.Context, in *GetDocChunksReq, opts ...grpc.CallOption) (*GetDocChunksResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDocChunksResp)
	err := c.cc.Invoke(ctx, Rag_GetDocumentChunks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) GrantBotKBAccess(ctx context.Context, in *GrantBotKBAccessReq, opts ...grpc.CallOption) (*GrantBotKBAccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrantBotKBAccessResp)
	err := c.cc.Invoke(ctx, Rag_GrantBotKBAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) RevokeBotKBAccess(ctx context.Context, in *RevokeBotKBAccessReq, opts ...grpc.CallOption) (*RevokeBotKBAccessResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeBotKBAccessResp)
	err := c.cc.Invoke(ctx, Rag_RevokeBotKBAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) AuthorizeKB(ctx context.Context, in *AuthorizeKBReq, opts ...grpc.CallOption) (*AuthorizeKBResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeKBResp)
	err := c.cc.Invoke(ctx, Rag_AuthorizeKB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) RevokeKBAuth(ctx context.Context, in *RevokeKBAuthReq, opts ...grpc.CallOption) (*RevokeKBAuthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeKBAuthResp)
	err := c.cc.Invoke(ctx, Rag_RevokeKBAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) ListKBAuthorizations(ctx context.Context, in *ListKBAuthsReq, opts ...grpc.CallOption) (*ListKBAuthsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKBAuthsResp)
	err := c.cc.Invoke(ctx, Rag_ListKBAuthorizations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) ListBotKnowledgeBases(ctx context.Context, in *ListBotKBsReq, opts ...grpc.CallOption) (*ListBotKBsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBotKBsResp)
	err := c.cc.Invoke(ctx, Rag_ListBotKnowledgeBases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) SearchKnowledge(ctx context.Context, in *SearchKnowledgeReq, opts ...grpc.CallOption) (*SearchKnowledgeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchKnowledgeResp)
	err := c.cc.Invoke(ctx, Rag_SearchKnowledge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) CrossKBSearch(ctx context.Context, in *CrossKBSearchReq, opts ...grpc.CallOption) (*CrossKBSearchResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrossKBSearchResp)
	err := c.cc.Invoke(ctx, Rag_CrossKBSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) AssessRetrieval(ctx context.Context, in *AssessRetrievalReq, opts ...grpc.CallOption) (*AssessRetrievalResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssessRetrievalResp)
	err := c.cc.Invoke(ctx, Rag_AssessRetrieval_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) AnalyzeKBHealth(ctx context.Context, in *AnalyzeKBHealthReq, opts ...grpc.CallOption) (*AnalyzeKBHealthResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeKBHealthResp)
	err := c.cc.Invoke(ctx, Rag_AnalyzeKBHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) GetSubGraph(ctx context.Context, in *GetSubGraphReq, opts ...grpc.CallOption) (*GetSubGraphResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubGraphResp)
	err := c.cc.Invoke(ctx, Rag_GetSubGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) TriggerExternalSync(ctx context.Context, in *TriggerExternalSyncReq, opts ...grpc.CallOption) (*TriggerExternalSyncResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerExternalSyncResp)
	err := c.cc.Invoke(ctx, Rag_TriggerExternalSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) GetSyncStatus(ctx context.Context, in *GetSyncStatusReq, opts ...grpc.CallOption) (*GetSyncStatusResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSyncStatusResp)
	err := c.cc.Invoke(ctx, Rag_GetSyncStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ragClient) ListExternalSyncs(ctx context.Context, in *ListExternalSyncsReq, opts ...grpc.CallOption) (*ListExternalSyncsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExternalSyncsResp)
	err := c.cc.Invoke(ctx, Rag_ListExternalSyncs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RagServer is the server API for Rag service.
// All implementations must embed UnimplementedRagServer
// for forward compatibility.
//
// ========== Service ==========
type RagServer interface {
	// 知识库管理
	CreateKnowledgeBase(context.Context, *CreateKBReq) (*CreateKBResp, error)
	ListKnowledgeBases(context.Context, *ListKBsReq) (*ListKBsResp, error)
	GetKnowledgeBase(context.Context, *GetKBReq) (*GetKBResp, error)
	UpdateKnowledgeBase(context.Context, *UpdateKBReq) (*UpdateKBResp, error)
	DeleteKnowledgeBase(context.Context, *DeleteKBReq) (*DeleteKBResp, error)
	// 文档管理
	UploadDocument(grpc.ClientStreamingServer[UploadDocReq, UploadDocResp]) error
	GetDocumentStatus(context.Context, *GetDocStatusReq) (*GetDocStatusResp, error)
	ListDocuments(context.Context, *ListDocsReq) (*ListDocsResp, error)
	DeleteDocument(context.Context, *DeleteDocReq) (*DeleteDocResp, error)
	GetDocumentChunks(context.Context, *GetDocChunksReq) (*GetDocChunksResp, error)
	// 知识库授权
	GrantBotKBAccess(context.Context, *GrantBotKBAccessReq) (*GrantBotKBAccessResp, error)
	RevokeBotKBAccess(context.Context, *RevokeBotKBAccessReq) (*RevokeBotKBAccessResp, error)
	AuthorizeKB(context.Context, *AuthorizeKBReq) (*AuthorizeKBResp, error)
	RevokeKBAuth(context.Context, *RevokeKBAuthReq) (*RevokeKBAuthResp, error)
	ListKBAuthorizations(context.Context, *ListKBAuthsReq) (*ListKBAuthsResp, error)
	ListBotKnowledgeBases(context.Context, *ListBotKBsReq) (*ListBotKBsResp, error)
	// RAG 检索
	SearchKnowledge(context.Context, *SearchKnowledgeReq) (*SearchKnowledgeResp, error)
	CrossKBSearch(context.Context, *CrossKBSearchReq) (*CrossKBSearchResp, error)
	// 元认知
	AssessRetrieval(context.Context, *AssessRetrievalReq) (*AssessRetrievalResp, error)
	AnalyzeKBHealth(context.Context, *AnalyzeKBHealthReq) (*AnalyzeKBHealthResp, error)
	// 图谱
	GetSubGraph(context.Context, *GetSubGraphReq) (*GetSubGraphResp, error)
	// 外部知识库同步
	TriggerExternalSync(context.Context, *TriggerExternalSyncReq) (*TriggerExternalSyncResp, error)
	GetSyncStatus(context.Context, *GetSyncStatusReq) (*GetSyncStatusResp, error)
	ListExternalSyncs(context.Context, *ListExternalSyncsReq) (*ListExternalSyncsResp, error)
	mustEmbedUnimplementedRagServer()
}

// UnimplementedRagServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRagServer struct{}

func (UnimplementedRagServer) CreateKnowledgeBase(context.Context, *CreateKBReq) (*CreateKBResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKnowledgeBase not implemented")
}
func (UnimplementedRagServer) ListKnowledgeBases(context.Context, *ListKBsReq) (*ListKBsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKnowledgeBases not implemented")
}
func (UnimplementedRagServer) GetKnowledgeBase(context.Context, *GetKBReq) (*GetKBResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKnowledgeBase not implemented")
}
func (UnimplementedRagServer) UpdateKnowledgeBase(context.Context, *UpdateKBReq) (*UpdateKBResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateKnowledgeBase not implemented")
}
func (UnimplementedRagServer) DeleteKnowledgeBase(context.Context, *DeleteKBReq) (*DeleteKBResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteKnowledgeBase not implemented")
}
func (UnimplementedRagServer) UploadDocument(grpc.ClientStreamingServer[UploadDocReq, UploadDocResp]) error {
	return status.Error(codes.Unimplemented, "method UploadDocument not implemented")
}
func (UnimplementedRagServer) GetDocumentStatus(context.Context, *GetDocStatusReq) (*GetDocStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentStatus not implemented")
}
func (UnimplementedRagServer) ListDocuments(context.Context, *ListDocsReq) (*ListDocsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDocuments not implemented")
}
func (UnimplementedRagServer) DeleteDocument(context.Context, *DeleteDocReq) (*DeleteDocResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDocument not implemented")
}
func (UnimplementedRagServer) GetDocumentChunks(context.Context, *GetDocChunksReq) (*GetDocChunksResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocumentChunks not implemented")
}
func (UnimplementedRagServer) GrantBotKBAccess(context.Context, *GrantBotKBAccessReq) (*GrantBotKBAccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GrantBotKBAccess not implemented")
}
func (UnimplementedRagServer) RevokeBotKBAccess(context.Context, *RevokeBotKBAccessReq) (*RevokeBotKBAccessResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeBotKBAccess not implemented")
}
func (UnimplementedRagServer) AuthorizeKB(context.Context, *AuthorizeKBReq) (*AuthorizeKBResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthorizeKB not implemented")
}
func (UnimplementedRagServer) RevokeKBAuth(context.Context, *RevokeKBAuthReq) (*RevokeKBAuthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeKBAuth not implemented")
}
func (UnimplementedRagServer) ListKBAuthorizations(context.Context, *ListKBAuthsReq) (*ListKBAuthsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKBAuthorizations not implemented")
}
func (UnimplementedRagServer) ListBotKnowledgeBases(context.Context, *ListBotKBsReq) (*ListBotKBsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBotKnowledgeBases not implemented")
}
func (UnimplementedRagServer) SearchKnowledge(context.Context, *SearchKnowledgeReq) (*SearchKnowledgeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchKnowledge not implemented")
}
func (UnimplementedRagServer) CrossKBSearch(context.Context, *CrossKBSearchReq) (*CrossKBSearchResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CrossKBSearch not implemented")
}
func (UnimplementedRagServer) AssessRetrieval(context.Context, *AssessRetrievalReq) (*AssessRetrievalResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AssessRetrieval not implemented")
}
func (UnimplementedRagServer) AnalyzeKBHealth(context.Context, *AnalyzeKBHealthReq) (*AnalyzeKBHealthResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeKBHealth not implemented")
}
func (UnimplementedRagServer) GetSubGraph(context.Context, *GetSubGraphReq) (*GetSubGraphResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubGraph not implemented")
}
func (UnimplementedRagServer) TriggerExternalSync(context.Context, *TriggerExternalSyncReq) (*TriggerExternalSyncResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerExternalSync not implemented")
}
func (UnimplementedRagServer) GetSyncStatus(context.Context, *GetSyncStatusReq) (*GetSyncStatusResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSyncStatus not implemented")
}
func (UnimplementedRagServer) ListExternalSyncs(context.Context, *ListExternalSyncsReq) (*ListExternalSyncsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListExternalSyncs not implemented")
}
func (UnimplementedRagServer) mustEmbedUnimplementedRagServer() {}
func (UnimplementedRagServer) testEmbeddedByValue()             {}

// UnsafeRagServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RagServer will
// result in compilation errors.
type UnsafeRagServer interface {
	mustEmbedUnimplementedRagServer()
}

func RegisterRagServer(s grpc.ServiceRegistrar, srv RagServer) {
	// If the following call panics, it indicates UnimplementedRagServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rag_ServiceDesc, srv)
}

func _Rag_CreateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).CreateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_CreateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).CreateKnowledgeBase(ctx, req.(*CreateKBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_ListKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKBsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).ListKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_ListKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).ListKnowledgeBases(ctx, req.(*ListKBsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_GetKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GetKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GetKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GetKnowledgeBase(ctx, req.(*GetKBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_UpdateKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateKBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).UpdateKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_UpdateKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).UpdateKnowledgeBase(ctx, req.(*UpdateKBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_DeleteKnowledgeBase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).DeleteKnowledgeBase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_DeleteKnowledgeBase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).DeleteKnowledgeBase(ctx, req.(*DeleteKBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_UploadDocument_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RagServer).UploadDocument(&grpc.GenericServerStream[UploadDocReq, UploadDocResp]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rag_UploadDocumentServer = grpc.ClientStreamingServer[UploadDocReq, UploadDocResp]

func _Rag_GetDocumentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GetDocumentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GetDocumentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GetDocumentStatus(ctx, req.(*GetDocStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_ListDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDocsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).ListDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_ListDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).ListDocuments(ctx, req.(*ListDocsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_DeleteDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDocReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).DeleteDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_DeleteDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).DeleteDocument(ctx, req.(*DeleteDocReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_GetDocumentChunks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocChunksReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GetDocumentChunks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GetDocumentChunks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GetDocumentChunks(ctx, req.(*GetDocChunksReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_GrantBotKBAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrantBotKBAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GrantBotKBAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GrantBotKBAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GrantBotKBAccess(ctx, req.(*GrantBotKBAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_RevokeBotKBAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeBotKBAccessReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).RevokeBotKBAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_RevokeBotKBAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).RevokeBotKBAccess(ctx, req.(*RevokeBotKBAccessReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_AuthorizeKB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeKBReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).AuthorizeKB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_AuthorizeKB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).AuthorizeKB(ctx, req.(*AuthorizeKBReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_RevokeKBAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeKBAuthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).RevokeKBAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_RevokeKBAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).RevokeKBAuth(ctx, req.(*RevokeKBAuthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_ListKBAuthorizations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKBAuthsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).ListKBAuthorizations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_ListKBAuthorizations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).ListKBAuthorizations(ctx, req.(*ListKBAuthsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_ListBotKnowledgeBases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBotKBsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).ListBotKnowledgeBases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_ListBotKnowledgeBases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).ListBotKnowledgeBases(ctx, req.(*ListBotKBsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_SearchKnowledge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchKnowledgeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).SearchKnowledge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_SearchKnowledge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).SearchKnowledge(ctx, req.(*SearchKnowledgeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_CrossKBSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrossKBSearchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).CrossKBSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_CrossKBSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).CrossKBSearch(ctx, req.(*CrossKBSearchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_AssessRetrieval_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssessRetrievalReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).AssessRetrieval(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_AssessRetrieval_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).AssessRetrieval(ctx, req.(*AssessRetrievalReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_AnalyzeKBHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeKBHealthReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).AnalyzeKBHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_AnalyzeKBHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).AnalyzeKBHealth(ctx, req.(*AnalyzeKBHealthReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_GetSubGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubGraphReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GetSubGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GetSubGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GetSubGraph(ctx, req.(*GetSubGraphReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_TriggerExternalSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerExternalSyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).TriggerExternalSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_TriggerExternalSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).TriggerExternalSync(ctx, req.(*TriggerExternalSyncReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_GetSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSyncStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).GetSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_GetSyncStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).GetSyncStatus(ctx, req.(*GetSyncStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Rag_ListExternalSyncs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExternalSyncsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RagServer).ListExternalSyncs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Rag_ListExternalSyncs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RagServer).ListExternalSyncs(ctx, req.(*ListExternalSyncsReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Rag_ServiceDesc is the grpc.ServiceDesc for Rag service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rag_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rag.rag",
	HandlerType: (*RagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateKnowledgeBase",
			Handler:    _Rag_CreateKnowledgeBase_Handler,
		},
		{
			MethodName: "ListKnowledgeBases",
			Handler:    _Rag_ListKnowledgeBases_Handler,
		},
		{
			MethodName: "GetKnowledgeBase",
			Handler:    _Rag_GetKnowledgeBase_Handler,
		},
		{
			MethodName: "UpdateKnowledgeBase",
			Handler:    _Rag_UpdateKnowledgeBase_Handler,
		},
		{
			MethodName: "DeleteKnowledgeBase",
			Handler:    _Rag_DeleteKnowledgeBase_Handler,
		},
		{
			MethodName: "GetDocumentStatus",
			Handler:    _Rag_GetDocumentStatus_Handler,
		},
		{
			MethodName: "ListDocuments",
			Handler:    _Rag_ListDocuments_Handler,
		},
		{
			MethodName: "DeleteDocument",
			Handler:    _Rag_DeleteDocument_Handler,
		},
		{
			MethodName: "GetDocumentChunks",
			Handler:    _Rag_GetDocumentChunks_Handler,
		},
		{
			MethodName: "GrantBotKBAccess",
			Handler:    _Rag_GrantBotKBAccess_Handler,
		},
		{
			MethodName: "RevokeBotKBAccess",
			Handler:    _Rag_RevokeBotKBAccess_Handler,
		},
		{
			MethodName: "AuthorizeKB",
			Handler:    _Rag_AuthorizeKB_Handler,
		},
		{
			MethodName: "RevokeKBAuth",
			Handler:    _Rag_RevokeKBAuth_Handler,
		},
		{
			MethodName: "ListKBAuthorizations",
			Handler:    _Rag_ListKBAuthorizations_Handler,
		},
		{
			MethodName: "ListBotKnowledgeBases",
			Handler:    _Rag_ListBotKnowledgeBases_Handler,
		},
		{
			MethodName: "SearchKnowledge",
			Handler:    _Rag_SearchKnowledge_Handler,
		},
		{
			MethodName: "CrossKBSearch",
			Handler:    _Rag_CrossKBSearch_Handler,
		},
		{
			MethodName: "AssessRetrieval",
			Handler:    _Rag_AssessRetrieval_Handler,
		},
		{
			MethodName: "AnalyzeKBHealth",
			Handler:    _Rag_AnalyzeKBHealth_Handler,
		},
		{
			MethodName: "GetSubGraph",
			Handler:    _Rag_GetSubGraph_Handler,
		},
		{
			MethodName: "TriggerExternalSync",
			Handler:    _Rag_TriggerExternalSync_Handler,
		},
		{
			MethodName: "GetSyncStatus",
			Handler:    _Rag_GetSyncStatus_Handler,
		},
		{
			MethodName: "ListExternalSyncs",
			Handler:    _Rag_ListExternalSyncs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadDocument",
			Handler:       _Rag_UploadDocument_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "rag.proto",
}
