// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: oss.proto

package logic

import (
	"context"

	"oss/internal/svc"
	"oss/oss"

	"github.com/zeromicro/go-zero/core/logx"
)

type AbortMultipartUploadLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	logx.Logger
}

func NewAbortMultipartUploadLogic(ctx context.Context, svcCtx *svc.ServiceContext) *AbortMultipartUploadLogic {
	return &AbortMultipartUploadLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: logx.WithContext(ctx),
	}
}

// 取消上传
func (l *AbortMultipartUploadLogic) AbortMultipartUpload(in *oss.AbortUploadReq) (*oss.AbortUploadResp, error) {
	if in.UploadId == "" || in.ObjectKey == "" {
		return &oss.AbortUploadResp{}, nil
	}

	// 调用 RustFS 取消分片上传
	err := l.svcCtx.Storage.AbortMultipartUpload(l.ctx, in.UploadId, in.ObjectKey)
	if err != nil {
		l.Errorf("AbortMultipartUpload error: %v", err)
		// 即使底层报错也继续清理本地缓存
	}

	// 清理 Redis 缓存和 hasher
	l.svcCtx.Hashers.Delete(in.UploadId)
	go func() {
		_ = l.svcCtx.RedisDao.DelUploadMeta(context.Background(), in.UploadId)
		_ = l.svcCtx.RedisDao.DelParts(context.Background(), in.UploadId)
		_ = l.svcCtx.RedisDao.DelURLCache(context.Background(), in.ObjectKey)
	}()

	return &oss.AbortUploadResp{}, nil
}