// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: oss.proto

package logic

import (
	"context"

	"oss/internal/svc"
	"oss/oss"

	"github.com/zeromicro/go-zero/core/logx"
)

type DeleteFileLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	logx.Logger
}

func NewDeleteFileLogic(ctx context.Context, svcCtx *svc.ServiceContext) *DeleteFileLogic {
	return &DeleteFileLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: logx.WithContext(ctx),
	}
}

// DeleteFile 删除文件
// 支持通过 index_id（文件索引ID）或 object_key（内容哈希路径）删除
// 注意：删除文件索引只删除该 index 条目；只有所有指向该内容的 index 都被删除后，才会删除实际存储对象
func (l *DeleteFileLogic) DeleteFile(in *oss.DeleteFileReq) (*oss.DeleteFileResp, error) {
	objectKey := in.ObjectKey
	var indexID string

	// 如果提供了 index_id，从索引中解析 objectKey
	if in.IndexId != "" {
		idx, err := l.svcCtx.RedisDao.GetFileIndex(l.ctx, in.IndexId)
		if err != nil {
			l.Errorf("GetFileIndex for index_id=%s error: %v", in.IndexId, err)
			return &oss.DeleteFileResp{Deleted: false}, err
		}
		objectKey = idx.ObjectKey
		indexID = in.IndexId
	}

	if objectKey == "" {
		return &oss.DeleteFileResp{Deleted: false}, nil
	}

	// 如果指定了 index_id，只删除该索引；否则直接删除存储对象
	if indexID != "" {
		if err := l.svcCtx.RedisDao.DelFileIndex(l.ctx, indexID); err != nil {
			l.Errorf("DelFileIndex error: %v", err)
			return &oss.DeleteFileResp{Deleted: false}, err
		}

		// 检查是否还有其他 index 指向同一内容
		referrers, err := l.svcCtx.RedisDao.GetIndexesByHash(l.ctx, objectKey)
		if err != nil || len(referrers) == 0 {
			// 没有其他引用，删除实际存储对象
			go func() {
				_ = l.svcCtx.Storage.RemoveObject(context.Background(), objectKey)
				_ = l.svcCtx.RedisDao.DelURLCache(context.Background(), objectKey)
			}()
		}
		return &oss.DeleteFileResp{Deleted: true}, nil
	}

	// 直接通过 objectKey 删除（遗留方式，清除所有关联 index）
	referrers, _ := l.svcCtx.RedisDao.GetIndexesByHash(l.ctx, objectKey)
	for _, refID := range referrers {
		_ = l.svcCtx.RedisDao.DelFileIndex(l.ctx, refID)
	}

	err := l.svcCtx.Storage.RemoveObject(l.ctx, objectKey)
	if err != nil {
		l.Errorf("DeleteFile RemoveObject error: %v", err)
		return &oss.DeleteFileResp{Deleted: false}, err
	}

	// 清理缓存
	go func() {
		_ = l.svcCtx.RedisDao.DelURLCache(context.Background(), objectKey)
	}()

	return &oss.DeleteFileResp{Deleted: true}, nil
}