// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: oss.proto

package logic

import (
	"context"
	"path"
	"time"

	"oss/internal/dao"
	"oss/internal/svc"
	"oss/oss"

	"lukechampine.com/blake3"

	"github.com/google/uuid"
	"github.com/zeromicro/go-zero/core/logx"
)

type InitiateMultipartUploadLogic struct {
	ctx    context.Context
	svcCtx *svc.ServiceContext
	logx.Logger
}

func NewInitiateMultipartUploadLogic(ctx context.Context, svcCtx *svc.ServiceContext) *InitiateMultipartUploadLogic {
	return &InitiateMultipartUploadLogic{
		ctx:    ctx,
		svcCtx: svcCtx,
		Logger: logx.WithContext(ctx),
	}
}

// 初始化分片上传，返回 UploadId 并创建 BLAKE3 hasher
func (l *InitiateMultipartUploadLogic) InitiateMultipartUpload(in *oss.InitiateUploadReq) (*oss.InitiateUploadResp, error) {
	if in.FileName == "" {
		return nil, nil
	}

	uploadID := uuid.New().String()
	// 分片上传临时使用 UUID 作为对象路径，完成后迁移到哈希路径
	objectKey := path.Join("uploads", "chunked", uploadID)

	// 调用 MinIO 初始化分片上传
	realUploadID, err := l.svcCtx.Storage.InitiateMultipartUpload(l.ctx, objectKey)
	if err != nil {
		l.Errorf("InitiateMultipartUpload error: %v", err)
		return nil, err
	}

	// 创建 BLAKE3 流式 hasher，用于在分片上传过程中累积计算哈希
	hasher := blake3.New(32, nil)
	l.svcCtx.Hashers.Store(realUploadID, hasher)

	// 缓存上传元数据（临时 objectKey，完成后会迁移到哈希 key）
	meta := &dao.UploadMeta{
		UploadID:    realUploadID,
		Bucket:      l.svcCtx.Storage.GetBucket(),
		ObjectKey:   objectKey,
		FileName:    in.FileName,
		ContentType: in.ContentType,
		TotalSize:   in.TotalSize,
		CreatedAt:   time.Now().Unix(),
	}
	if err := l.svcCtx.RedisDao.SetUploadMeta(l.ctx, meta); err != nil {
		l.Errorf("SetUploadMeta error: %v", err)
	}

	return &oss.InitiateUploadResp{
		UploadId:  realUploadID,
		Bucket:    meta.Bucket,
		ObjectKey: objectKey,
	}, nil
}