{
 "title": "Go-Zero",
 "description": "专为go-zero框架设计的监控面板",
 "tags": [ "go-zero" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "Service",
    "label": "Service",
    "query": {
     "query": "label_values(kube_service_info{namespace=~\"$Namespace\"},service)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=~\"$Namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Rpc Client Code Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_code_total{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m])) by (app, code)",
     "legendFormat": "{{app}} | {{code}}"
    }
   ]
  },
  {
   "title": "Rpc Server Code Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_code_total{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m])) by (app, code)",
     "legendFormat": "{{app}} | {{code}}"
    }
   ]
  },
  {
   "title": "Rpc Client Duration Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_client_requests_duration_ms_sum{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m]) / rate(rpc_client_requests_duration_ms_count{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m])) by (app, method)",
     "legendFormat": "{{app}} | {{method}}"
    }
   ]
  },
  {
   "title": "Rpc Server Duration Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(rpc_server_requests_duration_ms_sum{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m]) / rate(rpc_server_requests_duration_ms_count{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m])) by (app, method)",
     "legendFormat": "{{app}} | {{method}}"
    }
   ]
  },
  {
   "title": "Http Server Code Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_code_total{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m])) by (app, code, method, path)",
     "legendFormat": "{{app}} | {{code}} | {{method}} | {{path}}"
    }
   ]
  },
  {
   "title": "Http Server Duration Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_duration_ms_sum{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m]) / rate(http_server_requests_duration_ms_count{namespace=~\"$Namespace\",app=~\"$Service\",pod=~\"$Pod\"}[1m])) by (app, method, path)",
     "legendFormat": "{{app}} | {{method}} | {{path}}"
    }
   ]
  }
 ]
}