// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0--rc1
// source: bot.proto

package bot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bot_CreateBot_FullMethodName            = "/bot.bot/CreateBot"
	Bot_ListMyBots_FullMethodName           = "/bot.bot/ListMyBots"
	Bot_ListCommunityBots_FullMethodName    = "/bot.bot/ListCommunityBots"
	Bot_GetBot_FullMethodName               = "/bot.bot/GetBot"
	Bot_UpdateBot_FullMethodName            = "/bot.bot/UpdateBot"
	Bot_DeleteBot_FullMethodName            = "/bot.bot/DeleteBot"
	Bot_GetBotInstallations_FullMethodName  = "/bot.bot/GetBotInstallations"
	Bot_GetBotRateLimit_FullMethodName      = "/bot.bot/GetBotRateLimit"
	Bot_UpdateBotRateLimit_FullMethodName   = "/bot.bot/UpdateBotRateLimit"
	Bot_RegenerateCredential_FullMethodName = "/bot.bot/RegenerateCredential"
	Bot_RotateWebhookSecret_FullMethodName  = "/bot.bot/RotateWebhookSecret"
	Bot_GetEventDeliveries_FullMethodName   = "/bot.bot/GetEventDeliveries"
	Bot_RetryEventDelivery_FullMethodName   = "/bot.bot/RetryEventDelivery"
	Bot_GetConvBots_FullMethodName          = "/bot.bot/GetConvBots"
	Bot_InstallBot_FullMethodName           = "/bot.bot/InstallBot"
	Bot_UninstallBot_FullMethodName         = "/bot.bot/UninstallBot"
	Bot_BotGetConv_FullMethodName           = "/bot.bot/BotGetConv"
	Bot_BotGetConvMembers_FullMethodName    = "/bot.bot/BotGetConvMembers"
	Bot_BotGetMsg_FullMethodName            = "/bot.bot/BotGetMsg"
	Bot_BotSendMsg_FullMethodName           = "/bot.bot/BotSendMsg"
	Bot_BotRecallMsg_FullMethodName         = "/bot.bot/BotRecallMsg"
	Bot_BotReplyMsg_FullMethodName          = "/bot.bot/BotReplyMsg"
	Bot_BotUploadFile_FullMethodName        = "/bot.bot/BotUploadFile"
	Bot_BotGetUser_FullMethodName           = "/bot.bot/BotGetUser"
	Bot_Authorize_FullMethodName            = "/bot.bot/Authorize"
	Bot_ApproveAuthorize_FullMethodName     = "/bot.bot/ApproveAuthorize"
	Bot_BotToken_FullMethodName             = "/bot.bot/BotToken"
)

// BotClient is the client API for Bot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========== Service ==========
type BotClient interface {
	// Developer APIs (user-facing)
	CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*CreateBotResp, error)
	ListMyBots(ctx context.Context, in *ListMyBotsReq, opts ...grpc.CallOption) (*ListMyBotsResp, error)
	ListCommunityBots(ctx context.Context, in *ListCommunityBotsReq, opts ...grpc.CallOption) (*ListCommunityBotsResp, error)
	GetBot(ctx context.Context, in *GetBotReq, opts ...grpc.CallOption) (*GetBotResp, error)
	UpdateBot(ctx context.Context, in *UpdateBotReq, opts ...grpc.CallOption) (*UpdateBotResp, error)
	DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*DeleteBotResp, error)
	GetBotInstallations(ctx context.Context, in *GetBotInstallationsReq, opts ...grpc.CallOption) (*GetBotInstallationsResp, error)
	GetBotRateLimit(ctx context.Context, in *GetBotRateLimitReq, opts ...grpc.CallOption) (*GetBotRateLimitResp, error)
	UpdateBotRateLimit(ctx context.Context, in *UpdateBotRateLimitReq, opts ...grpc.CallOption) (*UpdateBotRateLimitResp, error)
	RegenerateCredential(ctx context.Context, in *RegenerateCredentialReq, opts ...grpc.CallOption) (*RegenerateCredentialResp, error)
	RotateWebhookSecret(ctx context.Context, in *RotateWebhookSecretReq, opts ...grpc.CallOption) (*RotateWebhookSecretResp, error)
	GetEventDeliveries(ctx context.Context, in *GetEventDeliveriesReq, opts ...grpc.CallOption) (*GetEventDeliveriesResp, error)
	RetryEventDelivery(ctx context.Context, in *RetryEventDeliveryReq, opts ...grpc.CallOption) (*RetryEventDeliveryResp, error)
	// Installation APIs
	GetConvBots(ctx context.Context, in *GetConvBotsReq, opts ...grpc.CallOption) (*GetConvBotsResp, error)
	InstallBot(ctx context.Context, in *InstallBotReq, opts ...grpc.CallOption) (*InstallBotResp, error)
	UninstallBot(ctx context.Context, in *UninstallBotReq, opts ...grpc.CallOption) (*UninstallBotResp, error)
	// Bot APIs (bot 调用 Katheryne)
	BotGetConv(ctx context.Context, in *BotGetConvReq, opts ...grpc.CallOption) (*BotGetConvResp, error)
	BotGetConvMembers(ctx context.Context, in *BotGetConvMembersReq, opts ...grpc.CallOption) (*BotGetConvMembersResp, error)
	BotGetMsg(ctx context.Context, in *BotGetMsgReq, opts ...grpc.CallOption) (*BotGetMsgResp, error)
	BotSendMsg(ctx context.Context, in *BotSendMsgReq, opts ...grpc.CallOption) (*BotSendMsgResp, error)
	BotRecallMsg(ctx context.Context, in *BotRecallMsgReq, opts ...grpc.CallOption) (*BotRecallMsgResp, error)
	BotReplyMsg(ctx context.Context, in *BotReplyMsgReq, opts ...grpc.CallOption) (*BotReplyMsgResp, error)
	BotUploadFile(ctx context.Context, in *BotUploadFileReq, opts ...grpc.CallOption) (*BotUploadFileResp, error)
	BotGetUser(ctx context.Context, in *BotGetUserReq, opts ...grpc.CallOption) (*BotGetUserResp, error)
	// OAuth2 APIs
	Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeResp, error)
	ApproveAuthorize(ctx context.Context, in *ApproveAuthorizeReq, opts ...grpc.CallOption) (*ApproveAuthorizeResp, error)
	BotToken(ctx context.Context, in *BotTokenReq, opts ...grpc.CallOption) (*BotTokenResp, error)
}

type botClient struct {
	cc grpc.ClientConnInterface
}

func NewBotClient(cc grpc.ClientConnInterface) BotClient {
	return &botClient{cc}
}

func (c *botClient) CreateBot(ctx context.Context, in *CreateBotReq, opts ...grpc.CallOption) (*CreateBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBotResp)
	err := c.cc.Invoke(ctx, Bot_CreateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) ListMyBots(ctx context.Context, in *ListMyBotsReq, opts ...grpc.CallOption) (*ListMyBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyBotsResp)
	err := c.cc.Invoke(ctx, Bot_ListMyBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) ListCommunityBots(ctx context.Context, in *ListCommunityBotsReq, opts ...grpc.CallOption) (*ListCommunityBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCommunityBotsResp)
	err := c.cc.Invoke(ctx, Bot_ListCommunityBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetBot(ctx context.Context, in *GetBotReq, opts ...grpc.CallOption) (*GetBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBotResp)
	err := c.cc.Invoke(ctx, Bot_GetBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) UpdateBot(ctx context.Context, in *UpdateBotReq, opts ...grpc.CallOption) (*UpdateBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBotResp)
	err := c.cc.Invoke(ctx, Bot_UpdateBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) DeleteBot(ctx context.Context, in *DeleteBotReq, opts ...grpc.CallOption) (*DeleteBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBotResp)
	err := c.cc.Invoke(ctx, Bot_DeleteBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetBotInstallations(ctx context.Context, in *GetBotInstallationsReq, opts ...grpc.CallOption) (*GetBotInstallationsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBotInstallationsResp)
	err := c.cc.Invoke(ctx, Bot_GetBotInstallations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetBotRateLimit(ctx context.Context, in *GetBotRateLimitReq, opts ...grpc.CallOption) (*GetBotRateLimitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBotRateLimitResp)
	err := c.cc.Invoke(ctx, Bot_GetBotRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) UpdateBotRateLimit(ctx context.Context, in *UpdateBotRateLimitReq, opts ...grpc.CallOption) (*UpdateBotRateLimitResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBotRateLimitResp)
	err := c.cc.Invoke(ctx, Bot_UpdateBotRateLimit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) RegenerateCredential(ctx context.Context, in *RegenerateCredentialReq, opts ...grpc.CallOption) (*RegenerateCredentialResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateCredentialResp)
	err := c.cc.Invoke(ctx, Bot_RegenerateCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) RotateWebhookSecret(ctx context.Context, in *RotateWebhookSecretReq, opts ...grpc.CallOption) (*RotateWebhookSecretResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateWebhookSecretResp)
	err := c.cc.Invoke(ctx, Bot_RotateWebhookSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetEventDeliveries(ctx context.Context, in *GetEventDeliveriesReq, opts ...grpc.CallOption) (*GetEventDeliveriesResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEventDeliveriesResp)
	err := c.cc.Invoke(ctx, Bot_GetEventDeliveries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) RetryEventDelivery(ctx context.Context, in *RetryEventDeliveryReq, opts ...grpc.CallOption) (*RetryEventDeliveryResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryEventDeliveryResp)
	err := c.cc.Invoke(ctx, Bot_RetryEventDelivery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) GetConvBots(ctx context.Context, in *GetConvBotsReq, opts ...grpc.CallOption) (*GetConvBotsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConvBotsResp)
	err := c.cc.Invoke(ctx, Bot_GetConvBots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) InstallBot(ctx context.Context, in *InstallBotReq, opts ...grpc.CallOption) (*InstallBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallBotResp)
	err := c.cc.Invoke(ctx, Bot_InstallBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) UninstallBot(ctx context.Context, in *UninstallBotReq, opts ...grpc.CallOption) (*UninstallBotResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UninstallBotResp)
	err := c.cc.Invoke(ctx, Bot_UninstallBot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotGetConv(ctx context.Context, in *BotGetConvReq, opts ...grpc.CallOption) (*BotGetConvResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotGetConvResp)
	err := c.cc.Invoke(ctx, Bot_BotGetConv_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotGetConvMembers(ctx context.Context, in *BotGetConvMembersReq, opts ...grpc.CallOption) (*BotGetConvMembersResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotGetConvMembersResp)
	err := c.cc.Invoke(ctx, Bot_BotGetConvMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotGetMsg(ctx context.Context, in *BotGetMsgReq, opts ...grpc.CallOption) (*BotGetMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotGetMsgResp)
	err := c.cc.Invoke(ctx, Bot_BotGetMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotSendMsg(ctx context.Context, in *BotSendMsgReq, opts ...grpc.CallOption) (*BotSendMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotSendMsgResp)
	err := c.cc.Invoke(ctx, Bot_BotSendMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotRecallMsg(ctx context.Context, in *BotRecallMsgReq, opts ...grpc.CallOption) (*BotRecallMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotRecallMsgResp)
	err := c.cc.Invoke(ctx, Bot_BotRecallMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotReplyMsg(ctx context.Context, in *BotReplyMsgReq, opts ...grpc.CallOption) (*BotReplyMsgResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotReplyMsgResp)
	err := c.cc.Invoke(ctx, Bot_BotReplyMsg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotUploadFile(ctx context.Context, in *BotUploadFileReq, opts ...grpc.CallOption) (*BotUploadFileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotUploadFileResp)
	err := c.cc.Invoke(ctx, Bot_BotUploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotGetUser(ctx context.Context, in *BotGetUserReq, opts ...grpc.CallOption) (*BotGetUserResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotGetUserResp)
	err := c.cc.Invoke(ctx, Bot_BotGetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) Authorize(ctx context.Context, in *AuthorizeReq, opts ...grpc.CallOption) (*AuthorizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizeResp)
	err := c.cc.Invoke(ctx, Bot_Authorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) ApproveAuthorize(ctx context.Context, in *ApproveAuthorizeReq, opts ...grpc.CallOption) (*ApproveAuthorizeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApproveAuthorizeResp)
	err := c.cc.Invoke(ctx, Bot_ApproveAuthorize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *botClient) BotToken(ctx context.Context, in *BotTokenReq, opts ...grpc.CallOption) (*BotTokenResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BotTokenResp)
	err := c.cc.Invoke(ctx, Bot_BotToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BotServer is the server API for Bot service.
// All implementations must embed UnimplementedBotServer
// for forward compatibility.
//
// ========== Service ==========
type BotServer interface {
	// Developer APIs (user-facing)
	CreateBot(context.Context, *CreateBotReq) (*CreateBotResp, error)
	ListMyBots(context.Context, *ListMyBotsReq) (*ListMyBotsResp, error)
	ListCommunityBots(context.Context, *ListCommunityBotsReq) (*ListCommunityBotsResp, error)
	GetBot(context.Context, *GetBotReq) (*GetBotResp, error)
	UpdateBot(context.Context, *UpdateBotReq) (*UpdateBotResp, error)
	DeleteBot(context.Context, *DeleteBotReq) (*DeleteBotResp, error)
	GetBotInstallations(context.Context, *GetBotInstallationsReq) (*GetBotInstallationsResp, error)
	GetBotRateLimit(context.Context, *GetBotRateLimitReq) (*GetBotRateLimitResp, error)
	UpdateBotRateLimit(context.Context, *UpdateBotRateLimitReq) (*UpdateBotRateLimitResp, error)
	RegenerateCredential(context.Context, *RegenerateCredentialReq) (*RegenerateCredentialResp, error)
	RotateWebhookSecret(context.Context, *RotateWebhookSecretReq) (*RotateWebhookSecretResp, error)
	GetEventDeliveries(context.Context, *GetEventDeliveriesReq) (*GetEventDeliveriesResp, error)
	RetryEventDelivery(context.Context, *RetryEventDeliveryReq) (*RetryEventDeliveryResp, error)
	// Installation APIs
	GetConvBots(context.Context, *GetConvBotsReq) (*GetConvBotsResp, error)
	InstallBot(context.Context, *InstallBotReq) (*InstallBotResp, error)
	UninstallBot(context.Context, *UninstallBotReq) (*UninstallBotResp, error)
	// Bot APIs (bot 调用 Katheryne)
	BotGetConv(context.Context, *BotGetConvReq) (*BotGetConvResp, error)
	BotGetConvMembers(context.Context, *BotGetConvMembersReq) (*BotGetConvMembersResp, error)
	BotGetMsg(context.Context, *BotGetMsgReq) (*BotGetMsgResp, error)
	BotSendMsg(context.Context, *BotSendMsgReq) (*BotSendMsgResp, error)
	BotRecallMsg(context.Context, *BotRecallMsgReq) (*BotRecallMsgResp, error)
	BotReplyMsg(context.Context, *BotReplyMsgReq) (*BotReplyMsgResp, error)
	BotUploadFile(context.Context, *BotUploadFileReq) (*BotUploadFileResp, error)
	BotGetUser(context.Context, *BotGetUserReq) (*BotGetUserResp, error)
	// OAuth2 APIs
	Authorize(context.Context, *AuthorizeReq) (*AuthorizeResp, error)
	ApproveAuthorize(context.Context, *ApproveAuthorizeReq) (*ApproveAuthorizeResp, error)
	BotToken(context.Context, *BotTokenReq) (*BotTokenResp, error)
	mustEmbedUnimplementedBotServer()
}

// UnimplementedBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBotServer struct{}

func (UnimplementedBotServer) CreateBot(context.Context, *CreateBotReq) (*CreateBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBot not implemented")
}
func (UnimplementedBotServer) ListMyBots(context.Context, *ListMyBotsReq) (*ListMyBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMyBots not implemented")
}
func (UnimplementedBotServer) ListCommunityBots(context.Context, *ListCommunityBotsReq) (*ListCommunityBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCommunityBots not implemented")
}
func (UnimplementedBotServer) GetBot(context.Context, *GetBotReq) (*GetBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBot not implemented")
}
func (UnimplementedBotServer) UpdateBot(context.Context, *UpdateBotReq) (*UpdateBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBot not implemented")
}
func (UnimplementedBotServer) DeleteBot(context.Context, *DeleteBotReq) (*DeleteBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBot not implemented")
}
func (UnimplementedBotServer) GetBotInstallations(context.Context, *GetBotInstallationsReq) (*GetBotInstallationsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotInstallations not implemented")
}
func (UnimplementedBotServer) GetBotRateLimit(context.Context, *GetBotRateLimitReq) (*GetBotRateLimitResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBotRateLimit not implemented")
}
func (UnimplementedBotServer) UpdateBotRateLimit(context.Context, *UpdateBotRateLimitReq) (*UpdateBotRateLimitResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBotRateLimit not implemented")
}
func (UnimplementedBotServer) RegenerateCredential(context.Context, *RegenerateCredentialReq) (*RegenerateCredentialResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RegenerateCredential not implemented")
}
func (UnimplementedBotServer) RotateWebhookSecret(context.Context, *RotateWebhookSecretReq) (*RotateWebhookSecretResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateWebhookSecret not implemented")
}
func (UnimplementedBotServer) GetEventDeliveries(context.Context, *GetEventDeliveriesReq) (*GetEventDeliveriesResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEventDeliveries not implemented")
}
func (UnimplementedBotServer) RetryEventDelivery(context.Context, *RetryEventDeliveryReq) (*RetryEventDeliveryResp, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryEventDelivery not implemented")
}
func (UnimplementedBotServer) GetConvBots(context.Context, *GetConvBotsReq) (*GetConvBotsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConvBots not implemented")
}
func (UnimplementedBotServer) InstallBot(context.Context, *InstallBotReq) (*InstallBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InstallBot not implemented")
}
func (UnimplementedBotServer) UninstallBot(context.Context, *UninstallBotReq) (*UninstallBotResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UninstallBot not implemented")
}
func (UnimplementedBotServer) BotGetConv(context.Context, *BotGetConvReq) (*BotGetConvResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotGetConv not implemented")
}
func (UnimplementedBotServer) BotGetConvMembers(context.Context, *BotGetConvMembersReq) (*BotGetConvMembersResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotGetConvMembers not implemented")
}
func (UnimplementedBotServer) BotGetMsg(context.Context, *BotGetMsgReq) (*BotGetMsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotGetMsg not implemented")
}
func (UnimplementedBotServer) BotSendMsg(context.Context, *BotSendMsgReq) (*BotSendMsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotSendMsg not implemented")
}
func (UnimplementedBotServer) BotRecallMsg(context.Context, *BotRecallMsgReq) (*BotRecallMsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotRecallMsg not implemented")
}
func (UnimplementedBotServer) BotReplyMsg(context.Context, *BotReplyMsgReq) (*BotReplyMsgResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotReplyMsg not implemented")
}
func (UnimplementedBotServer) BotUploadFile(context.Context, *BotUploadFileReq) (*BotUploadFileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotUploadFile not implemented")
}
func (UnimplementedBotServer) BotGetUser(context.Context, *BotGetUserReq) (*BotGetUserResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotGetUser not implemented")
}
func (UnimplementedBotServer) Authorize(context.Context, *AuthorizeReq) (*AuthorizeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Authorize not implemented")
}
func (UnimplementedBotServer) ApproveAuthorize(context.Context, *ApproveAuthorizeReq) (*ApproveAuthorizeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveAuthorize not implemented")
}
func (UnimplementedBotServer) BotToken(context.Context, *BotTokenReq) (*BotTokenResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BotToken not implemented")
}
func (UnimplementedBotServer) mustEmbedUnimplementedBotServer() {}
func (UnimplementedBotServer) testEmbeddedByValue()             {}

// UnsafeBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BotServer will
// result in compilation errors.
type UnsafeBotServer interface {
	mustEmbedUnimplementedBotServer()
}

func RegisterBotServer(s grpc.ServiceRegistrar, srv BotServer) {
	// If the following call panics, it indicates UnimplementedBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bot_ServiceDesc, srv)
}

func _Bot_CreateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).CreateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_CreateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).CreateBot(ctx, req.(*CreateBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_ListMyBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).ListMyBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_ListMyBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).ListMyBots(ctx, req.(*ListMyBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_ListCommunityBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCommunityBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).ListCommunityBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_ListCommunityBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).ListCommunityBots(ctx, req.(*ListCommunityBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_GetBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetBot(ctx, req.(*GetBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_UpdateBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).UpdateBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_UpdateBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).UpdateBot(ctx, req.(*UpdateBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_DeleteBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).DeleteBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_DeleteBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).DeleteBot(ctx, req.(*DeleteBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetBotInstallations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotInstallationsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetBotInstallations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_GetBotInstallations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetBotInstallations(ctx, req.(*GetBotInstallationsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetBotRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBotRateLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetBotRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_GetBotRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetBotRateLimit(ctx, req.(*GetBotRateLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_UpdateBotRateLimit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBotRateLimitReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).UpdateBotRateLimit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_UpdateBotRateLimit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).UpdateBotRateLimit(ctx, req.(*UpdateBotRateLimitReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_RegenerateCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateCredentialReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).RegenerateCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_RegenerateCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).RegenerateCredential(ctx, req.(*RegenerateCredentialReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_RotateWebhookSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateWebhookSecretReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).RotateWebhookSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_RotateWebhookSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).RotateWebhookSecret(ctx, req.(*RotateWebhookSecretReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetEventDeliveries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventDeliveriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetEventDeliveries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_GetEventDeliveries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetEventDeliveries(ctx, req.(*GetEventDeliveriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_RetryEventDelivery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryEventDeliveryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).RetryEventDelivery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_RetryEventDelivery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).RetryEventDelivery(ctx, req.(*RetryEventDeliveryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_GetConvBots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConvBotsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).GetConvBots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_GetConvBots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).GetConvBots(ctx, req.(*GetConvBotsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_InstallBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).InstallBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_InstallBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).InstallBot(ctx, req.(*InstallBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_UninstallBot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UninstallBotReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).UninstallBot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_UninstallBot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).UninstallBot(ctx, req.(*UninstallBotReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotGetConv_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotGetConvReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotGetConv(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotGetConv_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotGetConv(ctx, req.(*BotGetConvReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotGetConvMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotGetConvMembersReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotGetConvMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotGetConvMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotGetConvMembers(ctx, req.(*BotGetConvMembersReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotGetMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotGetMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotGetMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotGetMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotGetMsg(ctx, req.(*BotGetMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotSendMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotSendMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotSendMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotSendMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotSendMsg(ctx, req.(*BotSendMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotRecallMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotRecallMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotRecallMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotRecallMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotRecallMsg(ctx, req.(*BotRecallMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotReplyMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotReplyMsgReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotReplyMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotReplyMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotReplyMsg(ctx, req.(*BotReplyMsgReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotUploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotUploadFileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotUploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotUploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotUploadFile(ctx, req.(*BotUploadFileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotGetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotGetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotGetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotGetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotGetUser(ctx, req.(*BotGetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_Authorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).Authorize(ctx, req.(*AuthorizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_ApproveAuthorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveAuthorizeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).ApproveAuthorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_ApproveAuthorize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).ApproveAuthorize(ctx, req.(*ApproveAuthorizeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bot_BotToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BotTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BotServer).BotToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bot_BotToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BotServer).BotToken(ctx, req.(*BotTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Bot_ServiceDesc is the grpc.ServiceDesc for Bot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bot.bot",
	HandlerType: (*BotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBot",
			Handler:    _Bot_CreateBot_Handler,
		},
		{
			MethodName: "ListMyBots",
			Handler:    _Bot_ListMyBots_Handler,
		},
		{
			MethodName: "ListCommunityBots",
			Handler:    _Bot_ListCommunityBots_Handler,
		},
		{
			MethodName: "GetBot",
			Handler:    _Bot_GetBot_Handler,
		},
		{
			MethodName: "UpdateBot",
			Handler:    _Bot_UpdateBot_Handler,
		},
		{
			MethodName: "DeleteBot",
			Handler:    _Bot_DeleteBot_Handler,
		},
		{
			MethodName: "GetBotInstallations",
			Handler:    _Bot_GetBotInstallations_Handler,
		},
		{
			MethodName: "GetBotRateLimit",
			Handler:    _Bot_GetBotRateLimit_Handler,
		},
		{
			MethodName: "UpdateBotRateLimit",
			Handler:    _Bot_UpdateBotRateLimit_Handler,
		},
		{
			MethodName: "RegenerateCredential",
			Handler:    _Bot_RegenerateCredential_Handler,
		},
		{
			MethodName: "RotateWebhookSecret",
			Handler:    _Bot_RotateWebhookSecret_Handler,
		},
		{
			MethodName: "GetEventDeliveries",
			Handler:    _Bot_GetEventDeliveries_Handler,
		},
		{
			MethodName: "RetryEventDelivery",
			Handler:    _Bot_RetryEventDelivery_Handler,
		},
		{
			MethodName: "GetConvBots",
			Handler:    _Bot_GetConvBots_Handler,
		},
		{
			MethodName: "InstallBot",
			Handler:    _Bot_InstallBot_Handler,
		},
		{
			MethodName: "UninstallBot",
			Handler:    _Bot_UninstallBot_Handler,
		},
		{
			MethodName: "BotGetConv",
			Handler:    _Bot_BotGetConv_Handler,
		},
		{
			MethodName: "BotGetConvMembers",
			Handler:    _Bot_BotGetConvMembers_Handler,
		},
		{
			MethodName: "BotGetMsg",
			Handler:    _Bot_BotGetMsg_Handler,
		},
		{
			MethodName: "BotSendMsg",
			Handler:    _Bot_BotSendMsg_Handler,
		},
		{
			MethodName: "BotRecallMsg",
			Handler:    _Bot_BotRecallMsg_Handler,
		},
		{
			MethodName: "BotReplyMsg",
			Handler:    _Bot_BotReplyMsg_Handler,
		},
		{
			MethodName: "BotUploadFile",
			Handler:    _Bot_BotUploadFile_Handler,
		},
		{
			MethodName: "BotGetUser",
			Handler:    _Bot_BotGetUser_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _Bot_Authorize_Handler,
		},
		{
			MethodName: "ApproveAuthorize",
			Handler:    _Bot_ApproveAuthorize_Handler,
		},
		{
			MethodName: "BotToken",
			Handler:    _Bot_BotToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bot.proto",
}
