// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: conversation.proto

package conversationclient

import (
	"context"

	"conversation/conversation"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddConvMembersReq         = conversation.AddConvMembersReq
	AddConvMembersResp        = conversation.AddConvMembersResp
	ClearUnreadReq            = conversation.ClearUnreadReq
	ClearUnreadResp           = conversation.ClearUnreadResp
	ConversationItem          = conversation.ConversationItem
	CreateGroupConvReq        = conversation.CreateGroupConvReq
	CreateGroupConvResp       = conversation.CreateGroupConvResp
	DeleteConversationReq     = conversation.DeleteConversationReq
	DeleteConversationResp    = conversation.DeleteConversationResp
	GetConvMembersReq         = conversation.GetConvMembersReq
	GetConvMembersResp        = conversation.GetConvMembersResp
	GetConversationReq        = conversation.GetConversationReq
	GetConversationResp       = conversation.GetConversationResp
	GetConversationsReq       = conversation.GetConversationsReq
	GetConversationsResp      = conversation.GetConversationsResp
	GetOrCreateSingleConvReq  = conversation.GetOrCreateSingleConvReq
	GetOrCreateSingleConvResp = conversation.GetOrCreateSingleConvResp
	GetTotalUnreadReq         = conversation.GetTotalUnreadReq
	GetTotalUnreadResp        = conversation.GetTotalUnreadResp
	RemoveConvMembersReq      = conversation.RemoveConvMembersReq
	RemoveConvMembersResp     = conversation.RemoveConvMembersResp
	SetConvMuteReq            = conversation.SetConvMuteReq
	SetConvMuteResp           = conversation.SetConvMuteResp
	SetConvPinReq             = conversation.SetConvPinReq
	SetConvPinResp            = conversation.SetConvPinResp
	UpdateLastMessageReq      = conversation.UpdateLastMessageReq
	UpdateLastMessageResp     = conversation.UpdateLastMessageResp
	IncrementUnreadReq        = conversation.IncrementUnreadReq
	IncrementUnreadResp       = conversation.IncrementUnreadResp

	Conversation interface {
		GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error)
		GetOrCreateSingleConv(ctx context.Context, in *GetOrCreateSingleConvReq, opts ...grpc.CallOption) (*GetOrCreateSingleConvResp, error)
		GetConversation(ctx context.Context, in *GetConversationReq, opts ...grpc.CallOption) (*GetConversationResp, error)
		DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error)
		SetConvMute(ctx context.Context, in *SetConvMuteReq, opts ...grpc.CallOption) (*SetConvMuteResp, error)
		SetConvPin(ctx context.Context, in *SetConvPinReq, opts ...grpc.CallOption) (*SetConvPinResp, error)
		CreateGroupConv(ctx context.Context, in *CreateGroupConvReq, opts ...grpc.CallOption) (*CreateGroupConvResp, error)
		AddConvMembers(ctx context.Context, in *AddConvMembersReq, opts ...grpc.CallOption) (*AddConvMembersResp, error)
		RemoveConvMembers(ctx context.Context, in *RemoveConvMembersReq, opts ...grpc.CallOption) (*RemoveConvMembersResp, error)
		GetConvMembers(ctx context.Context, in *GetConvMembersReq, opts ...grpc.CallOption) (*GetConvMembersResp, error)
		ClearUnread(ctx context.Context, in *ClearUnreadReq, opts ...grpc.CallOption) (*ClearUnreadResp, error)
		GetTotalUnread(ctx context.Context, in *GetTotalUnreadReq, opts ...grpc.CallOption) (*GetTotalUnreadResp, error)
		UpdateLastMessage(ctx context.Context, in *UpdateLastMessageReq, opts ...grpc.CallOption) (*UpdateLastMessageResp, error)
		IncrementUnread(ctx context.Context, in *IncrementUnreadReq, opts ...grpc.CallOption) (*IncrementUnreadResp, error)
	}

	defaultConversation struct {
		cli zrpc.Client
	}
)

func NewConversation(cli zrpc.Client) Conversation {
	return &defaultConversation{
		cli: cli,
	}
}

func (m *defaultConversation) GetConversations(ctx context.Context, in *GetConversationsReq, opts ...grpc.CallOption) (*GetConversationsResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.GetConversations(ctx, in, opts...)
}

func (m *defaultConversation) GetOrCreateSingleConv(ctx context.Context, in *GetOrCreateSingleConvReq, opts ...grpc.CallOption) (*GetOrCreateSingleConvResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.GetOrCreateSingleConv(ctx, in, opts...)
}

func (m *defaultConversation) GetConversation(ctx context.Context, in *GetConversationReq, opts ...grpc.CallOption) (*GetConversationResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.GetConversation(ctx, in, opts...)
}

func (m *defaultConversation) DeleteConversation(ctx context.Context, in *DeleteConversationReq, opts ...grpc.CallOption) (*DeleteConversationResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.DeleteConversation(ctx, in, opts...)
}

func (m *defaultConversation) SetConvMute(ctx context.Context, in *SetConvMuteReq, opts ...grpc.CallOption) (*SetConvMuteResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.SetConvMute(ctx, in, opts...)
}

func (m *defaultConversation) SetConvPin(ctx context.Context, in *SetConvPinReq, opts ...grpc.CallOption) (*SetConvPinResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.SetConvPin(ctx, in, opts...)
}

func (m *defaultConversation) CreateGroupConv(ctx context.Context, in *CreateGroupConvReq, opts ...grpc.CallOption) (*CreateGroupConvResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.CreateGroupConv(ctx, in, opts...)
}

func (m *defaultConversation) AddConvMembers(ctx context.Context, in *AddConvMembersReq, opts ...grpc.CallOption) (*AddConvMembersResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.AddConvMembers(ctx, in, opts...)
}

func (m *defaultConversation) RemoveConvMembers(ctx context.Context, in *RemoveConvMembersReq, opts ...grpc.CallOption) (*RemoveConvMembersResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.RemoveConvMembers(ctx, in, opts...)
}

func (m *defaultConversation) GetConvMembers(ctx context.Context, in *GetConvMembersReq, opts ...grpc.CallOption) (*GetConvMembersResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.GetConvMembers(ctx, in, opts...)
}

func (m *defaultConversation) ClearUnread(ctx context.Context, in *ClearUnreadReq, opts ...grpc.CallOption) (*ClearUnreadResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.ClearUnread(ctx, in, opts...)
}

func (m *defaultConversation) GetTotalUnread(ctx context.Context, in *GetTotalUnreadReq, opts ...grpc.CallOption) (*GetTotalUnreadResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.GetTotalUnread(ctx, in, opts...)
}

func (m *defaultConversation) UpdateLastMessage(ctx context.Context, in *UpdateLastMessageReq, opts ...grpc.CallOption) (*UpdateLastMessageResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.UpdateLastMessage(ctx, in, opts...)
}

func (m *defaultConversation) IncrementUnread(ctx context.Context, in *IncrementUnreadReq, opts ...grpc.CallOption) (*IncrementUnreadResp, error) {
	client := conversation.NewConversationClient(m.cli.Conn())
	return client.IncrementUnread(ctx, in, opts...)
}
