// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	auth "gateway/internal/handler/auth"
	bot "gateway/internal/handler/bot"
	conversation "gateway/internal/handler/conversation"
	message "gateway/internal/handler/message"
	oauth2 "gateway/internal/handler/oauth2"
	oss "gateway/internal/handler/oss"
	social "gateway/internal/handler/social"
	"gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/login/finalize",
				Handler: auth.LoginFinalizeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/init",
				Handler: auth.LoginInitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register/finalize",
				Handler: auth.RegisterFinalizeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/register/init",
				Handler: auth.RegisterInitHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/tfa-verify",
				Handler: auth.TFAVerifyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user_info/:uid",
				Handler: auth.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/auth"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/bots",
					Handler: bot.CreateBotHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/bots",
					Handler: bot.ListMyBotsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/bots/:bot_id",
					Handler: bot.GetBotHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/bots/:bot_id",
					Handler: bot.UpdateBotHandler(serverCtx),
				},
				{
					Method:  http.MethodDelete,
					Path:    "/bots/:bot_id",
					Handler: bot.DeleteBotHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/bots/:bot_id/credentials/regenerate",
					Handler: bot.RegenerateCredentialHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/bots/:bot_id/event-deliveries",
					Handler: bot.GetEventDeliveriesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/bots/:bot_id/event-deliveries/:event_id/retry",
					Handler: bot.RetryEventDeliveryHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/bots/:bot_id/installations",
					Handler: bot.GetBotInstallationsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/bots/:bot_id/rate-limit",
					Handler: bot.GetBotRateLimitHandler(serverCtx),
				},
				{
					Method:  http.MethodPut,
					Path:    "/bots/:bot_id/rate-limit",
					Handler: bot.UpdateBotRateLimitHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/bots/:bot_id/webhook-secret/rotate",
					Handler: bot.RotateWebhookSecretHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/bot/developer"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/bots",
					Handler: bot.ListCommunityBotsHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/bot/community"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/convs/:conv_id/bots",
					Handler: bot.GetConvBotsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/convs/:conv_id/bots/install",
					Handler: bot.InstallBotHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/convs/:conv_id/bots/uninstall",
					Handler: bot.UninstallBotHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/bot/installation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/convs/:conv_id",
					Handler: bot.BotGetConvHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/convs/:conv_id/members",
					Handler: bot.BotGetConvMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/convs/:conv_id/msgs",
					Handler: bot.BotSendMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/convs/:conv_id/msgs/:msg_id",
					Handler: bot.BotGetMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/convs/:conv_id/msgs/:msg_id/recall",
					Handler: bot.BotRecallMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/convs/:conv_id/msgs/reply",
					Handler: bot.BotReplyMsgHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/files",
					Handler: bot.BotUploadFileHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/users/:uid",
					Handler: bot.BotGetUserHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/bot"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/authorize",
				Handler: bot.BotAuthorizeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/token",
				Handler: bot.BotTokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/bot/oauth2"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/authorize",
					Handler: bot.ApproveAuthorizeHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/bot/oauth2"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:conv_id",
					Handler: conversation.GetConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/clear_unread",
					Handler: conversation.ClearUnreadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/delete",
					Handler: conversation.DeleteConversationHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/list",
					Handler: conversation.GetConversationsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/mute",
					Handler: conversation.SetConvMuteHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/pin",
					Handler: conversation.SetConvPinHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/single",
					Handler: conversation.GetOrCreateSingleConvHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/total_unread",
					Handler: conversation.GetTotalUnreadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/conversation"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/:conv_id",
					Handler: message.GetMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/:conv_id/read/:msg_id",
					Handler: message.GetMessageReadMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/edit",
					Handler: message.EditMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/recall",
					Handler: message.RecallMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/search",
					Handler: message.SearchMessagesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/send",
					Handler: message.SendMessageHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/sync",
					Handler: message.SyncOfflineMessagesHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/message"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/authorize",
				Handler: oauth2.AuthorizeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/token",
				Handler: oauth2.TokenHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/oauth2"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: oss.UploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/complete",
					Handler: oss.CompleteUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/initiate",
					Handler: oss.InitiateUploadHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/upload/part",
					Handler: oss.UploadPartHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/oss"),
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuthMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodGet,
					Path:    "/blacklist",
					Handler: social.GetBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/blacklist/add",
					Handler: social.AddBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/blacklist/remove",
					Handler: social.RemoveBlacklistHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friend/delete",
					Handler: social.DeleteFriendHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friend/remark",
					Handler: social.UpdateFriendRemarkHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friend/request",
					Handler: social.SendFriendRequestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/friend/request/:id",
					Handler: social.HandleFriendRequestHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friend/requests",
					Handler: social.GetFriendRequestsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/friends",
					Handler: social.GetFriendsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/:group_id",
					Handler: social.GetGroupInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/:group_id/announcements",
					Handler: social.GetAnnouncementsHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/:group_id/members",
					Handler: social.GetGroupMembersHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/:group_id/requests",
					Handler: social.GetGroupJoinRequestsHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/announcement",
					Handler: social.CreateAnnouncementHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/create",
					Handler: social.CreateGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/invite",
					Handler: social.InviteToGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/invite/:id",
					Handler: social.HandleGroupInviteHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/group/invites",
					Handler: social.GetGroupInvitesHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/join",
					Handler: social.JoinGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/join/:id",
					Handler: social.HandleGroupJoinRequestHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/kick",
					Handler: social.KickMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/leave",
					Handler: social.LeaveGroupHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/mute",
					Handler: social.MuteMemberHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/transfer",
					Handler: social.TransferOwnerHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/group/update",
					Handler: social.UpdateGroupHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/social"),
	)
}
