// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0--rc1
// source: auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterInitReq struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Phone               string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	RegistrationRequest []byte                 `protobuf:"bytes,2,opt,name=registration_request,json=registrationRequest,proto3" json:"registration_request,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RegisterInitReq) Reset() {
	*x = RegisterInitReq{}
	mi := &file_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInitReq) ProtoMessage() {}

func (x *RegisterInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInitReq.ProtoReflect.Descriptor instead.
func (*RegisterInitReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterInitReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterInitReq) GetRegistrationRequest() []byte {
	if x != nil {
		return x.RegistrationRequest
	}
	return nil
}

type RegisterInitResp struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ServerPublicKey      []byte                 `protobuf:"bytes,1,opt,name=server_public_key,json=serverPublicKey,proto3" json:"server_public_key,omitempty"`
	RegistrationResponse []byte                 `protobuf:"bytes,2,opt,name=registration_response,json=registrationResponse,proto3" json:"registration_response,omitempty"`
	CredentialIdentifier []byte                 `protobuf:"bytes,3,opt,name=credential_identifier,json=credentialIdentifier,proto3" json:"credential_identifier,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterInitResp) Reset() {
	*x = RegisterInitResp{}
	mi := &file_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterInitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterInitResp) ProtoMessage() {}

func (x *RegisterInitResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterInitResp.ProtoReflect.Descriptor instead.
func (*RegisterInitResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterInitResp) GetServerPublicKey() []byte {
	if x != nil {
		return x.ServerPublicKey
	}
	return nil
}

func (x *RegisterInitResp) GetRegistrationResponse() []byte {
	if x != nil {
		return x.RegistrationResponse
	}
	return nil
}

func (x *RegisterInitResp) GetCredentialIdentifier() []byte {
	if x != nil {
		return x.CredentialIdentifier
	}
	return nil
}

type RegisterFinalizeReq struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Phone              string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RegistrationRecord []byte                 `protobuf:"bytes,3,opt,name=registration_record,json=registrationRecord,proto3" json:"registration_record,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterFinalizeReq) Reset() {
	*x = RegisterFinalizeReq{}
	mi := &file_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFinalizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFinalizeReq) ProtoMessage() {}

func (x *RegisterFinalizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFinalizeReq.ProtoReflect.Descriptor instead.
func (*RegisterFinalizeReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterFinalizeReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterFinalizeReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterFinalizeReq) GetRegistrationRecord() []byte {
	if x != nil {
		return x.RegistrationRecord
	}
	return nil
}

type RegisterFinalizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterFinalizeResp) Reset() {
	*x = RegisterFinalizeResp{}
	mi := &file_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterFinalizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterFinalizeResp) ProtoMessage() {}

func (x *RegisterFinalizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterFinalizeResp.ProtoReflect.Descriptor instead.
func (*RegisterFinalizeResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterFinalizeResp) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *RegisterFinalizeResp) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type LoginInitReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Ke1           []byte                 `protobuf:"bytes,2,opt,name=ke1,proto3" json:"ke1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInitReq) Reset() {
	*x = LoginInitReq{}
	mi := &file_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInitReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInitReq) ProtoMessage() {}

func (x *LoginInitReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInitReq.ProtoReflect.Descriptor instead.
func (*LoginInitReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{4}
}

func (x *LoginInitReq) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginInitReq) GetKe1() []byte {
	if x != nil {
		return x.Ke1
	}
	return nil
}

type LoginInitResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ke2           []byte                 `protobuf:"bytes,1,opt,name=ke2,proto3" json:"ke2,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginInitResp) Reset() {
	*x = LoginInitResp{}
	mi := &file_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginInitResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginInitResp) ProtoMessage() {}

func (x *LoginInitResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginInitResp.ProtoReflect.Descriptor instead.
func (*LoginInitResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LoginInitResp) GetKe2() []byte {
	if x != nil {
		return x.Ke2
	}
	return nil
}

func (x *LoginInitResp) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LoginFinalizeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ke3           []byte                 `protobuf:"bytes,1,opt,name=ke3,proto3" json:"ke3,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFinalizeReq) Reset() {
	*x = LoginFinalizeReq{}
	mi := &file_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFinalizeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFinalizeReq) ProtoMessage() {}

func (x *LoginFinalizeReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFinalizeReq.ProtoReflect.Descriptor instead.
func (*LoginFinalizeReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{6}
}

func (x *LoginFinalizeReq) GetKe3() []byte {
	if x != nil {
		return x.Ke3
	}
	return nil
}

func (x *LoginFinalizeReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LoginFinalizeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Need_2Fa      bool                   `protobuf:"varint,2,opt,name=need_2fa,json=need2fa,proto3" json:"need_2fa,omitempty"`   // 是否需要二次验证
	TfaToken      string                 `protobuf:"bytes,3,opt,name=tfa_token,json=tfaToken,proto3" json:"tfa_token,omitempty"` // 需要2FA时返回的临时 token
	AccessToken   string                 `protobuf:"bytes,4,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,5,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginFinalizeResp) Reset() {
	*x = LoginFinalizeResp{}
	mi := &file_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginFinalizeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginFinalizeResp) ProtoMessage() {}

func (x *LoginFinalizeResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginFinalizeResp.ProtoReflect.Descriptor instead.
func (*LoginFinalizeResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{7}
}

func (x *LoginFinalizeResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LoginFinalizeResp) GetNeed_2Fa() bool {
	if x != nil {
		return x.Need_2Fa
	}
	return false
}

func (x *LoginFinalizeResp) GetTfaToken() string {
	if x != nil {
		return x.TfaToken
	}
	return ""
}

func (x *LoginFinalizeResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginFinalizeResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginFinalizeResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type TFAVerifyReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TfaToken      string                 `protobuf:"bytes,1,opt,name=tfa_token,json=tfaToken,proto3" json:"tfa_token,omitempty"` // 上一步返回的临时 token
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                         // 用户输入的 TOTP 验证码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TFAVerifyReq) Reset() {
	*x = TFAVerifyReq{}
	mi := &file_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFAVerifyReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFAVerifyReq) ProtoMessage() {}

func (x *TFAVerifyReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFAVerifyReq.ProtoReflect.Descriptor instead.
func (*TFAVerifyReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{8}
}

func (x *TFAVerifyReq) GetTfaToken() string {
	if x != nil {
		return x.TfaToken
	}
	return ""
}

func (x *TFAVerifyReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type TFAVerifyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           int64                  `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AccessToken   string                 `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TFAVerifyResp) Reset() {
	*x = TFAVerifyResp{}
	mi := &file_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TFAVerifyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFAVerifyResp) ProtoMessage() {}

func (x *TFAVerifyResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFAVerifyResp.ProtoReflect.Descriptor instead.
func (*TFAVerifyResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{9}
}

func (x *TFAVerifyResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *TFAVerifyResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TFAVerifyResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TFAVerifyResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type LogoutReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutReq) Reset() {
	*x = LogoutReq{}
	mi := &file_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutReq) ProtoMessage() {}

func (x *LogoutReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutReq.ProtoReflect.Descriptor instead.
func (*LogoutReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{10}
}

func (x *LogoutReq) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type LogoutResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResp) Reset() {
	*x = LogoutResp{}
	mi := &file_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResp) ProtoMessage() {}

func (x *LogoutResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResp.ProtoReflect.Descriptor instead.
func (*LogoutResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{11}
}

type RefreshTokenReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenReq) Reset() {
	*x = RefreshTokenReq{}
	mi := &file_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenReq) ProtoMessage() {}

func (x *RefreshTokenReq) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenReq.ProtoReflect.Descriptor instead.
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenReq) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResp) Reset() {
	*x = RefreshTokenResp{}
	mi := &file_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResp) ProtoMessage() {}

func (x *RefreshTokenResp) ProtoReflect() protoreflect.Message {
	mi := &file_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResp.ProtoReflect.Descriptor instead.
func (*RefreshTokenResp) Descriptor() ([]byte, []int) {
	return file_auth_proto_rawDescGZIP(), []int{13}
}

func (x *RefreshTokenResp) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResp) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResp) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_auth_proto protoreflect.FileDescriptor

const file_auth_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"auth.proto\x12\x04auth\"Z\n" +
	"\x0fRegisterInitReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x121\n" +
	"\x14registration_request\x18\x02 \x01(\fR\x13registrationRequest\"\xa8\x01\n" +
	"\x10RegisterInitResp\x12*\n" +
	"\x11server_public_key\x18\x01 \x01(\fR\x0fserverPublicKey\x123\n" +
	"\x15registration_response\x18\x02 \x01(\fR\x14registrationResponse\x123\n" +
	"\x15credential_identifier\x18\x03 \x01(\fR\x14credentialIdentifier\"p\n" +
	"\x13RegisterFinalizeReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x13registration_record\x18\x03 \x01(\fR\x12registrationRecord\"F\n" +
	"\x14RegisterFinalizeResp\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"6\n" +
	"\fLoginInitReq\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x10\n" +
	"\x03ke1\x18\x02 \x01(\fR\x03ke1\"@\n" +
	"\rLoginInitResp\x12\x10\n" +
	"\x03ke2\x18\x01 \x01(\fR\x03ke2\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"C\n" +
	"\x10LoginFinalizeReq\x12\x10\n" +
	"\x03ke3\x18\x01 \x01(\fR\x03ke3\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xc4\x01\n" +
	"\x11LoginFinalizeResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12\x19\n" +
	"\bneed_2fa\x18\x02 \x01(\bR\aneed2fa\x12\x1b\n" +
	"\ttfa_token\x18\x03 \x01(\tR\btfaToken\x12!\n" +
	"\faccess_token\x18\x04 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x05 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"?\n" +
	"\fTFAVerifyReq\x12\x1b\n" +
	"\ttfa_token\x18\x01 \x01(\tR\btfaToken\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\x88\x01\n" +
	"\rTFAVerifyResp\x12\x10\n" +
	"\x03uid\x18\x01 \x01(\x03R\x03uid\x12!\n" +
	"\faccess_token\x18\x02 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\x03R\texpiresAt\".\n" +
	"\tLogoutReq\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\f\n" +
	"\n" +
	"LogoutResp\"6\n" +
	"\x0fRefreshTokenReq\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"y\n" +
	"\x10RefreshTokenResp\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt2\xaa\x03\n" +
	"\x04Auth\x12=\n" +
	"\fRegisterInit\x12\x15.auth.RegisterInitReq\x1a\x16.auth.RegisterInitResp\x12I\n" +
	"\x10RegisterFinalize\x12\x19.auth.RegisterFinalizeReq\x1a\x1a.auth.RegisterFinalizeResp\x124\n" +
	"\tLoginInit\x12\x12.auth.LoginInitReq\x1a\x13.auth.LoginInitResp\x12@\n" +
	"\rLoginFinalize\x12\x16.auth.LoginFinalizeReq\x1a\x17.auth.LoginFinalizeResp\x124\n" +
	"\tTFAVerify\x12\x12.auth.TFAVerifyReq\x1a\x13.auth.TFAVerifyResp\x12+\n" +
	"\x06Logout\x12\x0f.auth.LogoutReq\x1a\x10.auth.LogoutResp\x12=\n" +
	"\fRefreshToken\x12\x15.auth.RefreshTokenReq\x1a\x16.auth.RefreshTokenRespB\bZ\x06./authb\x06proto3"

var (
	file_auth_proto_rawDescOnce sync.Once
	file_auth_proto_rawDescData []byte
)

func file_auth_proto_rawDescGZIP() []byte {
	file_auth_proto_rawDescOnce.Do(func() {
		file_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)))
	})
	return file_auth_proto_rawDescData
}

var file_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_auth_proto_goTypes = []any{
	(*RegisterInitReq)(nil),      // 0: auth.RegisterInitReq
	(*RegisterInitResp)(nil),     // 1: auth.RegisterInitResp
	(*RegisterFinalizeReq)(nil),  // 2: auth.RegisterFinalizeReq
	(*RegisterFinalizeResp)(nil), // 3: auth.RegisterFinalizeResp
	(*LoginInitReq)(nil),         // 4: auth.LoginInitReq
	(*LoginInitResp)(nil),        // 5: auth.LoginInitResp
	(*LoginFinalizeReq)(nil),     // 6: auth.LoginFinalizeReq
	(*LoginFinalizeResp)(nil),    // 7: auth.LoginFinalizeResp
	(*TFAVerifyReq)(nil),         // 8: auth.TFAVerifyReq
	(*TFAVerifyResp)(nil),        // 9: auth.TFAVerifyResp
	(*LogoutReq)(nil),            // 10: auth.LogoutReq
	(*LogoutResp)(nil),           // 11: auth.LogoutResp
	(*RefreshTokenReq)(nil),      // 12: auth.RefreshTokenReq
	(*RefreshTokenResp)(nil),     // 13: auth.RefreshTokenResp
}
var file_auth_proto_depIdxs = []int32{
	0,  // 0: auth.Auth.RegisterInit:input_type -> auth.RegisterInitReq
	2,  // 1: auth.Auth.RegisterFinalize:input_type -> auth.RegisterFinalizeReq
	4,  // 2: auth.Auth.LoginInit:input_type -> auth.LoginInitReq
	6,  // 3: auth.Auth.LoginFinalize:input_type -> auth.LoginFinalizeReq
	8,  // 4: auth.Auth.TFAVerify:input_type -> auth.TFAVerifyReq
	10, // 5: auth.Auth.Logout:input_type -> auth.LogoutReq
	12, // 6: auth.Auth.RefreshToken:input_type -> auth.RefreshTokenReq
	1,  // 7: auth.Auth.RegisterInit:output_type -> auth.RegisterInitResp
	3,  // 8: auth.Auth.RegisterFinalize:output_type -> auth.RegisterFinalizeResp
	5,  // 9: auth.Auth.LoginInit:output_type -> auth.LoginInitResp
	7,  // 10: auth.Auth.LoginFinalize:output_type -> auth.LoginFinalizeResp
	9,  // 11: auth.Auth.TFAVerify:output_type -> auth.TFAVerifyResp
	11, // 12: auth.Auth.Logout:output_type -> auth.LogoutResp
	13, // 13: auth.Auth.RefreshToken:output_type -> auth.RefreshTokenResp
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_auth_proto_init() }
func file_auth_proto_init() {
	if File_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_proto_rawDesc), len(file_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_proto_goTypes,
		DependencyIndexes: file_auth_proto_depIdxs,
		MessageInfos:      file_auth_proto_msgTypes,
	}.Build()
	File_auth_proto = out.File
	file_auth_proto_goTypes = nil
	file_auth_proto_depIdxs = nil
}
